### ISSUE TITLE
execve 出错

### ISSUE THREAD

**Issue by gofmt** [zhkl0228/unidbg#102]
[ INFO][00:18:35][ARMSyscallHandler:1007] execve filename=/system/bin/sh, args=[sh, -c, stat -c "%X|%Y" /storage/emulated], env=[ANDROID_DATA=/data, ANDROID_ROOT=/system]
exit with code: 127

127错误码应该是找不到命令,请教如何处理?

**Comment by gofmt** [comment]
已解决.

**Comment by 18712886438** [comment]
> 已解决.

大佬，想请教一下这里要怎么解决
