### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by meiyinguo** [zhkl0228/unidbg#107]
d7495476e17b33038d000e0f506bb6f3cc924c3c
. OSX 系统10.12.6 (16G1510)
. 全部日志如下：
```
log4j:WARN No appenders could be found for logger (org.scijava.nativelib.NativeLibraryUtil).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/8d/c3s4z1_97x536pd0xhrd5s3m0000gn/T/nativelib-loader_7745203063363062974/libunicorn_java.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/8d/c3s4z1_97x536pd0xhrd5s3m0000gn/T/nativelib-loader_7745203063363062974/libunicorn_java.dylib
  Expected in: /usr/lib/libSystem.B.dylib

```
. 我猜测这个____chkstk_darwin函数是高版本添加的
. 2020年03月14日10:23:15
. 我重新编译了libunicorn_java.dylib但是作者应该是改动了吧，缺少内容，看样子不行

**Comment by zhkl0228** [comment]
ios模拟现在还有很多问题没解决

**Comment by zhkl0228** [comment]
libunicorn_java.dylib已重新编译，更新最新代码试下

**Comment by sawflare** [comment]
```
objc[78327]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10439b4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1043f24e0). One of the two will be used. Which one is undefined.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```
OSX  10.13.6貌似也有问题..

**Comment by zhkl0228** [comment]
> ```
> objc[78327]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10439b4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1043f24e0). One of the two will be used. Which one is undefined.
> dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
>   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> dyld: Symbol not found: ____chkstk_darwin
>   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
> ```
> 
> OSX 10.13.6貌似也有问题..

最新的代码已经重新编译，请试下

**Comment by sawflare** [comment]
> > ```
> > objc[78327]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10439b4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1043f24e0). One of the two will be used. Which one is undefined.
> > dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
> >   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
> >   Expected in: /usr/lib/libSystem.B.dylib
> > 
> > dyld: Symbol not found: ____chkstk_darwin
> >   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
> >   Expected in: /usr/lib/libSystem.B.dylib
> > ```
> > 
> > 
> > OSX 10.13.6貌似也有问题..
> 
> 最新的代码已经重新编译，请试下

10.13.6测试结果一样，我换到10.14就正常了。

**Comment by zhkl0228** [comment]
晚点再发布一个重新测试下，这次用ida打开看了没有导入____chkstk_darwin符号

**Comment by zhkl0228** [comment]
> > > ```
> > > objc[78327]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10439b4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1043f24e0). One of the two will be used. Which one is undefined.
> > > dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
> > >   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
> > >   Expected in: /usr/lib/libSystem.B.dylib
> > > 
> > > dyld: Symbol not found: ____chkstk_darwin
> > >   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
> > >   Expected in: /usr/lib/libSystem.B.dylib
> > > ```
> > > 
> > > 
> > > OSX 10.13.6貌似也有问题..
> > 
> > 
> > 最新的代码已经重新编译，请试下
> 
> 10.13.6测试结果一样，我换到10.14就正常了。

已发布，再试下

**Comment by sawflare** [comment]
> > > > ```
> > > > objc[78327]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10439b4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1043f24e0). One of the two will be used. Which one is undefined.
> > > > dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
> > > >   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
> > > >   Expected in: /usr/lib/libSystem.B.dylib
> > > > 
> > > > dyld: Symbol not found: ____chkstk_darwin
> > > >   Referenced from: /private/var/folders/j2/21bx3mm57jxd9l163l8r2c340000gn/T/nativelib-loader_8361975855201403714/libunicorn_java.dylib
> > > >   Expected in: /usr/lib/libSystem.B.dylib
> > > > ```
> > > > 
> > > > 
> > > > OSX 10.13.6貌似也有问题..
> > > 
> > > 
> > > 最新的代码已经重新编译，请试下
> > 
> > 
> > 10.13.6测试结果一样，我换到10.14就正常了。
> 
> 已发布，再试下

可以了，正常跑起来了。
