### ISSUE TITLE
while invoke douyin libcms.so leviathan method , program warnning & npe

### ISSUE THREAD

**Issue by litterinchina** [zhkl0228/unidbg#118]
请问下怎么解决？问题有点类似于https://github.com/zhkl0228/unidbg/issues/47 这个issue

so文件下载地址（需解压）： https://tntfiles.com/5d74qp4o1q/libcms-zip
代码：

`package com.bkutil;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Module;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.memory.Memory;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
/**
 * Created by xxx on 2020/3/29.
 */
public class Dy {
    private final AndroidEmulator emulator;

    private final VM vm;
    private final Module module;

    private final DvmClass TTEncryptUtils;

    public Dy() throws IOException {
        emulator = new AndroidARMEmulator("com.ss.android.ugc.aweme");
        Memory memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));
        memory.setCallInitFunction();
        vm = emulator.createDalvikVM(null);
        DalvikModule dm = vm.loadLibrary(new File("src/test/resources/so/libcms.so"), false);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();
        TTEncryptUtils = vm.resolveClass("com/ss/sys/ces/a");
    }
    private void destroy() throws IOException {
        emulator.close();
        System.out.println("destroy");
    }

    public static void main(String[] args) throws IOException {
        Dy t = new Dy();
        t.encodeByte();
        t.destroy();
    }

    private String encodeByte() {
        byte[] byteArs = "abcdefgaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".getBytes(StandardCharsets.UTF_8);
        Number ret = TTEncryptUtils.callStaticJniMethod(emulator, "leviathan(II[B)[B",
                -1, ((int) (System.currentTimeMillis() / 1000)), vm.addLocalObject(new ByteArray(byteArs)));
        //ret 返回的是地址，
        Long hash = ret.intValue() & 0xffffffffL;
        //获得其值
        ByteArray str = vm.getObject(hash);
        System.out.println(str.getValue());
        return "";
    }
}
`

**Comment by deathmemory** [comment]
你解决了吗

**Comment by litterinchina** [comment]
> 你解决了吗，我也遇到同样的问题，返回是 null

没呢，感觉，可能得熟悉一下unicorn、动态调试so文件、hook这些后才能搞得定=_=

**Comment by litterinchina** [comment]
@deathmemory ，这个我参考了另一个基于unidbg的项目，看到别人搞定了，按我的理解，大约是因为在so里边还调用链java.lang.Thread的currentThread方法，解决的话就是定义一个类继承AbstractJni类并重写callStaticObjectMethodV方法 ，主要代码片段如下：

![image](https://user-images.githubusercontent.com/13163058/79365747-9f641f80-7f7d-11ea-967d-65b77e38691c.png)
![image](https://user-images.githubusercontent.com/13163058/79365792-b0149580-7f7d-11ea-8480-190bd1ace57a.png)

**Comment by wangdajiu999** [comment]
> @deathmemory ，这个我参考了另一个基于unidbg的项目，看到别人搞定了，按我的理解，大约是因为在so里边还调用链java.lang.Thread的currentThread方法，解决的话就是定义一个类继承AbstractJni类并重写callStaticObjectMethodV方法 ，主要代码片段如下：
> 
> ![image](https://user-images.githubusercontent.com/13163058/79365747-9f641f80-7f7d-11ea-967d-65b77e38691c.png)
> ![image](https://user-images.githubusercontent.com/13163058/79365792-b0149580-7f7d-11ea-8480-190bd1ace57a.png)

代码片段能重新来下吗？就是这个callStaticObjectMethod的解决方案
