### ISSUE TITLE
请问 import cn.banny.unidbg.xxx 和 import com.github.unidbg.xxx 有什么区别吗？

### ISSUE THREAD

**Issue by myvcgit** [zhkl0228/unidbg#119]
我看到别人的测试代码是import cn.banny.unidbg.xxx 
比如 这里的https://github.com/zhkl0228/unidbg/issues/62
我使用的是 import com.github.unidbg.xxx ，
但是我不能用
@Override
public FileIO resolve(File workDir, String pathname, int oflags) {
    System.out.println("---" + pathname);
}
会提示 
Error:(76, 5) java: method does not override or implement a method from a supertype

请问这个方法现在用什么替代了吗？
请问 import cn.banny.unidbg.xxx  和import com.github.unidbg.xxx  有区别吗，cn.banny.unidbg 这个在哪里可以下到？

**Comment by yattin** [comment]
@Override
    public FileResult resolve(Emulator emulator, String pathname, int oflags) {
        if (("/proc/" + emulator.getPid() + "/status").equals(pathname)) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname, "TracerPid:\t0\n".getBytes()));
        }
        if ("/proc/version".equals(pathname)) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname,
                    "Linux version 3.4.0-cyanogenmod+ (zhkl0228@ubuntu) (gcc version 4.7 (GCC) ) #17 SMP PREEMPT Tue Mar 15 18:23:47 CST 2016\n".getBytes()));
        }
        return null;
    }

加个FileResult包装下

**Comment by zhkl0228** [comment]
cn.banny.unidbg.xxx是旧版
新版全部改用包名com.github.unidbg
