### ISSUE TITLE
trace的汇编代码和IDA不一致

### ISSUE THREAD

**Issue by satng** [zhkl0228/unidbg#122]
可以看到打印出来的汇编代码少了
```
0003570E                 LDRH            R5, [R2,R0]
```
出现Invalid memory read (UC_ERR_READ_UNMAPPED)

请问下这个是哪里出现了问题? 

<img width="1358" alt="WX20200406-122226@2x" src="https://user-images.githubusercontent.com/6063500/78522907-87640180-7801-11ea-8900-8dd57e8d5d7d.png">

**Comment by satng** [comment]
估计是反调试的一方法

**Comment by CsFighting** [comment]
嗨，我看了你写的那个调用，我想请教你一些问题，如果可以能联系到你嘛，我的扣扣457049269，谢谢，希望得到你的回复
