### ISSUE TITLE
:-)

### ISSUE THREAD

**Issue by Rh3x4r** [zhkl0228/unidbg#141]

**Comment by Rh3x4r** [comment]
import com.github.unidbg.Emulator;
import com.github.unidbg.arm.ARMEmulator;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.file.NewFileIO;
import com.github.unidbg.file.linux.AndroidFileIO;
import com.github.unidbg.linux.android.AndroidARM64Emulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.linux.android.dvm.array.ArrayObject;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.linux.file.ByteArrayFileIO;
import com.github.unidbg.linux.file.SimpleFileIO;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.utils.Inspector;
import com.sun.org.apache.xml.internal.security.exceptions.Base64DecodingException;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.*;
import java.util.Arrays;
import java.util.Base64;

public class Love extends AbstractJni implements IOResolver {


    private static final Logger logger = LoggerFactory.getLogger(Love.class);

    StackTraceElement[] y;
    private final AndroidARM64Emulator emulator;
    private final VM vm;

    private final DvmClass txt;

    private Love() throws IOException {


        emulator = new AndroidARM64Emulator("com.zhiliaoapp.musically.go");
        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));
        vm = emulator.createDalvikVM(null);
        emulator.getSyscallHandler().addIOResolver(this);

        emulator.getSyscallHandler().setVerbose(true);



        vm.setVerbose(true);
        vm.setJni(this);
        DalvikModule dm = vm.loadLibrary(new File("src/root/libcms.so"), false);

        dm.callJNI_OnLoad(emulator);



     txt = vm.resolveClass("com/ss/sys/ces/a");




    }

    String lol() {


        return "mvgfghgjkyu";
    }


    private void destroy() throws IOException {
        emulator.close();
        System.out.println("destroy");
    }


    public static void main(String[] args) throws Exception {

        Love love = new Love();
        love.op();
        love.destroy();





    }


    @Override
    public FileResult resolve(Emulator emulator, String pathname, int oflags) {


        if (pathname.contains("/data/app/com.zhiliaoapp.musically.go-1/base.apk")){



          return  FileResult.success( new SimpleFileIO(oflags, new File("src/root/basex.s.apk"), pathname));


            }



        return null;
    }

    public void op() throws Base64DecodingException {


       // Number ret = txt.callStaticJniMethod(emulator, "stringFrom()",-1,1234567,new ByteArray("acde74a94e6b493a3399fac83c7c08b35D58B21D9582AF77647FC9902E36AE70f9c001e9334e6e94916682224fbe4e5f00000000000000000000000000000000".getBytes()));


        DvmObject context = vm.resolveClass("android/content/Context").newObject(null);


        Number ret;
       //Number ret = txt.callStaticJniMethod(emulator, "leviathan(II[B)[B",-1,1234567,new ByteArray("acde74a94e6b493a3399fac83c7c08b35D58B21D9582AF77647FC9902E36AE70f9c001e9334e6e94916682224fbe4e5f00000000000000000000000000000000".getBytes()));
      ret = txt.callStaticJniMethod(emulator, "meta(ILandroid/content/Context;Ljava/lang/Object;)Ljava/lang/Object;",103,null,new StringObject(vm,"6752320710881363461"));
       ret = txt.callStaticJniMethod(emulator, "meta(ILandroid/content/Context;Ljava/lang/Object;)Ljava/lang/Object;",104,null,new StringObject(vm,"6752320710881363461"));


       DvmObject ty = vm.resolveClass("com/ss/android/ugc/trill/app/TrillApplication").newObject(null);

        ret = txt.callStaticJniMethod(emulator, "meta(ILandroid/content/Context;Ljava/lang/Object;)Ljava/lang/Object;",222,ty,new StringObject(vm,"cold_start"));



      System.out.println(ret.intValue());
        long hash = ret.intValue() & 0xffffffffL;

        DvmObject array = vm.getObject(hash);
        vm.deleteLocalRefs();

        System.out.println(vm.getObject(hash));








    }




    @Override
    public DvmObject<?> getObjectField(BaseVM vm, DvmObject<?> dvmObject, String signature) {

        switch (signature) {
            case "android/content/pm/ApplicationInfo->sourceDir:Ljava/lang/String;" :
                return new StringObject(vm, "/data/app/com.zhiliaoapp.musically.go-1/base.apk");

        }
        return super.getObjectField(vm, dvmObject, signature);
    }

    @Override
    public DvmObject<?> callObjectMethod(BaseVM vm, DvmObject<?> dvmObject, String signature, VarArg varArg) {



        System.out.println("sexfffff\n\n\n"+signature);

        return super.callObjectMethod(vm, dvmObject, signature, varArg);
    }

    @Override
    public DvmObject<?> callObjectMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {

        Thread thread = Thread.currentThread();

        switch (signature) {

            case "java/lang/String->getBytes()[B":
                StringObject string = (StringObject) dvmObject;
                System.err.println("string=" + string.getValue() );
                return new ByteArray(string.getValue().getBytes());


            case "android/app/Application->getPackageName()Ljava/lang/String;":
                return  new StringObject(vm,"com.zhiliaoapp.musically.go");


            case "android/app/Application->getApplicationInfo()Landroid/content/pm/ApplicationInfo;":

                System.out.println("ljhghfghgdgfddgdgdfg"+signature);
                return vm.resolveClass("android/content/pm/ApplicationInfo").newObject(null);

            case "java/lang/Thread->getStackTrace()[Ljava/lang/StackTraceElement;":
                StackTraceElement[] elements = thread.getStackTrace();
                DvmObject[] objs = new DvmObject[elements.length];
                for (int i = 0; i < elements.length; i++) {
                    objs[i] = vm.resolveClass("java/lang/StackTraceElement").newObject(elements[i]);
                }
                return new ArrayObject(objs);
            case "java/lang/StackTraceElement->getClassName()Ljava/lang/String;":
                StackTraceElement element = (StackTraceElement) dvmObject.getValue();
                System.out.println(dvmObject.getValue());
                return new StringObject(vm, element.getClassName());
            case "android/content/Context->getApplicationInfo()Landroid/content/pm/ApplicationInfo;":
                return vm.resolveClass("Landroid/content/pm/ApplicationInfo").newObject(null);



        }
        System.out.println("love-->"+signature);

       return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }

    @Override
    public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        Thread thread = Thread.currentThread();
        switch (signature){

            case "com/ss/sys/ces/a->njss(ILjava/lang/Object;)Ljava/lang/Object;":
                int p1 = vaList.getInt(0);
                Object p2 = vaList.getObject(4);
                if (p1==131){

                    byte[] xop= Base64.getDecoder().decode("MIIEqDCCA5CgAwIBAgIJAJNurL4H8gHfMA0GCSqGSIb3DQEBBQUAMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEQMA4GA1UEChMHQW5kcm9pZDEQMA4GA1UECxMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDEiMCAGCSqGSIb3DQEJARYTYW5kcm9pZEBhbmRyb2lkLmNvbTAeFw0wODAyMjkwMTMzNDZaFw0zNTA3MTcwMTMzNDZaMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEQMA4GA1UEChMHQW5kcm9pZDEQMA4GA1UECxMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDEiMCAGCSqGSIb3DQEJARYTYW5kcm9pZEBhbmRyb2lkLmNvbTCCASAwDQYJKoZIhvcNAQEBBQADggENADCCAQgCggEBANaTGQTexgskse3HYuDZ2CU+Ps1s6x3i/waMqOi8qM1r03hupwqnbOYOuw+ZNVn/2T53qUPn6D1LZLjk/qLT5lbx4meoG7+yMLV4wgRDvkxyGLhG9SEVhvA4oU6Jwr44f46+z4/Kw9oe4zDJ6pPQp8PcSvNQIg1QCAcy4ICXF+5qBTNZ5qaU7Cyz8oSgpGbIepTYOzEJOmc3Li9kEsBubULxWBjf/gOBzAzURNps3cO4JFgZSAGzJWQTT7/emMkod0jb9WdqVA2BVMi7yge54kdVMxHEa5r3b97szI5p58ii0I54JiCUP5lyfTwE/nKZHZnfm644oLIXf6MdW2r+6R8CAQOjgfwwgfkwHQYDVR0OBBYEFEhZAFY9JyxGrhGGBaR0GawJyowRMIHJBgNVHSMEgcEwgb6AFEhZAFY9JyxGrhGGBaR0GawJyowRoYGapIGXMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEQMA4GA1UEChMHQW5kcm9pZDEQMA4GA1UECxMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDEiMCAGCSqGSIb3DQEJARYTYW5kcm9pZEBhbmRyb2lkLmNvbYIJAJNurL4H8gHfMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAHqvlozrUMRBBVEY0NqrrwFbinZaJ6cVosK0TyIUFf/azgMJWr+kLfcHCHJsIGnlw27drgQAvilFLAhLwn62oX6snb4YLCBOsVMR9FXYJLZW2+TcIkCRLXWG/oiVHQGo/rWuWkJgU134NDEFJCJGjDbiLCpe+ZTWHdcwauTJ9pUbo8EvHRkU3cYfGmLaLfgn9gP+pWA7LFQNvXwBnDa6sppCccEX31I828XzgXpJ4O+mDL1/dBd+ek8ZPUP0IgdyZm5MTYPhvVqGCHzzTy3sIeJFymwrsBbmg2OAUNLEMO6nwmocSdN2ClirfxqCzJOLSDE4QyS9BAH6EhY6UFcOaE0=");

                    return new ByteArray(xop);
                }



        }


        return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);
    }


    @Override
    public DvmObject<?> newObjectV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
       switch (signature){





       }

        return super.newObjectV(vm, dvmClass, signature, vaList);
    }

}

**Comment by satng** [comment]
哪个版本的cms?

**Comment by Rh3x4r** [comment]
https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically.go&hl=en_IN

**Comment by Rh3x4r** [comment]
最新版本
