### ISSUE TITLE
求大佬帮忙看下，android native 静态注册函数调用出现 memory failed

### ISSUE THREAD

**Issue by huojiaan** [zhkl0228/unidbg#147]
//代码如下
package com.tzrd;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Module;
import com.github.unidbg.Symbol;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.memory.MemoryBlock;

import java.io.File;
import java.io.IOException;

/**
 * @author huoja
 * @date 2020/6/8 下午3:43
 */
public class TzrdClient extends AbstractJni {
    private static final String APP_PACKAGE_NAME = "com.maihan.tredian";

    //创建安卓的模拟器
    private final AndroidEmulator emulator;

    //创建虚拟机
    private final VM vm;

    //创建运行模块
    private final Module module;

    //android native 类
    private final DvmClass Native;

    //创建对应的报名安卓模拟器
    private static AndroidEmulator createARMEmulator() {
        return new AndroidARMEmulator(APP_PACKAGE_NAME);
    }

    private TzrdClient() throws Exception {
        emulator = createARMEmulator();

        Memory memory = emulator.getMemory();

        memory.setLibraryResolver(new AndroidResolver(23));

        vm = emulator.createDalvikVM(null);

        vm.setJni(this);

        vm.setVerbose(true);

        DalvikModule dm = vm.loadLibrary(new File("src/test/resources/example_binaries/armeabi-v7a/libtre.so"),false);

        dm.callJNI_OnLoad(emulator);

        module = dm.getModule();

        Native = vm.resolveClass("com/maihan/tredian/util");

        Symbol __system_property_get = module.findSymbolByName("__system_property_get",true);

        MemoryBlock block = memory.malloc(0x20);

        Number ret = __system_property_get.call(emulator,"ro.build.version.sdk",block.getPointer())[0];

        System.out.println("sdk=" + new String(block.getPointer().getByteArray(0,ret.intValue())) + ", libc=" + memory.findModule("libc.so"));

        Symbol Java_com_maihan_tredian_util_TreUtil_sign = module.findSymbolByName("Java_com_maihan_tredian_util_TreUtil_sign");

        Number ret2 = Java_com_maihan_tredian_util_TreUtil_sign.call(emulator, "this is a test")[0];

        long address = ret2.intValue() & 0xffffffffL;

        String sign = (String) vm.getObject(address).getValue();

        System.out.println(sign);

    }

    private void destroy() throws IOException {
        emulator.close();
    }

    public static void main(String args[]) {
        try {
            TzrdClient tzrdClient = new TzrdClient();
            tzrdClient.destroy();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by huojiaan** [comment]
[libtre.so.zip](https://github.com/zhkl0228/unidbg/files/4750757/libtre.so.zip)

**Comment by huojiaan** [comment]
[com.meilishuo_144115188276579027_10.0.0.2220_1000005.apk.zip](https://github.com/zhkl0228/unidbg/files/4750766/com.meilishuo_144115188276579027_10.0.0.2220_1000005.apk.zip)

**Comment by huojiaan** [comment]
sdk=23, libc=LinuxModule{base=0x40006000, size=540672, name='libc.so'}
java.lang.NullPointerException
	at com.tzrd.TzrdClient.<init>(TzrdClient.java:73)
	at com.tzrd.TzrdClient.main(TzrdClient.java:85)
[16:01:31 027]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:55) - memory failed: address=0x73696b18, size=4, value=0x0, PC=RX@0x400019a8[libtre.so]0x19a8, LR=unicorn@0x62
[16:01:31 030]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:349) - emulate RX@0x40001981[libtre.so]0x1981 exception sp=unicorn@0xbffff608, msg=Invalid memory read (UC_ERR_READ_UNMAPPED), offset=5ms

**Comment by zhkl0228** [comment]
jni方法不是这样调用，参考测试用例

**Comment by huojiaan** [comment]
你好，作者大哥，我之前尝试 用 callStaticJniMethod 调用， 但是发现这个so 是静态注册的， 没有调用jni_onload来注册函数 ，所以调用这个函数 callStaticJniMethod 出现找不到那个我需要调用的函数，所以才尝试用  module.callFunction

**Comment by huojiaan** [comment]
以下是错误信息
Connected to the target VM, address: '127.0.0.1:51470', transport: 'socket'
sdk=23, libc=LinuxModule{base=0x40006000, size=540672, name='libc.so'}
Disconnected from the target VM, address: '127.0.0.1:51470', transport: 'socket'
java.lang.IllegalArgumentException: find method failed: sign(Ljava/lang/String;)Ljava/lang/String
	at com.github.unidbg.linux.android.dvm.DvmClass.findNativeFunction(DvmClass.java:213)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:39)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:222)
	at com.tzrd.TzrdClient.main(TzrdClient.java:79)

**Comment by huojiaan** [comment]
![image](https://user-images.githubusercontent.com/7390994/84151719-579dd800-aa96-11ea-8360-cd32b5878d6a.png)

**Comment by huojiaan** [comment]
> jni方法不是这样调用，参考测试用例

你好，作者大哥，我之前尝试 用 callStaticJniMethod 调用， 但是发现这个so 是静态注册的， 没有调用jni_onload来注册函数 ，所以调用这个函数 callStaticJniMethod 出现找不到那个我需要调用的函数，所以才尝试用 module.callFunction

**Comment by huojiaan** [comment]
这个是我自己写的一个apk 调用刚刚那个so 的例子
![image](https://user-images.githubusercontent.com/7390994/84151885-8b78fd80-aa96-11ea-8e11-120e13efe571.png)

**Comment by zhkl0228** [comment]
Native = vm.resolveClass("com/maihan/tredian/util.TreUtil");

**Comment by huojiaan** [comment]
> Native = vm.resolveClass("com/maihan/tredian/util/TreUtil");

你好，噢噢，我搞错了，加漏了，我再试试，谢谢🙏
