### ISSUE TITLE
unidbg升级到最新版后 跑不起来libsgmain.so  

### ISSUE THREAD

**Issue by jtduan** [zhkl0228/unidbg#152]
unidbg升级到最新版后 跑不起来libsgmain.so ,去年6月的版本是可以跑起来的，求修复
测试代码:

package com.bytedance.frameworks.core.encrypt;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import com.github.unidbg.Emulator;
import com.github.unidbg.LibraryResolver;
import com.github.unidbg.arm.ARMEmulator;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.AbstractJni;
import com.github.unidbg.linux.android.dvm.BaseVM;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.DvmObject;
import com.github.unidbg.linux.android.dvm.StringObject;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.VarArg;
import com.github.unidbg.linux.android.dvm.array.ArrayObject;
import com.github.unidbg.linux.android.dvm.wrapper.DvmBoolean;
import com.github.unidbg.linux.android.dvm.wrapper.DvmInteger;
import com.github.unidbg.linux.file.ByteArrayFileIO;
import com.github.unidbg.linux.file.SimpleFileIO;
import com.github.unidbg.memory.Memory;

public class TestSignso extends AbstractJni implements IOResolver {

    private static LibraryResolver createLibraryResolver() {
        return new AndroidResolver(19);
    }

    private static AndroidARMEmulator createARMEmulator() {
        return new AndroidARMEmulator();
    }

    private final AndroidARMEmulator emulator;
    private final VM vm;

    private final DvmClass Native;

    private TestSignso() throws IOException {
//        Logger.getLogger("cn.banny.unidbg.AbstractEmulator").setLevel(Level.DEBUG);

        emulator = createARMEmulator();
        emulator.getSyscallHandler().addIOResolver(this);
        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(createLibraryResolver());

        vm = emulator.createDalvikVM(APK_FILE);
        vm.setJni(this);
        DalvikModule dm = vm.loadLibrary("sgmainso-6.4.152", false);
        dm.callJNI_OnLoad(emulator);

        Native = vm.resolveClass("com.taobao.wireless.security.adapter.JNICLibrary".replace(".", "/"));
    }

    private static final String APK_INSTALL_PATH = "/data/app/test.apk";
    private static final File APK_FILE = new File("unidbg-android/src/test/resources/app/com.taobao.taobao_8.8.0_243.apk");

    @Override
    public FileResult resolve(Emulator emulator, String pathname, int oflags) {
        if (pathname.equals(APK_INSTALL_PATH)) {
            return FileResult.success(new SimpleFileIO(oflags, APK_FILE, pathname));
        }

        if (("/proc/self/status").equals(pathname)) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname, ("TracerPid:\t0\nState" +
                    ":\tr\n").getBytes()));
        }
        if (("/proc/" + emulator.getPid() + "/stat").equals(pathname)) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname, (emulator.getPid() +
                    " (a.out) R 6723 6873 6723 34819 6873 8388608 77 0 0 0 41958 31 0 0 25 0 3 0 5882654 1409024 56 4294967295 134512640 134513720 3215579040 0 2097798 0 0 0 0 0 0 0 17 0 0 0\n").getBytes()));
        }
        if (("/proc/" + emulator.getPid() + "/wchan").equals(pathname)) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname,
                    "sys_epoll".getBytes()));
        }

        return null;
    }

    private void destroy() throws IOException {
        emulator.close();
        System.out.println("destroy");
    }

    public static void main(String[] args) throws Exception {
        TestSignso test = new TestSignso();
        test.test();
        test.destroy();
    }

    private void test() {
        DvmObject context = vm.resolveClass("android/content/Context").newObject(null);
        long start = System.currentTimeMillis();
        Number ret = Native.callStaticJniMethod(emulator, "doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object;",
                10101,
                new ArrayObject(context, DvmInteger.valueOf(vm, 3), new StringObject(vm, ""), new StringObject(vm, new File("target/app_SGLib").getAbsolutePath()), new StringObject(vm, ""))
        );
        long hash = ret.intValue() & 0xffffffffL;
        DvmObject dvmObject = vm.getObject(hash);
        System.out.println("hash:" + hash + ", dvmObject=" + dvmObject + ", offset=" + (System.currentTimeMillis() - start) + "ms");
        vm.deleteLocalRefs();

        Map<String, String> map = new HashMap<>();
        map.put("INPUT", "XPDlGfM+zOoDAMHyPLa9+Okq&&&21646297&99914b932bd37a50b983c5e7c90ae93b&1560149480&mtop.common.gettimestamp&*&&231200@taobao_android_8.8.0&AjA1TIyT9T8vcuFw8Osrli35ALbE3ZW2SHLZNuihw8Ku&&&27&&&&&&&");
        start = System.currentTimeMillis();
        ret = Native.callStaticJniMethod(emulator, "doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object;",
                10401,
                new ArrayObject(vm.resolveClass("java/util/HashMap").newObject(map),
                        new StringObject(vm, "21646297"), DvmInteger.valueOf(vm, 7), null, DvmBoolean.valueOf(vm, true)));
        hash = ret.intValue() & 0xffffffffL;
        dvmObject = vm.getObject(hash);
        System.out.println("hash:" + hash + ", dvmObject=" + dvmObject + ", offset=" + (System.currentTimeMillis() - start) + "ms");
        vm.deleteLocalRefs();
        System.out.println("=========" + dvmObject);
    }

    @Override
    public DvmObject callStaticObjectMethod(BaseVM vm, DvmClass dvmClass, String signature, VarArg varArg) {
        switch (signature) {
            case "com/alibaba/wireless/security/mainplugin/SecurityGuardMainPlugin->getMainPluginClassLoader()Ljava/lang/ClassLoader;":
                return vm.resolveClass("java/lang/ClassLoader").newObject(null);
            case "com/taobao/wireless/security/adapter/common/SPUtility2->readFromSPUnified(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;":
                StringObject a1 = varArg.getObject(0);
                StringObject a2 = varArg.getObject(1);
                StringObject a3 = varArg.getObject(2);
                System.out.println("readFromSPUnified a1=" + a1 + ", a2=" + a2 + ", a3=" + a3);
                return null;
            case "com/taobao/wireless/security/adapter/datacollection/DeviceInfoCapturer->doCommandForString(I)Ljava/lang/String;":
                int value = varArg.getInt(0);
                System.out.println("com/taobao/wireless/security/adapter/datacollection/DeviceInfoCapturer->doCommandForString value=" + value);
                return null;
        }

        return super.callStaticObjectMethod(vm, dvmClass, signature, varArg);
    }

    @Override
    public DvmObject newObject(BaseVM vm, DvmClass dvmClass, String signature, VarArg varArg) {
        switch (signature) {
            case "com/alibaba/wireless/security/open/SecException-><init>(Ljava/lang/String;I)V": {
                StringObject msg = varArg.getObject(0);
                int value = varArg.getInt(1);
                return dvmClass.newObject(msg.getValue() + "[" + value + "]");
            }
            case "java/lang/Integer-><init>(I)V":
                int value = varArg.getInt(0);
                return DvmInteger.valueOf(vm, value);
        }

        return super.newObject(vm, dvmClass, signature, varArg);
    }

    @Override
    public DvmObject callObjectMethod(BaseVM vm, DvmObject dvmObject, String signature, VarArg varArg) {
        switch (signature) {
            case "java/util/HashMap->keySet()Ljava/util/Set;": {
                HashMap map = (HashMap) dvmObject.getValue();
                return vm.resolveClass("java/util/Set").newObject(map.keySet());
            }
            case "java/util/Set->toArray()[Ljava/lang/Object;":
                Set set = (Set) dvmObject.getValue();
                Object[] array = set.toArray();
                DvmObject[] objects = new DvmObject[array.length];
                for (int i = 0; i < array.length; i++) {
                    if (array[i] instanceof String) {
                        objects[i] = new StringObject(vm, (String) array[i]);
                    } else {
                        throw new IllegalStateException("array=" + array[i]);
                    }
                }
                return new ArrayObject(objects);
            case "java/util/HashMap->get(Ljava/lang/Object;)Ljava/lang/Object;": {
                HashMap map = (HashMap) dvmObject.getValue();
                Object key = varArg.getObject(0).getValue();
                Object obj = map.get(key);
                if (obj instanceof String) {
                    return new StringObject(vm, (String) obj);
                } else {
                    throw new IllegalStateException("array=" + obj);
                }
            }
            case "android/content/Context->getPackageCodePath()Ljava/lang/String;":
                return new StringObject(vm, APK_INSTALL_PATH);
            case "android/content/Context->getFilesDir()Ljava/io/File;":
                return vm.resolveClass("java/io/File").newObject(new File("target"));
            case "java/io/File->getAbsolutePath()Ljava/lang/String;":
                File file = (File) dvmObject.getValue();
                return new StringObject(vm, file.getAbsolutePath());
        }

        return super.callObjectMethod(vm, dvmObject, signature, varArg);
    }

    @Override
    public void callStaticVoidMethod(BaseVM vm, DvmClass dvmClass, String signature, VarArg varArg) {
        switch (signature) {
            case "com/taobao/dp/util/CallbackHelper->onCallBack(ILjava/lang/String;I)V":
                int i1 = varArg.getInt(0);
                StringObject str = varArg.getObject(1);
                int i2 = varArg.getInt(2);
                System.out.println("com/taobao/dp/util/CallbackHelper->onCallBack i1=" + i1 + ", str=" + str + ", i2=" + i2);
                return;
            case "com/alibaba/wireless/security/open/edgecomputing/ECMiscInfo->registerAppLifeCyCleCallBack()V":
                System.out.println("registerAppLifeCyCleCallBack");
                return;
        }

        super.callStaticVoidMethod(vm, dvmClass, signature, varArg);
    }

    @Override
    public DvmObject getObjectField(BaseVM vm, DvmObject dvmObject, String signature) {
        switch (signature) {
            case "android/content/pm/ApplicationInfo->nativeLibraryDir:Ljava/lang/String;":
                return new StringObject(vm, new File("target").getAbsolutePath());
        }

        return super.getObjectField(vm, dvmObject, signature);
    }

    @Override
    public int callStaticIntMethod(BaseVM vm, DvmClass dvmClass, String signature, VarArg varArg) {
        switch (signature) {
            case "com/alibaba/wireless/security/framework/utils/UserTrackMethodJniBridge->utAvaiable()I":
                return 1;
            case "com/taobao/wireless/security/adapter/common/SPUtility2->saveToFileUnifiedForNative(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I":
                StringObject a1 = varArg.getObject(0);
                StringObject a2 = varArg.getObject(1);
                StringObject a3 = varArg.getObject(2);
                boolean b4 = varArg.getInt(3) != 0;
                System.out.println("saveToFileUnifiedForNative a1=" + a1 + ", a2=" + a2 + ", a3=" + a3 + ", b4=" + b4);
                return 0;
        }

        return super.callStaticIntMethod(vm, dvmClass, signature, varArg);
    }
}

运行后是null

**Comment by jtduan** [comment]
测试app地址: https://www.wandoujia.com/apps/32267/history_v243

**Comment by zhkl0228** [comment]
建议使用旧版，新版还在不断完善中

**Comment by xiamulo** [comment]
@jtduan 能发一份去年6月份的版本给我吗，我也遇到和你一样的问题

**Comment by feng504x** [comment]
请问怎么使用旧版???

**Comment by jtduan** [comment]
> 请问怎么使用旧版???

最新版已经支持sgmain系列调用了，旧版的话，可以把git代码库切换到19年的版本直接运行就可以

**Comment by fanfan493** [comment]
> > 请问怎么使用旧版???
> 
> 最新版已经支持sgmain系列调用了，旧版的话，可以把git代码库切换到19年的版本直接运行就可以

兄弟 给个 联系方式   有偿咨询

**Comment by HandsomeXi** [comment]
用的64位还是32位？

**Comment by HandsomeXi** [comment]
java.lang.IllegalStateException: createNewFile failed: target\rootfs\default\D:\workspace\unidbgTest\target\ab914f43b8296c2c.lock
	at com.github.unidbg.file.BaseFileSystem.createFileIO(BaseFileSystem.java:95)
	at com.github.unidbg.file.BaseFileSystem.open(BaseFileSystem.java:58)
	at com.github.unidbg.file.linux.LinuxFileSystem.open(LinuxFileSystem.java:30)
	at com.github.unidbg.unix.UnixSyscallHandler.resolve(UnixSyscallHandler.java:103)
	at com.github.unidbg.unix.UnixSyscallHandler.open(UnixSyscallHandler.java:273)
	at com.github.unidbg.linux.ARM32SyscallHandler.open(ARM32SyscallHandler.java:1902)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:134)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:376)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:465)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:208)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:115)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:223)
	at OtherTaobaoSo.test(OtherTaobaoSo.java:95)
	at OtherTaobaoSo.main(OtherTaobaoSo.java:88)

楼主遇到过这种问题吗？这个创建的文件路径很奇怪

**Comment by SeriousSnow** [comment]
> java.lang.IllegalStateException: createNewFile failed: target\rootfs\default\D:\workspace\unidbgTest\target\ab914f43b8296c2c.lock
> at com.github.unidbg.file.BaseFileSystem.createFileIO(BaseFileSystem.java:95)
> at com.github.unidbg.file.BaseFileSystem.open(BaseFileSystem.java:58)
> at com.github.unidbg.file.linux.LinuxFileSystem.open(LinuxFileSystem.java:30)
> at com.github.unidbg.unix.UnixSyscallHandler.resolve(UnixSyscallHandler.java:103)
> at com.github.unidbg.unix.UnixSyscallHandler.open(UnixSyscallHandler.java:273)
> at com.github.unidbg.linux.ARM32SyscallHandler.open(ARM32SyscallHandler.java:1902)
> at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:134)
> at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
> at unicorn.Unicorn.emu_start(Native Method)
> at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:376)
> at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:465)
> at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:208)
> at com.github.unidbg.Module.emulateFunction(Module.java:154)
> at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:115)
> at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:223)
> at OtherTaobaoSo.test(OtherTaobaoSo.java:95)
> at OtherTaobaoSo.main(OtherTaobaoSo.java:88)
> 
> 楼主遇到过这种问题吗？这个创建的文件路径很奇怪


这个方法里面
@Override
    public FileResult resolve(Emulator emulator, String pathname, int oflags) {

添加一个
        if (pathname.endsWith("ab914f43b8296c2c.lock")){
            return FileResult.success(new ByteArrayFileIO(oflags, pathname,"".getBytes()));
        }

**Comment by ChongTianhe** [comment]
> > 请问怎么使用旧版???
> 
> 最新版已经支持sgmain系列调用了，旧版的话，可以把git代码库切换到19年的版本直接运行就可以

请问你的可以了吗 我新版的也不行啊

**Comment by yangxiaopao** [comment]
@jtduan 用了你pull request合并后的版本，但是跑起来也遇到了createNewFile 错误，怎么处理的呢

**Comment by xuejiandong** [comment]
> @jtduan 用了你pull request合并后的版本，但是跑起来也遇到了createNewFile 错误，怎么处理的呢

一样的
