### ISSUE TITLE
请教时区设置方法

### ISSUE THREAD

**Issue by gofmt** [zhkl0228/unidbg#158]
__bionic_open_tzdata_path: could not read index of "/system//usr/share/zoneinfo/tzdata": short read

Android平台,当需要读取时区设置时,出现这个错误,请教如何设置时区?

**Comment by wiwii** [comment]
到rootfs对应的目录，放置arm的时区文件

**Comment by gofmt** [comment]
> 到rootfs对应的目录，放置arm的时区文件

请详细举例说明一下,谢谢!

**Comment by justcodedroid** [comment]
> __bionic_open_tzdata_path: could not read index of "/system//usr/share/zoneinfo/tzdata": short read
> 
> Android平台,当需要读取时区设置时,出现这个错误,请教如何设置时区?

看到您关闭了issue，请问您找到解决问题的方案了么？
