### ISSUE TITLE
Build jar

### ISSUE THREAD

**Issue by kshport** [zhkl0228/unidbg#160]
Guys, need help! 
How to build output jar file with com.bytedance.frameworks.core.encrypt.TTEncrypt main class? 
I'm adding MANIFEST.MF to /unidbg-android/src/main/java/META-INF/MANIFEST.MF with:

>Manifest-Version: 1.0. 
Main-Class: com.bytedance.frameworks.core.encrypt.TTEncrypt

But when i try execute jar, i'v got:
> java -jar unidbg-android.jar. 
no main manifest attribute, in unidbg-android.jar

I'm using IntellyJ Ultimate

**Comment by TianLing2020** [comment]
May be you need help .
You can contacts my email:
kailexin@gmail.com
