### ISSUE TITLE
jni的一部分方法可以调用，一部分调用失败一般是什么原因？

### ISSUE THREAD

**Issue by xiada** [zhkl0228/unidbg#18]
```

public class AwemeEncryptTest extends AbstractJni implements IOResolver {

    private static LibraryResolver createLibraryResolver() {
        return new AndroidResolver(23);
    }

    private static ARMEmulator createARMEmulator() {
        return new AndroidARMEmulator("com.ss.android");
    }

    private final ARMEmulator emulator;
    private final VM vm;
    private final Module module;

    private final DvmClass UserInfo;

    private AwemeEncryptTest() throws IOException {
        emulator = createARMEmulator();
        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(createLibraryResolver());
        memory.setCallInitFunction();

        vm = emulator.createDalvikVM(null);
        DalvikModule dm = vm.loadLibrary(new File("src/test/resources/example_binaries/libcms.so"), false);
        vm.setJni(this);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();

        UserInfo = vm.resolveClass("com/ss/android/common/applog/UserInfo");
    }
    private void destroy() throws IOException {
        emulator.close();
        System.out.println("module=" + module);
        System.out.println("== destroy ===");
    }
    public static void main(String[] args) throws Exception {
        AwemeEncryptTest test = new AwemeEncryptTest();
        test.sign();
        test.destroy();
    }

    private void sign() {
        int appId = 1128;
        UserInfo.callStaticJniMethod(emulator, "setAppId(I)V", appId);
        long hash;
        StringObject obj ;
        Number ret;
        String key = "a3668f0afac72ca3f6c1697d29e0e1bb1fef4ab0285319b95ac39fa42c38d05f";
        UserInfo.callStaticJniMethod(emulator, "initUser(Ljava/lang/String;)I", new StringObject(vm, key));
//        System.out.println(obj.getValue());

        ret = UserInfo.callStaticJniMethod(emulator, "getS()Ljava/lang/String;");
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        System.out.println(obj.getValue());

        UserInfo.callStaticJniMethod(emulator, "getType()I");


        int timeStamp = 1559629512;
        String deviceId = "53039791462";
        String url = "https://aweme-eagle.snssdk.com/aweme/v1/feed/?os_api=26&device_type=MHA-AL00&ssmix=a&manifest_version_code=380&dpi=480&uuid=865296034887289&js_sdk_version=1.5.4&need_relieve_aweme=0&min_cursor=0&req_from=&count=6&app_name=aweme&max_cursor=0&version_name=3.8.0&pull_type=1&ac=wifi&app_type=normal&update_version_code=3802&channel=update&type=0&_rticket=1545468521415&is_cold_start=0&device_platform=android&iid=54915619827&volume=0.0&longitude=120.388862&version_code=380&openudid=3a6f6cdf79dc8965&device_id=53039791462&latitude=36.090072&resolution=1080*1808&device_brand=HUAWEI&language=zh&os_version=8.0.0&filter_warn=0&aid=1128&mcc_mnc=46000&ts=1559629512";
        ret = UserInfo.callStaticJniMethod(emulator, "getUserInfo(ILjava/lang/String;[Ljava/lang/String;)Ljava/lang/String;",
                timeStamp,new StringObject(vm,url),null,new StringObject(vm,deviceId));
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        vm.deleteLocalRefs();
//        System.out.println(obj.getValue());
        Number[] numbers = module.callFunction(emulator, 0x19c5d,vm.getJNIEnv(),0x363E7561,timeStamp,url,null,deviceId);
        Unicorn unicorn = emulator.getUnicorn();
        long address = numbers[0].intValue() & 0xffffffffL;
        System.out.println("eFunc length is: " + numbers[0].intValue());
        System.out.println("ret=" + ARM.readCString(unicorn, address));
    }


    @Override
    public FileIO resolve(File workDir, String pathname, int oflags) {
        if (("proc/" + emulator.getPid() + "/status").equals(pathname)) {
            return new ByteArrayFileIO(oflags, pathname, "TracerPid:\t0\n".getBytes());
        }
        return null;
    }
}
```

这个是so文件
[libcms.zip](https://github.com/zhkl0228/unidbg/files/3251094/libcms.zip)

getS 和 getType能得到返回值
其他就是NullPointerException

**Comment by xiada** [comment]
getS 和 getType能得到返回值
其他就是NullPointerException

**Comment by zhkl0228** [comment]
试下

`public class AwemeEncryptTest extends AbstractJni implements IOResolver {

    private static LibraryResolver createLibraryResolver() {
        return new AndroidResolver(19);
    }

    private static ARMEmulator createARMEmulator() {
        return new AndroidARMEmulator("com.ss.android");
    }

    private final ARMEmulator emulator;
    private final VM vm;
    private final Module module;

    private final DvmClass UserInfo;

    private AwemeEncryptTest() throws IOException {
        emulator = createARMEmulator();
        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(createLibraryResolver());
        memory.setCallInitFunction();

        vm = emulator.createDalvikVM(null);
        DalvikModule dm = vm.loadLibrary(new File("src/test/resources/example_binaries/libcms.so"), false);
        vm.setJni(this);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();

        UserInfo = vm.resolveClass("com/ss/android/common/applog/UserInfo");
    }
    private void destroy() throws IOException {
        emulator.close();
        System.out.println("module=" + module);
        System.out.println("== destroy ===");
    }
    public static void main(String[] args) throws Exception {
        AwemeEncryptTest test = new AwemeEncryptTest();
        test.sign();
        test.destroy();
    }

    private void sign() {
        int appId = 1128;
        UserInfo.callStaticJniMethod(emulator, "setAppId(I)V", appId);
        long hash;
        StringObject obj ;
        Number ret;
        String key = "a3668f0afac72ca3f6c1697d29e0e1bb1fef4ab0285319b95ac39fa42c38d05f";
        UserInfo.callStaticJniMethod(emulator, "initUser(Ljava/lang/String;)I", vm.addLocalObject(new StringObject(vm, key)));
//        System.out.println(obj.getValue());

        ret = UserInfo.callStaticJniMethod(emulator, "getS()Ljava/lang/String;");
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        System.out.println("getS=" + obj.getValue());

        UserInfo.callStaticJniMethod(emulator, "getType()I");


        int timeStamp = 1559629512;
        String deviceId = "53039791462";
        String url = "https://aweme-eagle.snssdk.com/aweme/v1/feed/?os_api=26&device_type=MHA-AL00&ssmix=a&manifest_version_code=380&dpi=480&uuid=865296034887289&js_sdk_version=1.5.4&need_relieve_aweme=0&min_cursor=0&req_from=&count=6&app_name=aweme&max_cursor=0&version_name=3.8.0&pull_type=1&ac=wifi&app_type=normal&update_version_code=3802&channel=update&type=0&_rticket=1545468521415&is_cold_start=0&device_platform=android&iid=54915619827&volume=0.0&longitude=120.388862&version_code=380&openudid=3a6f6cdf79dc8965&device_id=53039791462&latitude=36.090072&resolution=1080*1808&device_brand=HUAWEI&language=zh&os_version=8.0.0&filter_warn=0&aid=1128&mcc_mnc=46000&ts=1559629512";
        ret = UserInfo.callStaticJniMethod(emulator, "getUserInfo(ILjava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
                timeStamp,vm.addLocalObject(new StringObject(vm,url)),null,vm.addLocalObject(new StringObject(vm,deviceId)));
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        vm.deleteLocalRefs();
        System.out.println("getUserInfo=" + obj.getValue());
    }


    @Override
    public FileIO resolve(File workDir, String pathname, int oflags) {
        if (("proc/" + emulator.getPid() + "/status").equals(pathname)) {
            return new ByteArrayFileIO(oflags, pathname, "TracerPid:\t0\n".getBytes());
        }
        return null;
    }
}
`

**Comment by xiada** [comment]
的确可以了，我忘了vm.addLocalObject。。还有那个getUserInfo应该调用第二个重载方法

**Comment by hellodword** [comment]
> 的确可以了，我忘了vm.addLocalObject。。还有那个getUserInfo应该调用第二个重载方法

```java
    private void getUserInfo() throws IOException {

        long hash;
        StringObject obj;
        Number ret;


        int ts = 1559491087;
        String url = "http://dm.toutiao.com/ies/network/aweme/?retry_type=no_retry&iid=76783365765&device_id=67083372561&ac=wifi&channel=aweGW&aid=1128&app_name=aweme&version_code=620&version_name=6.2.0&device_platform=android&ssmix=a&device_type=Nexus 5&device_brand=google&language=zh&os_api=23&os_version=6.0.1&openudid=9076ff2f076be785&manifest_version_code=620&resolution=1080*1776&dpi=480&update_version_code=6202&_rticket=1559491087326&ts=1559491087&js_sdk_version=1.16.2.7";
        String[] kv = {"os_api", "23", "device_type", "Nexus 5", "device_platform", "android", "ssmix", "a", "iid", "76783365765", "manifest_version_code", "620", "dpi", "480", "version_code", "620", "app_name", "aweme", "version_name", "6.2.0", "openudid", "9076ff2f076be785", "device_id", "67083372561", "resolution", "1080*1776", "os_version", "6.0.1", "language", "zh", "device_brand", "google", "ac", "wifi", "update_version_code", "6202", "aid", "1128", "channel", "aweGW"};
        String deviceid = "67083372561";

        System.out.println(kv.length);

        DvmObject[] kvObj = new DvmObject[kv.length];
        for (int i = 0; i < kv.length; i++) {
            kvObj[i] = new StringObject(vm, kv[i]);
            vm.addLocalObject(kvObj[i]); //
            
        }

        ret = UserInfo.callStaticJniMethod(emulator, "getUserInfo(ILjava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
                ts,
                vm.addLocalObject(new StringObject(vm, url)),
                vm.addLocalObject(new ArrayObject(kvObj)),
                vm.addLocalObject(new StringObject(vm, deviceid))
        );

        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        vm.deleteLocalRefs();
        System.out.println("getUserInfo=" + obj.getValue());

    }
```

我也试着调用这个, 请问 String 数组的参数怎么处理的呢?

**Comment by zhkl0228** [comment]
> > 的确可以了，我忘了vm.addLocalObject。。还有那个getUserInfo应该调用第二个重载方法
> 
> ```java
>     private void getUserInfo() throws IOException {
> 
>         long hash;
>         StringObject obj;
>         Number ret;
> 
> 
>         int ts = 1559491087;
>         String url = "http://dm.toutiao.com/ies/network/aweme/?retry_type=no_retry&iid=76783365765&device_id=67083372561&ac=wifi&channel=aweGW&aid=1128&app_name=aweme&version_code=620&version_name=6.2.0&device_platform=android&ssmix=a&device_type=Nexus 5&device_brand=google&language=zh&os_api=23&os_version=6.0.1&openudid=9076ff2f076be785&manifest_version_code=620&resolution=1080*1776&dpi=480&update_version_code=6202&_rticket=1559491087326&ts=1559491087&js_sdk_version=1.16.2.7";
>         String[] kv = {"os_api", "23", "device_type", "Nexus 5", "device_platform", "android", "ssmix", "a", "iid", "76783365765", "manifest_version_code", "620", "dpi", "480", "version_code", "620", "app_name", "aweme", "version_name", "6.2.0", "openudid", "9076ff2f076be785", "device_id", "67083372561", "resolution", "1080*1776", "os_version", "6.0.1", "language", "zh", "device_brand", "google", "ac", "wifi", "update_version_code", "6202", "aid", "1128", "channel", "aweGW"};
>         String deviceid = "67083372561";
> 
>         System.out.println(kv.length);
> 
>         DvmObject[] kvObj = new DvmObject[kv.length];
>         for (int i = 0; i < kv.length; i++) {
>             kvObj[i] = new StringObject(vm, kv[i]);
>             vm.addLocalObject(kvObj[i]); //
>             
>         }
> 
>         ret = UserInfo.callStaticJniMethod(emulator, "getUserInfo(ILjava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
>                 ts,
>                 vm.addLocalObject(new StringObject(vm, url)),
>                 vm.addLocalObject(new ArrayObject(kvObj)),
>                 vm.addLocalObject(new StringObject(vm, deviceid))
>         );
> 
>         hash = ret.intValue() & 0xffffffffL;
>         obj = vm.getObject(hash);
>         vm.deleteLocalRefs();
>         System.out.println("getUserInfo=" + obj.getValue());
> 
>     }
> ```
> 
> 我也试着调用这个, 请问 String 数组的参数怎么处理的呢? 我这样调用也是抛 `NullPointerException`

你这个调用没问题，使用最新版试下

**Comment by hellodword** [comment]
> 你这个调用没问题，使用最新版试下

确实，我的失误，感谢

**Comment by xiada** [comment]
```

    private AwemeEncryptTest() throws IOException {
        emulator = createARMEmulator();
        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(createLibraryResolver());
        memory.setCallInitFunction();

//        vm = emulator.createDalvikVM(null);
//        DalvikModule dm = vm.loadLibrary(new File("src/test/resources/example_binaries/libcms.so"), false);

        vm = emulator.createDalvikVM(new File("src/test/resources/app/douyin_test.apk"));
        DalvikModule dm = vm.loadLibrary("cms", false);

        vm.setJni(this);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();


    }

    private void destroy() throws IOException {
        emulator.close();
        System.out.println("module=" + module);
        System.out.println("== destroy ===");
    }

    public static void main(String[] args) throws Exception {
        AwemeEncryptTest test = new AwemeEncryptTest();
        test.sign();
        test.destroy();
    }

    private void sign() {
        DvmClass UserInfo = vm.resolveClass("com/ss/android/common/applog/UserInfo");
        DvmClass Ces_a = vm.resolveClass("com/ss/sys/ces/a");
        int appId = 1128;
        UserInfo.callStaticJniMethod(emulator, "setAppId(I)V", appId);
        long hash;
        StringObject obj;
        Number ret;
        String key = "a3668f0afac72ca3f6c1697d29e0e1bb1fef4ab0285319b95ac39fa42c38d05f";
        UserInfo.callStaticJniMethod(emulator, "initUser(Ljava/lang/String;)I", vm.addLocalObject(new StringObject(vm, key)));

        ret = UserInfo.callStaticJniMethod(emulator, "getS()Ljava/lang/String;");
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        System.out.println("getS=" + obj.getValue());

        UserInfo.callStaticJniMethod(emulator, "getType()I");


        int timeStamp = 1559629512;
        String deviceId = "53039791462";
        String url = "https://aweme-eagle.snssdk.com/aweme/v1/feed/?os_api=26&device_type=MHA-AL00&ssmix=a&manifest_version_code=380&dpi=480&uuid=865296034887289&js_sdk_version=1.5.4&need_relieve_aweme=0&min_cursor=0&req_from=&count=6&app_name=aweme&max_cursor=0&version_name=3.8.0&pull_type=1&ac=wifi&app_type=normal&update_version_code=3802&channel=update&type=0&_rticket=1545468521415&is_cold_start=0&device_platform=android&iid=54915619827&volume=0.0&longitude=120.388862&version_code=380&openudid=3a6f6cdf79dc8965&device_id=53039791462&latitude=36.090072&resolution=1080*1808&device_brand=HUAWEI&language=zh&os_version=8.0.0&filter_warn=0&aid=1128&mcc_mnc=46000&ts=1559629512";
        ret = UserInfo.callStaticJniMethod(emulator, "getUserInfo(ILjava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
                timeStamp, vm.addLocalObject(new StringObject(vm, url)), null, vm.addLocalObject(new StringObject(vm, deviceId)));
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        vm.deleteLocalRefs();
        System.out.println("getUserInfo=" + obj.getValue());


        String as = obj.getValue().substring(0, obj.getValue().length() >> 1);
        String cp = obj.getValue().substring(obj.getValue().length() >> 1);
        byte[] masBytes = as.getBytes();
        ByteArray byteArray = new ByteArray(masBytes);
        ret = Ces_a.callStaticJniMethod(emulator, "e([B)[B", vm.addLocalObject(byteArray));
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        vm.deleteLocalRefs();
        System.out.println("a.e =" + obj.getValue());
    }

    @Override
    public FileIO resolve(File workDir, String pathname, int oflags) {
        if (("proc/" + emulator.getPid() + "/status").equals(pathname)) {
            return new ByteArrayFileIO(oflags, pathname, "TracerPid:\t0\n".getBytes());
        }
        return null;
    }

    @Override
    public DvmObject callObjectMethodV(BaseVM vm, DvmObject dvmObject, String signature, VaList vaList) {
//        System.out.println(signature);
        switch (signature) {
            case "android/app/Application->getPackageManager()Landroid/content/pm/PackageManager;":
                return new DvmObject<Object>(vm.resolveClass("android/content/pm/PackageManager"), null);
            case "android/app/Application->getPackageName()Ljava/lang/String;":
                return new StringObject(vm, vm.getPackageName());
            case "android/content/pm/PackageManager->getPackageInfo(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;":
                StringObject packageName = vaList.getObject(0);
                int flag = vaList.getInt(4);
                System.out.println("getPackageInfo packageName=" + packageName.getValue() + ", flag=" + flag);
                return new DvmObject<>(vm.resolveClass("android/content/pm/PackageInfo"), packageName.getValue());
            case "android/content/pm/Signature->toByteArray()[B":
                DvmObject<Object> dvmSignature = new DvmObject<>(vm.resolveClass("android/content/pm/Signature"), null);
                return new ArrayObject(dvmSignature);            

        }
        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }

    @Override
    public DvmObject getObjectField(BaseVM vm, DvmObject dvmObject, String signature) {
        switch (signature) {
            case "android/content/pm/PackageInfo->signatures:[Landroid/content/pm/Signature;":
                DvmObject<Object> dvmSignature = new DvmObject<>(vm.resolveClass("android/content/pm/Signature"), null);
                return new ArrayObject(dvmSignature);
        }
        return super.getObjectField(vm, dvmObject, signature);
    }


```
请问一下`java.lang.AbstractMethodError: java/io/ByteArrayInputStream-><init>([B)V` 这个报错怎么解决啊？

**Comment by zhkl0228** [comment]
```
    @Override
    public DvmObject newObjectV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        switch (signature) {
            case "java/io/ByteArrayInputStream-><init>([B)V":
                ByteArray array = vaList.getObject(0);
                return vm.resolveClass("java/io/ByteArrayInputStream").newObject(new ByteArrayInputStream(array.getValue()));
        }

        return super.newObjectV(vm, dvmClass, signature, vaList);
    }
```

**Comment by xiada** [comment]
加上这个会报这个错 `java.lang.ClassCastException: cn.banny.unidbg.linux.android.dvm.ArrayObject cannot be cast to cn.banny.unidbg.linux.android.dvm.ByteArray
`

**Comment by zhkl0228** [comment]
case "android/content/pm/Signature->toByteArray()[B":
                DvmObject<Object> dvmSignature = new DvmObject<>(vm.resolveClass("android/content/pm/Signature"), null);
                return new ArrayObject(dvmSignature);            
这行错了

**Comment by zhkl0228** [comment]
如果用apk文件加载so的话，会自动处理签名方面的jni，具体可看AbstractJni

**Comment by xiada** [comment]
我的确是改成apk加载so了，不过还是有问题

**Comment by xiada** [comment]
`java.lang.ClassCastException: cn.banny.unidbg.linux.android.dvm.DvmObject cannot be cast to cn.banny.unidbg.linux.android.dvm.Array`
这个报错是怎么回事？

**Comment by zhkl0228** [comment]
传参或者模拟ini有问题

**Comment by xiada** [comment]
还是这个so和apk，调用的是
```
DvmClass Ces_a = vm.resolveClass("com/ss/sys/ces/a");
byte[] masBytes = "".getBytes();
        ByteArray byteArray = new ByteArray(masBytes);
        ret = Ces_a.callStaticJniMethod(emulator, "e([B)[B", vm.addLocalObject(byteArray));
```
传参和jni应该没啥问题。smali里的代码是"e([B)[B"

**Comment by zhkl0228** [comment]
还有可能是模拟jni调用的返回有问题

**Comment by xiada** [comment]
这个有debug的方法吗？

**Comment by qiang** [comment]
@zhkl0228 @xiada 我有个疑问啊，这个地方的包名为啥是 com.ss.android 而不是 com.ss.android.ugc.aweme ？

**Comment by 157charles** [comment]
@zhkl0228  我的也是jni的部分方法调用失败,请大神看看。
public class EncryptionJni extends AbstractJni implements IOResolver {
    private static final String APP_PACKAGE_NAME = "com.sankuai.meituan.takeoutnew";

    private static LibraryResolver createLibraryResolver() {
        return new AndroidResolver(19);
    }

    private static ARMEmulator createARMEmulator() {
        return new AndroidARMEmulator(APP_PACKAGE_NAME);
    }

    private final ARMEmulator emulator;
    private final VM vm;

    private final DvmClass clazz;

    private static final String INSTALL_PATH = "/data/app/com.sankuai.meituan.takeoutnew-1.apk";
    private static final String APK_PATH = "src/main/resources/app/7.8.4.70804.apk";

    private final Module module;

    public EncryptionJni() throws IOException {
        emulator = createARMEmulator();
        emulator.getSyscallHandler().addIOResolver(this);
        System.out.println("== init ===");

        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(createLibraryResolver());
        memory.setCallInitFunction();

        vm = emulator.createDalvikVM(new File(APK_PATH));
        DalvikModule dm = vm.loadLibrary("mtguard", false);
        Logger.getLogger("cn.banny.unidbg.AbstractEmulator").setLevel(Level.ERROR);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();

        clazz = vm.resolveClass("com.meituan.android.common.encryption.EncryptionJni".replace(".", "/"));

        memory.runLastThread(TimeUnit.SECONDS.toMicros(10));
    }

    private void destroy() throws IOException {
        emulator.close();
        System.out.println("module=" + module);
        System.out.println("== destroy ===");
    }

    public static void main(String[] args) throws Exception {
        EncryptionJni encryptionJni = new EncryptionJni();
        String readString = "FHVl2ldQ8PhMY5elqWg+4Z/T8e1mq7zSaLP0sIJIieUfTAkx+0MktwQrw4/g1Tslxi+XgmK8lP7x" +
                "PF9d8EVHfIHkmoQZDpA2msU5YW49HHppoyj8BocOqxmCGcIKEYgBv+GEWiRVpc8cbwPyNoRvog==";
        byte[] decryptAES = encryptionJni.encyptDataAES2(java.util.Base64.getDecoder().decode(readString), "aesKey".getBytes(), 0);
        System.out.println(new String(decryptAES, Charset.forName("UTF-8")));
    }

    public byte[] encyptDataAES2(byte[] bArr, byte[] bArr2, int i) {


        DvmObject context = vm.resolveClass("android/content/Context").newObject(null);
        long start = System.currentTimeMillis();
        Number ret = clazz.callStaticJniMethod(emulator, "encyptDataAES2(Ljava/lang/Object;[B[BI)[B",
                context,
                vm.addLocalObject(new ByteArray(bArr)),
                vm.addLocalObject(new ByteArray(bArr2)),
                i
        );
        long hash = ret.intValue() & 0xffffffffL;
        ByteArray obj = vm.getObject(hash);
        vm.deleteLocalRefs();
        Inspector.inspect(Base64.decodeBase64(obj.getValue()), "encyptDataAES2 = " + new String(obj.getValue()) + ", offset=" + (System.currentTimeMillis() - start) + "ms");

        try {
            destroy();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return obj.getValue();
    }

    @Override
    public FileIO resolve(File workDir, String pathname, int oflags) {
        if ("/proc/self/cmdline".equals(pathname)) {
            return new ByteArrayFileIO(oflags, pathname, APP_PACKAGE_NAME.getBytes());
        }
        if (INSTALL_PATH.equals(pathname)) {
            return new SimpleFileIO(oflags, new File(APK_PATH), pathname);
        }
        if ("/data/misc/zoneinfo/tzdata".equals(pathname)) {
            return new SimpleFileIO(oflags, new File("src/main/resources/android/sdk19/system/usr/share/zoneinfo/tzdata"), pathname);
        }
        return null;
    }
    @Override
    public DvmObject callObjectMethod(BaseVM vm, DvmObject dvmObject, String signature, VarArg varArg) {
        if ("android/content/Context->getPackageCodePath()Ljava/lang/String;".equals(signature)) {
            return new StringObject(vm, INSTALL_PATH);
        }

        return super.callObjectMethod(vm, dvmObject, signature, varArg);
    }

出现Exception in thread "main" java.lang.NullPointerException
	at com.meituan.android.common.encryption.EncryptionJni.encyptDataAES2(EncryptionJni.java:98)
	at com.meituan.android.common.encryption.EncryptionJni.main(EncryptionJni.java:80)
