### ISSUE TITLE
libsgmainso-6.4.163.so 0.9.0 

### ISSUE THREAD

**Issue by serious-snow** [zhkl0228/unidbg#205]
StringObject ret2 = Native.callStaticJniMethodObject(emulator, "doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object;",
                10401,arrayObject
                );
一直返回null

**Comment by ChongTianhe** [comment]
问题解决了吗

**Comment by SeriousSnow** [comment]
> 问题解决了吗

老哥，没有解决，最后没有用unidbg 了，用的xposed+AsyncHttpServer 勉强用着了
