### ISSUE TITLE
GetStringUTFChars获得的char* 无法用free释放, Invalid address xxxx passed to free: value not allocated

### ISSUE THREAD

**Issue by kylin1020** [zhkl0228/unidbg#210]
![image](https://user-images.githubusercontent.com/37458538/100591726-1c87ad80-3331-11eb-90c0-3e9bef090bcb.png)
这里会出错

代码: 
`        DalvikModule dm = vm.loadLibrary("d-lib", false);
        DvmClass ad = vm.resolveClass("a/d");
        Module module = dm.getModule();
        dm.callJNI_OnLoad(emulator);

        String methodSign = "c(Ljava/lang/String)[B";
        DvmObject<?> ret = ad.callStaticJniMethodObject(emulator, methodSign, "123");
        System.out.println(ret);`
日志: 
Find native function Java_a_d_c(Ljava/lang/String)[B => RX@0x4000127d[libd-lib.so]0x127d
JNIEnv->GetStringUtfChars("123") was called from RX@0x400012a3[libd-lib.so]0x12a3
ox137d was finished, result is 1077219392
JNIEnv->NewByteArray(8) was called from RX@0x400012b9[libd-lib.so]0x12b9
JNIEnv->SetByteArrayRegion([B@2cbb3d47, 0, 8, RW@0x40351040) was called from RX@0x400012cf[libd-lib.so]0x12cf
Invalid address 0x402c3000 passed to free: value not allocated
[crash]A/libc: Invalid address 0x402c3000 passed to free: value not allocated
exit with code: 1

**Comment by kylin1020** [comment]
APK: 
链接：https://pan.baidu.com/s/12U49DbsFy-g-zBae4b2etQ 
提取码：x1za 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by google-mirror** [comment]
本来就不能free, 这个绕过JNI接口的三流app模拟它干啥

**Comment by kylin1020** [comment]
按理说确实, 但是我碰到几个应用都是这么操作, 没法子.

**Comment by google-mirror** [comment]
那你就自己把free拦截掉
