### ISSUE TITLE
当包名中带下滑线时，findNativeFunction函数无法生成正确的symolName导致匹配不上so中函数

### ISSUE THREAD

**Issue by leeblackc** [zhkl0228/unidbg#219]
在测试过程中发现，当包名中含有下划线的时候，生成的so中函数下划线"_"会被替换成"_1"，而本项目的DvmClass中的findNativeFunction方法，没有进行相应的处理，会导致没有生成正确的symbolName，无法与so中函数匹配，从而抛出find method failed 异常
![image](https://user-images.githubusercontent.com/21374847/103340273-9ccf3900-4abe-11eb-8d0d-da0268398b14.png)

**Comment by zhkl0228** [comment]
最新版修复
