### ISSUE TITLE
如何释放函数内部分配的内存？

### ISSUE THREAD

**Issue by RainbowXie** [zhkl0228/unidbg#227]
一个函数在函数内部分配的内存，我调用这个函数后，如何释放他分配的内存？
```
char* foo()
{ 
    ...
    char* p = malloc(0x100)
    ...
    return p;
}
```

**Comment by zhkl0228** [comment]
主动调用libc的free方法

**Comment by RainbowXie** [comment]
memory.munmap(pointer.peer, (int)pointer.getSize());

**Comment by RainbowXie** [comment]
> 主动调用libc的free方法

这样可以吗

`memory.munmap(pointer.peer, (int)pointer.getSize());`

**Comment by zhkl0228** [comment]
不行

**Comment by zhkl0228** [comment]
free = module.findSymbolByName("free");
free.call

**Comment by zhkl0228** [comment]
相当于调用c的free

**Comment by RainbowXie** [comment]
好的，谢谢～
