### ISSUE TITLE
请问是否可以为trace提供类似于类似于xposed一样的afterhookinsn接口

### ISSUE THREAD

**Issue by sepyeight** [zhkl0228/unidbg#234]
我想模拟ida pro的trace功能，记录指令执行后寄存器的值，测试时发现现有的接口提供的功能是指令执行前打印指令的方式，大佬能否提供指令执行后的接口呢？

**Comment by zhkl0228** [comment]
指令后的话，遇到跳转指令就乱了，指令级的hook是unicorn提供的功能

**Comment by sepyeight** [comment]
谢谢大佬，我看看有没有取巧的方式解决我的问题
