### ISSUE TITLE
override callObjectMethodV

### ISSUE THREAD

**Issue by leiguo1029** [zhkl0228/unidbg#24]
@Override
    public DvmObject callObjectMethodV(BaseVM vm, DvmObject dvmObject, String signature, VaList vaList) {
        switch (signature){
            case "java/lang/Thread->getStackTrace()[Ljava/lang/StackTraceElement;":
            return  ？？？？
        }
        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }

signature为“java/lang/Thread->getStackTrace()[Ljava/lang/StackTraceElement;”时返回值应该怎么写呢？如何返回object的数组？

**Comment by zhkl0228** [comment]
https://github.com/zhkl0228/unidbg/blob/4e7c3c1f478ed9c97c30fff16995105bf949f40d/src/test/java/com/xunmeng/pinduoduo/secure/DeviceNative.java
这里面有示例

**Comment by leiguo1029** [comment]
> https://github.com/zhkl0228/unidbg/blob/4e7c3c1f478ed9c97c30fff16995105bf949f40d/src/test/java/com/xunmeng/pinduoduo/secure/DeviceNative.java
> 这里面有示例

好的，谢谢    那signature是"java/lang/Thread->currentThread()Ljava/lang/Thread;"呢？返回值如何写？

**Comment by leiguo1029** [comment]
> https://github.com/zhkl0228/unidbg/blob/4e7c3c1f478ed9c97c30fff16995105bf949f40d/src/test/java/com/xunmeng/pinduoduo/secure/DeviceNative.java
> 这里”

> https://github.com/zhkl0228/unidbg/blob/4e7c3c1f478ed9c97c30fff16995105bf949f40d/src/test/java/com/xunmeng/pinduoduo/secure/DeviceNative.java
> 这里面有示例

好的
那signature是“java/lang/Thread->currentThread()Ljava/lang/Thread;”的时候
我这样 return vm.resolveClass("java/lang/Thread").newObject(Thread.currentThread()); 对吗？
