### ISSUE TITLE
请添加对JNI方法: CallBooleanMethodA的支持

### ISSUE THREAD

**Issue by kylin1020** [zhkl0228/unidbg#241]
so文件: 
`链接：https://pan.baidu.com/s/1kcVwiHcPDXO58eBj1RZPeA 
提取码：1sbt 
复制这段内容后打开百度网盘手机App，操作更方便哦`

com/meituan/android/common/mtguard/NBridge$SIUACollector     startCollection()Ljava/lang/String;

**Comment by zhkl0228** [comment]
https://github.com/zhkl0228/unidbg/commit/c4a7b958a9f1693a65e6fdc4e40da93650e32596
