### ISSUE TITLE
dvmMethod == null 引发的错误

### ISSUE THREAD

**Issue by yorkfread** [zhkl0228/unidbg#267]
![image](https://user-images.githubusercontent.com/26402739/112276384-a29e7a00-8cbb-11eb-8df1-4afb9b22fb38.png)

终端输出这个，导致调用so里的方法失败，请问是什么原因？感觉是缺少了方法或参数，但是不知道缺少什么，然后怎么去补充，通过错误桟的代码指向以下：

![image](https://user-images.githubusercontent.com/26402739/112276569-dbd6ea00-8cbb-11eb-9f10-317fd1b1f700.png)

**Comment by yorkfread** [comment]
@zhkl0228 方便的话回复下，谢谢

**Comment by 592767809** [comment]
猿人学的我搞完了，需要自己跳坑，必须使用0.9.3的版本

**Comment by yorkfread** [comment]
> 猿人学的我搞完了，需要自己跳坑，必须使用0.9.3的版本。不过其中也有一些问题值得提出

@592767809 谢谢回复。我是用的最新发布的0.9.3的。这里是有个坑，但因为程序运行时没有错误输出，例如也没有提示缺少什么对象还是函数，我这边就一头雾水，我通过查看反编译so和Google，查到应该跟so里调用了File有关？能给点提示吗？折腾了两三天无从下手

**Comment by 592767809** [comment]
> > 猿人学的我搞完了，需要自己跳坑，必须使用0.9.3的版本。不过其中也有一些问题值得提出
> 
> @ 592767809谢谢回复。我是用的最新发布的0.9.3的。这里是有个坑，但因为程序运行时没有错误输出，例如也没有提示任何东西还是函数，我这边就一头雾水，我通过查看反编译so和Google，查到应该跟so里调用了文件有关？能给点提示吗？

目前处理的核心是hook掉sub_33A14函数，其中与file无关（一开始我也以为有关），会自动帮你处理文件与路径的内容

**Comment by yorkfread** [comment]
@592767809 好的，感谢百忙之中回复，提供了思路，我这边继续练习下

**Comment by zhkl0228** [comment]
参考https://github.com/zhkl0228/unidbg/issues/279解决方案
