### ISSUE TITLE
如何调用类似 sub_xxxx 的函数呢? 

### ISSUE THREAD

**Issue by xiguayizu** [zhkl0228/unidbg#272]
目前我是这么写的，但是貌似arm和thumb没有转换识别过来。
求大神给指条路子
`            VirtualSymbol sub_55AC = new VirtualSymbol("sub_55AC", dm.getModule(), MMAP_BASE+0x55AB);`

**Comment by xiguayizu** [comment]
已解决

**Comment by anjia0532** [comment]
@xiguayizu 大佬能说一下咋解决的么？
