### ISSUE TITLE
find failed   android/sdk23/dev/__properties__

### ISSUE THREAD

**Issue by wengjingqun** [zhkl0228/unidbg#273]
2021-04-04 20:38:02.975  WARN 1681 --- [nio-8122-exec-5] c.g.unidbg.linux.ARM32SyscallHandler     : handleInterrupt intno=2, NR=322, svcNumber=0x0, PC=RX@0x4021d488[libc.so]0x41488, syscall=null
Apr 04 20:38:02 crypto java[1681]: java.lang.IllegalStateException: find failed: jarPath=/home/release/cc.jar, name=BOOT-INF/lib/unidbg-android-0.9.4-SNAPSHOT.jar!/android/sdk23/dev/__properties__
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.utils.ResourceUtils.findJarEntry(ResourceUtils.java:138) ~[unidbg-api-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.utils.ResourceUtils.isFile(ResourceUtils.java:112) ~[unidbg-api-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.utils.ResourceUtils.extractResource(ResourceUtils.java:23) ~[unidbg-api-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.linux.android.AndroidResolver.resolve(AndroidResolver.java:84) ~[unidbg-android-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.unix.UnixSyscallHandler.resolve(UnixSyscallHandler.java:95) ~[unidbg-api-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.unix.UnixSyscallHandler.open(UnixSyscallHandler.java:293) ~[unidbg-api-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.linux.ARM32SyscallHandler.openat(ARM32SyscallHandler.java:1883) ~[unidbg-android-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:389) ~[unidbg-android-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:299) [unidbg-api-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128) [unicorn-1.0.12.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at unicorn.Unicorn.emu_start(Native Method) [unicorn-1.0.12.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:325) [unidbg-api-0.9.4-SNAPSHOT.jar!/:na]
Apr 04 20:38:02 crypto java[1681]: at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:369) [unidbg-a

-------------------------------
大佬，打成jar包报这个警告，有没有影响呢？能解决掉吗？找不到这个文件吧，我看文件里面有的。android/sdk23/dev/__properties__

 @zhkl0228

**Comment by kevinsir** [comment]
我也是这个问题，请问要如何解决呢

**Comment by wengjingqun** [comment]
> 

没有解决

**Comment by kevinsir** [comment]
我升级到最新版本解决了。升级到社区的最新版就可以了
