### ISSUE TITLE
请问在SO里面调用了java层的一个函数要如何调用

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#276]
请问在SO里面调用了java层的一个函数要如何调用。这个java层函数也是封装在APK里面，不是jdk的函数。java层函数现在还没有逆向出来

**Comment by 18670775011** [comment]
vm.setDvmClassFactory(new ProxyClassFactory());再去添加对应的java函数

**Comment by kevinsir** [comment]
设置这个出错了，我后来反编译了java的函数。谢谢
