### ISSUE TITLE
running 异常

### ISSUE THREAD

**Issue by morningKing** [zhkl0228/unidbg#280]
首先非常感谢作者的工作，您的劳动极大的帮到了我。
问题：
AbstractEmulator.java 中的 emulate 不是线程安全的，我在多线程环境下跑您的代码，发现有时会直接跑到下面这段逻辑里面去
![image](https://user-images.githubusercontent.com/16428142/114840217-2b1ac100-9e09-11eb-9141-fb9b30c3db90.png)

**Comment by zhkl0228** [comment]
多线程自己加锁
