### ISSUE TITLE
启动测试example出现报错

### ISSUE THREAD

**Issue by jusk9527** [zhkl0228/unidbg#281]
Error:(116, 41) java: 程序包com.github.unidbg.android.pb不存在
Error:(116, 80) java: 程序包com.github.unidbg.android.pb不存在
Error:(243, 41) java: 程序包com.github.unidbg.android.pb.jkn不存在
Error:(243, 84) java: 程序包com.github.unidbg.android.pb不存在
Error:(258, 41) java: 程序包com.github.unidbg.android.pb.jkl不存在
Error:(258, 84) java: 程序包com.github.unidbg.android.pb不存在

**Comment by zhkl0228** [comment]
先在命令行 mvn test-compile

**Comment by joshuachenn** [comment]
执行完成上述命令后依旧报错——`java: package com.github.unidbg.android.pb does not exist`

**Comment by joshuachenn** [comment]
执行完上述命令后，再Maven=>Reload Project后可以成功运行

**Comment by jusk9527** [comment]
上面答主已经解决！谢谢

**Comment by tigaliang** [comment]
@jusk9527 我在最新的 master 遇到同样问题。你成功的是哪个 commit？

**Comment by tigaliang** [comment]
Ok 我现在 reset 到 `c4ae7366f224b38e5443bf8705576fd59043a442` 可以通过 test
