### ISSUE TITLE
so文件修改byteArray里面的值，如何获取修改后的值呢

### ISSUE THREAD

**Issue by serious-snow** [zhkl0228/unidbg#285]
比如我有一个

byte[] byteArray = {1,2,3,4,5,6};
ByteArray ba = new ByteArray(vm, byteArray );
Native.callStaticJniMethod(emulator,“method([B)V”,ba);
System.out.println(Arrays.equals(byteArray,ba.getValue()));

**Comment by zhkl0228** [comment]
这样应该没问题

**Comment by serious-snow** [comment]
非常感谢，这么久我才来回复
