### ISSUE TITLE
关于调试问题

### ISSUE THREAD

**Issue by JiangJianCong** [zhkl0228/unidbg#29]
作者你好~
在调用之前使用emulator.attach(DebuggerType.GDB_SERVER);
可以进行动态调试么？具体操作应该怎么做，

**Comment by zhkl0228** [comment]
ida打开so，rebase再attach到gdb server

**Comment by bwenpig** [comment]
> ida打开so，rebase再attach到gdb server

我用ida attach 到gdb时候，提示 ：Bogus or irresponsive remote server，请问是不是还有哪个地方设置？
