### ISSUE TITLE
测试某个so出现dvmObject=null, dvmClass=null的情况

### ISSUE THREAD

**Issue by JiangJianCong** [zhkl0228/unidbg#30]
在调用_CallObjectMethodV的时候，DvmObject dvmObject = getObject(object.peer);拿到的东西是空的，求大佬帮忙看看是什么情况。
具体报错如下：
``
unicorn.UnicornException: dvmObject=null, dvmClass=null, jmethodID=unicorn@0x318b4ca9
	at cn.banny.unidbg.linux.android.dvm.DalvikVM$19.handle(DalvikVM.java:308)
	at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:90)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:140)
	at com.ss.sys.ces.CMS.sign(CMS.java:101)
	at com.ss.sys.ces.CMS.main(CMS.java:77)
debugger break at: 0xfffe01b4
>>> r0=0xfffe0920 r1=0xbffff7c4 r2=0x318b4ca9, r3=0xbfffef14 r4=0xb377e5e8 r5=0xfffe0920 r6=0x50bb0e8 r7=0xabf69add r8=0xc148d653 r9=0xfffe0920 r10=0x6fe75f6e fp=0xc148d654 ip=0xfffe01b0 sp=0xbfffef00 lr=0x40011af5 pc=0xfffe01b4 cpsr: N=0, Z=1, C=1, V=0, T=0, mode=0b10000
    [        libcms.so] [0x11ad7] [       fc 44 ] 0x40011ad6: add ip, pc
    [        libcms.so] [0x11ad9] [ dc f8 00 c0 ] 0x40011ad8: ldr.w ip, [ip]
    [        libcms.so] [0x11add] [ dc f8 00 c0 ] 0x40011adc: ldr.w ip, [ip]
    [        libcms.so] [0x11ae1] [       05 93 ] 0x40011ae0: str r3, [sp, #0x14]
    [        libcms.so] [0x11ae3] [       05 ab ] 0x40011ae2: add r3, sp, #0x14
    [        libcms.so] [0x11ae5] [ cd f8 08 c0 ] 0x40011ae4: str.w ip, [sp, #8]
    [        libcms.so] [0x11ae9] [       01 93 ] 0x40011ae8: str r3, [sp, #4]
    [        libcms.so] [0x11aeb] [ d0 f8 00 c0 ] 0x40011aea: ldr.w ip, [r0]
    [        libcms.so] [0x11aef] [ dc f8 8c c0 ] 0x40011aee: ldr.w ip, [ip, #0x8c]
    [        libcms.so] [0x11af3] [       e0 47 ] 0x40011af2: blx ip
    [       0xfffe01b0] [0x001b0] [ 12 01 00 ef ] 0xfffe01b0: svc #0x112
=> *[       0xfffe01b4]*[0x001b4]*[ 1e ff 2f e1 ]*0xfffe01b4:*bx lr
    [       0xfffe01b8] [0x001b8] [ 00 00 00 00 ] 0xfffe01b8: andeq r0, r0, r0
    [       0xfffe01bc] [0x001bc] [ 00 00 00 00 ] 0xfffe01bc: andeq r0, r0, r0
    [       0xfffe01c0] [0x001c0] [ 13 01 00 ef ] 0xfffe01c0: svc #0x113
    [       0xfffe01c4] [0x001c4] [ 1e ff 2f e1 ] 0xfffe01c4: bx lr
    [       0xfffe01c8] [0x001c8] [ 00 00 00 00 ] 0xfffe01c8: andeq r0, r0, r0
    [       0xfffe01cc] [0x001cc] [ 00 00 00 00 ] 0xfffe01cc: andeq r0, r0, r0
    [       0xfffe01d0] [0x001d0] [ 14 01 00 ef ] 0xfffe01d0: svc #0x114
    [       0xfffe01d4] [0x001d4] [ 1e ff 2f e1 ] 0xfffe01d4: bx lr
    [       0xfffe01d8] [0x001d8] [ 00 00 00 00 ] 0xfffe01d8: andeq r0, r0, r0
``

附件：
[upload.zip](https://github.com/zhkl0228/unidbg/files/3387086/upload.zip)

660.apk是dy的apk

**Comment by JiangJianCong** [comment]
[upload.zip](https://github.com/zhkl0228/unidbg/files/3387086/upload.zip)

**Comment by zhkl0228** [comment]
传的java类型不对，一般是Context有很多子类，要传特定的子类

**Comment by JiangJianCong** [comment]
> 传的java类型不对，一般是Context有很多子类，要传特定的子类

我翻源码的时候看到的是com.content.Context，那应该要传入什么子类？

**Comment by zhkl0228** [comment]
根据运行时传入的具体类型

**Comment by JiangJianCong** [comment]
> 据运行时传入的具体类

我hook到传入的子类是
```
// com/ss/android/ugc/aweme/app/host/HostApplication
        Object custom = null;
        DvmObject context = vm.resolveClass("com/ss/android/ugc/aweme/app/host/HostApplication").newObject(custom);
```
你看看这样有问题吗，这样调用还是出现那个异常了

**Comment by zhkl0228** [comment]
这个HostApplication到Context之间的类都试下

**Comment by JiangJianCong** [comment]
> 这个HostApplication到Context之间的类都试下

```
        // com/ss/android/ugc/aweme/app/host/HostApplication
        //  --com/ss/android/ugc/aweme/app/l
        //      -- com/ss/android/ugc/aweme/app/q
        //          -- android/app/Application
        //              -- android/content/ContextWrapper
        //                  --android/content/Context
```
这些我都试过但是还是不行

**Comment by zhkl0228** [comment]
打开cn.banny.unidbg.linux.android.dvm的DEBUG，分析下对应的方法注册在哪个类？

**Comment by JiangJianCong** [comment]
> cn.banny.unidbg.linux.android.dvm

DEBUG在哪里打开？

**Comment by JiangJianCong** [comment]
> 打开cn.banny.unidbg.linux.android.dvm的DEBUG，分析下对应的方法注册在哪个类？

[12:13:21 474] DEBUG [cn.banny.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$75:1337) - RegisterNatives dvmClass=com/ss/sys/ces/a, name=rb, signature=(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)[B, fnPtr=unicorn@0x40031085[libcms.so]0x31085

我把注册的时候的内容都打印出来了 context签名就是android/content/Context，但是还是报那个错

**Comment by zhkl0228** [comment]
打开log后，把DEBUG内容发出来分析下

**Comment by JiangJianCong** [comment]
[log.txt](https://github.com/zhkl0228/unidbg/files/3389460/log.txt)
日志
