### ISSUE TITLE
调用jni方法一直卡住不执行后续操作

### ISSUE THREAD

**Issue by bubbledevteam** [zhkl0228/unidbg#305]
<img width="1601" alt="截屏2021-05-18 下午4 06 54" src="https://user-images.githubusercontent.com/53160423/118615485-5cfdb980-b7f3-11eb-9e21-ffd6dd158625.png">
如图

**Comment by zhkl0228** [comment]
发测试才可以分析

**Comment by bubbledevteam** [comment]
代码下载地址
https://drive.google.com/file/d/1W5dJ5Kg5P3weBZ3ial2gpjQpXkEv1NYa/view?usp=sharing





> 发测试才可以分析

**Comment by zhkl0228** [comment]
使用最新的代码可以成功运行，具体参考 https://github.com/zhkl0228/unidbg/commit/af199a09226a1adbdbc63e473c359fa9d1acf04f

`package com.diabox;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.Module;
import com.github.unidbg.Symbol;
import com.github.unidbg.arm.context.RegisterContext;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.file.linux.AndroidFileIO;
import com.github.unidbg.hook.hookzz.HookEntryInfo;
import com.github.unidbg.hook.hookzz.HookZz;
import com.github.unidbg.hook.hookzz.IHookZz;
import com.github.unidbg.hook.hookzz.WrapCallback;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.AbstractJni;
import com.github.unidbg.linux.android.dvm.BaseVM;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.DvmObject;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.VarArg;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.linux.android.dvm.wrapper.DvmInteger;
import com.github.unidbg.linux.file.ByteArrayFileIO;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.pointer.UnidbgPointer;
import com.github.unidbg.utils.Inspector;
import com.sun.jna.Pointer;
import org.apache.commons.codec.DecoderException;
import org.apache.commons.codec.binary.Hex;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Abbott25 extends AbstractJni implements IOResolver<AndroidFileIO> {

    private final AndroidEmulator emulator;
    private final VM vm;
    private final Module module;

    private final DvmClass cNativeClass;

    /**
     * @param classPath  需要执行的函数所在的Java类路径
     */
    public Abbott25(String classPath) {
        // 创建app进程，包名可任意写

        emulator = AndroidEmulatorBuilder.for64Bit()
                .setProcessName("com.freestylelibre2.app.ca")
                .build(); // 创建模拟器实例，要模拟32位或者64位，在这里区分
        emulator.getSyscallHandler().addIOResolver(this);
//        emulator.getSyscallHandler().setVerbose(true);

        File apkFile = new File("unidbg-android/src/test/resources/app/libre2ca.apk");
        final Memory memory = emulator.getMemory(); // 模拟器的内存操作接口
        memory.setLibraryResolver(new AndroidResolver(23)); // 设置系统类库解析

        vm = emulator.createDalvikVM(apkFile); // 创建Android虚拟机
        vm.setJni(this);
        vm.setVerbose(true); // 设置是否打印Jni调用细节
        long start = System.currentTimeMillis();
        DalvikModule dm = vm.loadLibrary("DataProcessing", false); // 加载libttEncrypt.so到unicorn虚拟内存，加载成功以后会默认调用init_array等函数
        System.out.println("load offset=" + (System.currentTimeMillis() - start) + "ms");
        dm.callJNI_OnLoad(emulator); // 手动执行JNI_OnLoad函数
        module = dm.getModule(); // 加载好的libttEncrypt.so对应为一个模块
//        System.out.println("pid==" + vm.getManifestXml());
        cNativeClass = vm.resolveClass(classPath);
        //调用函数
    }

    @Override
    public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
        if ("/proc/self/status".equals(pathname)) {
            return FileResult.<AndroidFileIO>success(new ByteArrayFileIO(oflags, pathname, ("Name:\tcom.freestylelibre2.app.ca\n" +
                    "State:\tR (running)\n" +
                    "TracerPid:\t0\n" +
                    "FDSize:\t64\n" +
                    "VmPeak:\t    7876 kB\n" +
                    "VmSize:\t    7852 kB\n" +
                    "VmLck:\t       0 kB\n" +
                    "VmPin:\t       0 kB\n" +
                    "VmHWM:\t    1524 kB\n" +
                    "VmRSS:\t    1524 kB\n" +
                    "VmData:\t    4300 kB\n" +
                    "VmStk:\t     136 kB\n" +
                    "VmExe:\t     272 kB\n" +
                    "VmLib:\t    2632 kB\n" +
                    "VmPTE:\t      28 kB\n" +
                    "VmSwap:\t       0 kB\n" +
                    "SigQ:\t0/14024\n" +
                    "SigPnd:\t0000000000000000\n" +
                    "ShdPnd:\t0000000000000000\n" +
                    "SigBlk:\t0000000000000000\n" +
                    "SigIgn:\t0000000000001000\n" +
                    "SigCgt:\t000000000801e4ff\n" +
                    "CapInh:\t0000000000000000\n" +
                    "CapPrm:\t0000000000000000\n" +
                    "CapEff:\t0000000000000000\n" +
                    "CapBnd:\t0000003fffffffff\n" +
                    "Seccomp:\t0\n" +
                    "Cpus_allowed:\tf\n" +
                    "Cpus_allowed_list:\t0-3\n" +
                    "Mems_allowed:\t1\n" +
                    "Mems_allowed_list:\t0\n" +
                    "voluntary_ctxt_switches:\t0\n" +
                    "nonvoluntary_ctxt_switches:\t12\n").getBytes()));
        }
        if ("/proc/net/unix".equals(pathname)) {
            return FileResult.<AndroidFileIO>success(new ByteArrayFileIO(oflags, pathname, ("Num       RefCount Protocol Flags    Type St Inode Path\n" +
                    "0000000000000000: 0000004E 00000000 00000000 0002 01  5376 /dev/socket/logdw\n" +
                    "0000000000000000: 00000003 00000000 00000000 0001 03 30945\n" +
                    "0000000000000000: 00000003 00000000 00000000 0001 03 34216\n" +
                    "0000000000000000: 00000003 00000000 00000000 0001 03 28020\n" +
                    "0000000000000000: 00000003 00000000 00000000 0005 03 27131\n" +
                    "0000000000000000: 00000003 00000000 00000000 0001 03 24191\n").getBytes()));
        }

        return null;
    }

//    @Override
//    public DvmObject newObjectV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
//        System.out.println("newObjectV");
//        switch (signature) {
//            case "java/io/ByteArrayInputStream-><init>([B)V":
//                ByteArray bytes = vaList.getObject(0);
//                ByteArrayInputStream input = new ByteArrayInputStream(bytes.getValue());
//                System.out.println("byte input stream" + bytes.getValue());
//
//        }
//        return super.newObjectV(vm, dvmClass, signature, vaList);
//    }
//
//    public DvmObject<?> callObjectMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {
//        System.out.println("callObjectMethodV");
//        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
//    }
//
//    public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
//        System.out.println("callStaticObjectMethodV");
//        return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);
//    }

    @Override
    public int callStaticIntMethod(BaseVM vm, DvmClass dvmClass, String signature, VarArg varArg) {
        if ("android/os/Process->myPid()I".equals(signature)) {
            return emulator.getPid();
        }
        return super.callStaticIntMethod(vm, dvmClass, signature, varArg);
    }

//    @Override
//    public boolean callStaticBooleanMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
//        System.out.println("callStaticBooleanMethodV=" + signature);
//        return super.callStaticBooleanMethodV(vm, dvmClass, signature, vaList);
//    }

    @Override
    public boolean callStaticBooleanMethod(BaseVM vm, DvmClass dvmClass, String signature, VarArg varArg) {
        if ("android/os/Debug->isDebuggerConnected()Z".equals(signature)) {
            return false;
        }

        return super.callStaticBooleanMethod(vm, dvmClass, signature, varArg);
    }

    /**
     * 调用so文件中的指定函数
     *
     * @param methodSign 传入你要执行的函数信息，需要完整的smali语法格式的函数签名
     * @param args       是即将调用的函数需要的参数
     * @return 函数调用结果
     */
    private String myJni(String methodSign, Object... args) {
        Symbol symbol = module.findSymbolByName(methodSign);
        System.out.println(symbol);
        // 使用jni调用传入的函数签名对应的方法（）
        Object custom = null;
        DvmObject<?> context = vm.resolveClass("android/content/Context").newObject(custom);
        String content = "331a08170300000000000000000000000000000000000000e82a06066a06c8181c806606c8fc1b807f06c8d81b809c06c8c41b808706c8c41b807806c8c01b80c306c8e41b80bb06c8f01b80b406c8f81b80ab06c8f81b80a406c8fc1b809c06c8081c809a06c8081c809806c8101c808f06c8101c808006c8181c808108c8041b801008c8141b803408c8cc1a80ba07c8001b803207c8201b80ab06c8f81b80a104c8501a80c204c8341a80b205c8701a805006c86c1a80b306c8001a807407c83819805f07c88419801d08c8501a80f607c8581b801808c8ec1a808708c8401a80a309c8d818801e09c80c1a804f0ac8e818809b0ac8241b80e90ac8b01b80370bc8141b809d0b883a1b80530cc8801a80ed0bc8f01a80ae0bc8841a805c0bc8301b80ae0ac8181b80d709c88c1a808509c8501a80d808c8bc1a80872b0000a2b3000891094b51140796805a00eda614651ac8045e8974";
        String patchUid = "3C37436000A007E0";
        String patchInfo = "DF000008AA39";
        DvmObject<?> dvmObject = cNativeClass.callStaticJniMethodObject(emulator, methodSign);
        // ret存放返回调用结果存放的地址，获得函数执行后返回值
        return dvmObject.toString();
    }

    private void init() throws DecoderException {
        long start = System.currentTimeMillis();
        Object custom = null;
        DvmObject<?> context = vm.resolveClass("com/librelink/app/core/App").newObject(custom);
        DvmClass dvmClass = vm.findClass("com/librelink/app/core/App");

        cNativeClass.callStaticJniMethod(emulator, "initialize(Ljava/lang/Object;)V", context);
        int i = 1095774808;
        DvmInteger dvmInteger = DvmInteger.valueOf(vm, i);
        int size = cNativeClass.callStaticJniMethodInt(emulator, "getTotalMemorySize(I)I", i);
        System.out.println(size + "=====size");
        boolean va = cNativeClass.callStaticJniMethodBoolean(emulator, "getNeedsReaderInfoForActivation(I)Z", i);
        System.out.println("getNeedsReaderInfoForActivation va=" + va);
        String methodSign = "getActivationPayload(I[B[BB)[B";
        System.out.println(context);
        String content = "331a08170300000000000000000000000000000000000000e82a06066a06c8181c806606c8fc1b807f06c8d81b809c06c8c41b808706c8c41b807806c8c01b80c306c8e41b80bb06c8f01b80b406c8f81b80ab06c8f81b80a406c8fc1b809c06c8081c809a06c8081c809806c8101c808f06c8101c808006c8181c808108c8041b801008c8141b803408c8cc1a80ba07c8001b803207c8201b80ab06c8f81b80a104c8501a80c204c8341a80b205c8701a805006c86c1a80b306c8001a807407c83819805f07c88419801d08c8501a80f607c8581b801808c8ec1a808708c8401a80a309c8d818801e09c80c1a804f0ac8e818809b0ac8241b80e90ac8b01b80370bc8141b809d0b883a1b80530cc8801a80ed0bc8f01a80ae0bc8841a805c0bc8301b80ae0ac8181b80d709c88c1a808509c8501a80d808c8bc1a80872b0000a2b3000891094b51140796805a00eda614651ac8045e8974";
        String patchUid = "DF0A9D0100A407E0";
        String patchInfo = "9D0830018C2C";
        ByteArray buid = new ByteArray(vm, Hex.decodeHex(patchUid.toCharArray()));
        ByteArray bInfo = new ByteArray(vm, Hex.decodeHex(patchInfo.toCharArray()));
        int va1 = cNativeClass.callStaticJniMethodInt(emulator, "getActivationCommand(I[B)B", i, bInfo);
        System.out.println(va1);
//        vm.setJni(this);
//        DvmObject va1= cNativeClass.callStaticJniMethodObject(emulator, methodSign, i,buid,bInfo);
//        DvmObject va1= cNativeClass.callStaticJniMethodObject(emulator, methodSign, i, vm.addLocalObject(buid),vm.addLocalObject(bInfo));
//        DvmObject va1= cNativeClass.callStaticJniMethodObject(emulator, methodSign, i, buid,bInfo);

        // ret存放返回调用结果存放的地址，获得函数执行后返回值

        methodSign = "getProductFamily(I[B)I";
        int getProductFamily = cNativeClass.callStaticJniMethodInt(emulator, methodSign, i, bInfo);
        System.out.println(getProductFamily);
//        methodSign = "getNextRegionToRead(I[B[B[BI)Lcom/abbottdiabetescare/flashglucose/sensorabstractionservice/dataprocessing/MemoryRegion";
//        DvmObject getNextRegionToRead = cNativeClass.callStaticJniMethodObject(emulator, methodSign, i, bInfo);
//        System.out.println(getNextRegionToRead);
        methodSign = "isPatchSupported(I[BLcom/abbottdiabetescare/flashglucose/sensorabstractionservice/ApplicationRegion;)Z";
        Object custom2 = null;
        DvmObject<?> applicationRegion = vm.resolveClass("com/abbottdiabetescare/flashglucose/sensorabstractionservice/ApplicationRegion").newObject(custom2);
//            ApplicationRegion applicationRegion=ApplicationRegion.valueOf("LEVEL_1");
//            DvmObject d1=new DvmObject(vm.resolveClass("com/abbottdiabetescare/flashglucose/sensorabstractionservice/ApplicationRegion")
//                    ,applicationRegion);

        boolean isPatchSupported = cNativeClass.callStaticJniMethodBoolean(emulator, methodSign, i, bInfo, applicationRegion);
        System.out.println(isPatchSupported);

        System.out.println("init offset=" + (System.currentTimeMillis() - start) + "ms");
    }

    /**
     * 关闭模拟器
     */
    private void destroy() throws IOException {
        emulator.close();
        System.out.println("emulator destroy...");
    }

    public static void main(String[] args) throws IOException, DecoderException {
        // 2、需要调用函数所在的Java类完整路径，比如a/b/c/d等等，注意需要用/代替.
        String classPath = "com/abbottdiabetescare/flashglucose/sensorabstractionservice/dataprocessing/DataProcessingNative";
        Abbott25 encryptUtilsJni = new Abbott25(classPath);
        // 输出getGameKey方法调用结果
        encryptUtilsJni.init();
        encryptUtilsJni.destroy();
    }

    private void test() {
        List<Object> list = new ArrayList<>(3);
        list.add(vm.getJNIEnv());
        list.add(cNativeClass.hashCode());
        int i = 1095774808;
        list.add(i);
        String name = "Java_com_abbottdiabetescare_flashglucose_sensorabstractionservice_dataprocessing_DataProcessingNative_getTotalMemorySize";
        for (Module module : emulator.getMemory().getLoadedModules()) {
            Symbol symbol = module.findSymbolByName(name, false);
            if (symbol != null) {
                UnidbgPointer fnPtr = (UnidbgPointer) symbol.createPointer(emulator);
                Number[] numbers = Module.emulateFunction(emulator, fnPtr.peer, list.toArray());
                System.out.println(numbers[0]);
                break;

            }
        }
    }

    private void test2() {
        IHookZz hookZz = HookZz.getInstance(emulator); // 加载HookZz，支持inline hook，文档看https://github.com/jmpews/HookZz
//        hookZz.enable_arm_arm64_b_branch(); // 测试enable_arm_arm64_b_branch，可有可无
        hookZz.wrap(module.findSymbolByName("getTotalMemorySize"), new WrapCallback<RegisterContext>() { // inline wrap导出函数
            @Override
            public void preCall(Emulator<?> emulator, RegisterContext ctx, HookEntryInfo info) {
                Pointer pointer = ctx.getPointerArg(2);
                int length = ctx.getIntArg(3);
                byte[] key = pointer.getByteArray(0, length);
                Inspector.inspect(key, "ss_encrypt key");
            }

            @Override
            public void postCall(Emulator<?> emulator, RegisterContext ctx, HookEntryInfo info) {
                System.out.println("ss_encrypt.postCall R0=" + ctx.getLongArg(0));
            }
        });
    }
}`

**Comment by bubbledevteam** [comment]
> 使用最新的代码可以成功运行，具体参考 [af199a0](https://github.com/zhkl0228/unidbg/commit/af199a09226a1adbdbc63e473c359fa9d1acf04f)
> 
> [Abbott25.java.zip](https://github.com/zhkl0228/unidbg/files/6510172/Abbott25.java.zip)

[Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6512686/Abbott252.java.zip)
调用另外一个解析数据的方法 返回null

**Comment by zhkl0228** [comment]
> > 使用最新的代码可以成功运行，具体参考 [af199a0](https://github.com/zhkl0228/unidbg/commit/af199a09226a1adbdbc63e473c359fa9d1acf04f)
> > [Abbott25.java.zip](https://github.com/zhkl0228/unidbg/files/6510172/Abbott25.java.zip)
> 
> [Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6512686/Abbott252.java.zip)
> 调用另外一个解析数据的processScan方法 返回null

使用 https://github.com/zhkl0228/unidbg/commit/e89c26109595cf67c71885b63f83423bf9526414 继续跑，本地库有读取 /data/data/com.freestylelibre2.app.ca/cache/skb.kc 这个文件，看是否有需要补充
[Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6513096/Abbott252.java.zip)

**Comment by bubbledevteam** [comment]
> > > 使用最新的代码可以成功运行，具体参考 [af199a0](https://github.com/zhkl0228/unidbg/commit/af199a09226a1adbdbc63e473c359fa9d1acf04f)
> > > [Abbott25.java.zip](https://github.com/zhkl0228/unidbg/files/6510172/Abbott25.java.zip)
> > 
> > 
> > [Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6512686/Abbott252.java.zip)
> > 调用另外一个解析数据的processScan方法 返回null
> 
> 使用 [e89c261](https://github.com/zhkl0228/unidbg/commit/e89c26109595cf67c71885b63f83423bf9526414) 继续跑，本地库有读取 /data/data/com.freestylelibre2.app.ca/cache/skb.kc 这个文件，看是否有需要补充
> [Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6513096/Abbott252.java.zip)

[Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6513304/Abbott252.java.zip)
我添加了callIntMethod和callBooleanMethod 但是没有double的回调 现在还是返回null

**Comment by zhkl0228** [comment]
https://github.com/zhkl0228/unidbg/commit/734197b1c05e18f6b71ec9764b819cfceefc8b6f 已提交

**Comment by bubbledevteam** [comment]
> [734197b](https://github.com/zhkl0228/unidbg/commit/734197b1c05e18f6b71ec9764b819cfceefc8b6f) 已提交

[Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6513836/Abbott252.java.zip)
我吧对应的回调都加上了 现在可以返回了  但是对应的值的对象怎么获取出来了 
他本身是通过传入的out对象获取的 但是我打印out 都是null
下面是他本身的代码

` public DataProcessingScanOutputs a(AlarmConfiguration alarmConfiguration, NonActionableConfiguration nonActionableConfiguration, GlucoseValueRange glucoseValueRange, AttenuationConfiguration attenuationConfiguration, byte[] bArr, byte[] bArr2, byte[] bArr3, int i, int i2, int i3, int i4, int i5, byte[] bArr4, byte[] bArr5, byte[] bArr6) {
        Out out = r27;
        Out out2 = new Out();
        Out out3 = r28;
        Out out4 = new Out();
        Out out5 = r29;
        Out out6 = new Out();
        Out out7 = r30;
        Out out8 = new Out();
        Out out9 = r31;
        Out out10 = new Out();
        Out out11 = r32;
        Out out12 = new Out();
        Out out13 = r33;
        Out out14 = new Out();
        Out out15 = r34;
        Out out16 = new Out();
        Out out17 = r35;
        Out out18 = new Out();
        Out out19 = r36;
        Out out20 = new Out();
        DataProcessingResult processScan = processScan(this.AFa, alarmConfiguration, nonActionableConfiguration,
                glucoseValueRange, attenuationConfiguration, bArr, bArr2, bArr3,
                i, i2, i3, i4, i5, bArr4, bArr5, bArr6,
                out, out3, out5, out7, out9, out11, out13, out15, out17, out19);
        if (processScan == DataProcessingResult.SUCCESS) {
            return new DataProcessingScanOutputs(((Integer) out2.value()).intValue(), 
                    ((Integer) out4.value()).intValue(),
                    ((Boolean) out6.value()).booleanValue(), 
                    ((Boolean) out8.value()).booleanValue(), 
                    (byte[]) out10.value(), (byte[]) out12.value(), 
                    (byte[]) out14.value(), (AlgorithmResults) out16.value(),
                    ((Byte) out20.value()).byteValue(), (List) out18.value());
        }
        throw new DataProcessingException(processScan, (List) out18.value(), ((Byte) out20.value()).byteValue(), (byte[]) out14.value());
    }`

**Comment by bubbledevteam** [comment]
现在out out3, out5, out7, out9, out11, out13, out15, out17, out19 这些有值了 但是对应返回的值不对
他用的是 out2  out4, out6,out8, out10, out12, out14, out16,out18,out20这些 我翻译的源码 查不到他对应的r27 , r28这些是哪里声明的 
有办法获取到加载apk的classloader吗 我想直接调用他的java 中的.a方法 应该是可以获取到实际值的

**Comment by zhkl0228** [comment]
这里只处理unidbg相关，其它方面自行研究

**Comment by bubbledevteam** [comment]
> 这里只处理unidbg相关，其它方面自行研究

好的 谢谢啦

**Comment by bubbledevteam** [comment]
Closed and delete

**Comment by kuang438951276** [comment]
> > > [734197b](https://github.com/zhkl0228/unidbg/commit/734197b1c05e18f6b71ec9764b819cfceefc8b6f) 已提交
> > 
> > 
> > [Abbott252.java.zip](https://github.com/zhkl0228/unidbg/files/6513836/Abbott252.java.zip)
> > 我吧对应的回调都加上了 现在可以返回了 但是对应的值的对象怎么获取出来了
> > 他本身是通过传入的out对象获取的 但是我打印out 都是null
> > 下面是他本身的代码
> > ```java
> >  public DataProcessingScanOutputs a(AlarmConfiguration alarmConfiguration, NonActionableConfiguration nonActionableConfiguration, GlucoseValueRange glucoseValueRange, AttenuationConfiguration attenuationConfiguration, byte[] bArr, byte[] bArr2, byte[] bArr3, int i, int i2, int i3, int i4, int i5, byte[] bArr4, byte[] bArr5, byte[] bArr6) {
> >         Out out = r27;
> >         Out out2 = new Out();
> >         Out out3 = r28;
> >         Out out4 = new Out();
> >         Out out5 = r29;
> >         Out out6 = new Out();
> >         Out out7 = r30;
> >         Out out8 = new Out();
> >         Out out9 = r31;
> >         Out out10 = new Out();
> >         Out out11 = r32;
> >         Out out12 = new Out();
> >         Out out13 = r33;
> >         Out out14 = new Out();
> >         Out out15 = r34;
> >         Out out16 = new Out();
> >         Out out17 = r35;
> >         Out out18 = new Out();
> >         Out out19 = r36;
> >         Out out20 = new Out();
> >         DataProcessingResult processScan = processScan(this.AFa, alarmConfiguration, nonActionableConfiguration,
> >                 glucoseValueRange, attenuationConfiguration, bArr, bArr2, bArr3,
> >                 i, i2, i3, i4, i5, bArr4, bArr5, bArr6,
> >                 out, out3, out5, out7, out9, out11, out13, out15, out17, out19);
> >         if (processScan == DataProcessingResult.SUCCESS) {
> >             return new DataProcessingScanOutputs(((Integer) out2.value()).intValue(),
> >                     ((Integer) out4.value()).intValue(),
> >                     ((Boolean) out6.value()).booleanValue(),
> >                     ((Boolean) out8.value()).booleanValue(),
> >                     (byte[]) out10.value(), (byte[]) out12.value(),
> >                     (byte[]) out14.value(), (AlgorithmResults) out16.value(),
> >                     ((Byte) out20.value()).byteValue(), (List) out18.value());
> >         }
> >         throw new DataProcessingException(processScan, (List) out18.value(), ((Byte) out20.value()).byteValue(), (byte[]) out14.value());
> >     }
> > ```
> 
> 参考 [0436537](https://github.com/zhkl0228/unidbg/commit/0436537555d0222f8ff0639be8ccabbf952388d2) [src.zip](https://github.com/zhkl0228/unidbg/files/6518356/src.zip)

大佬，请教一下这个文件是怎么来的？我最近最研究雅培的OOP算法，com/abbottdiabetescare/flashglucose/sensorabstractionservice/AlarmConfiguration这个包名是从哪里获取的？
