### ISSUE TITLE
unidbg调试dy出错

### ISSUE THREAD

**Issue by LLYJT** [zhkl0228/unidbg#32]
@zhkl0228 
我测试抖音时遇到奔溃日志：
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:140)
	at com.ss.sys.ces.CMSTest.sign(CMSTest.java:105)
	at com.ss.sys.ces.CMSTest.main(CMSTest.java:75)
debugger break at: 0x40012a54
>>> r0=0x0 r1=0x414e1111 r2=0x574598f8, r3=0x0 r4=0xf72315d4 r5=0x18353522 r6=0x574598f7 r7=0xd7977dd5 sb=0x61cad990 sl=0x414e1112 fp=0x1 ip=0x0 sp=0xbfffe160 lr=0x61cad990 pc=0x40012a54 cpsr: N=0, Z=1, C=1, V=0, T=1, mode=0b10000
=> *[        libcms.so]*[0x12a55]*[*      01 9b ]*0x40012a54:*ldr r3, [sp, #4]
    [        libcms.so] [0x12a57] [       03 93 ] 0x40012a56: str r3, [sp, #0xc]
    [        libcms.so] [0x12a59] [       03 9b ] 0x40012a58: ldr r3, [sp, #0xc]
    [        libcms.so] [0x12a5b] [       1b 78 ] 0x40012a5a: ldrb r3, [r3]
    [        libcms.so] [0x12a5d] [       00 2b ] 0x40012a5c: cmp r3, #0
    [        libcms.so] [0x12a5f] [       23 46 ] 0x40012a5e: mov r3, r4
    [        libcms.so] [0x12a61] [       04 bf ] 0x40012a60: itt eq
    [        libcms.so] [0x12a63] [ 43 f2 22 53 ] 0x40012a62: movweq r3, #0x3522
    [        libcms.so] [0x12a67] [ c1 f6 35 03 ] 0x40012a66: movteq r3, #0x1835
    [        libcms.so] [0x12a6b] [       21 e0 ] 0x40012a6a: b #0x40012ab0
[CMSTest.zip](https://github.com/zhkl0228/unidbg/files/3401221/CMSTest.zip)
这个是我的测试代码
其实问题跟这个https://github.com/zhkl0228/unidbg/issues/21的作者是一样的，debug单步调试文件读取应该是没有问题的，但是最后还是出现了这样的错误报告，希望能得到大佬的答复，谢谢

**Comment by zhkl0228** [comment]
这是具体逆向的问题

**Comment by LLYJT** [comment]
> 这是具体逆向的问题

你对那个作者的解答我其实没看太懂他是怎么解决这个问题，所以想问下你是怎么帮他处理的

**Comment by zhkl0228** [comment]
我没帮他，他自己分析解决的

**Comment by LLYJT** [comment]
好的好的，谢谢
