### ISSUE TITLE
JNIEnv function table  

### ISSUE THREAD

**Issue by Chensem** [zhkl0228/unidbg#320]
JNI 函数表有点问题导致我不能调用CallLongMethod ， 通过debug，发现此偏移处的函数地址没有加上基地址，所以我想问一下这个代码location，方便我改一下，谢谢作者

**Comment by zhkl0228** [comment]
DalvikVM或者DalvikVM64

**Comment by Chensem** [comment]
> DalvikVM或者DalvikVM64

好滴 ，解决了谢谢作者
