### ISSUE TITLE
callJNI_OnLoad加载不起来，报错

### ISSUE THREAD

**Issue by RickyCong** [zhkl0228/unidbg#324]
# callJNI_OnLoad加载不起来
1.即使加了`vm.setDvmClassFactory(new ProxyClassFactory());` （见图1）
2.通过frida hook `JNI_OnLoad` 是能拿到返回值的（见图2）

猜测，是不是so对unidbg检测了
### 代码和so样本
```shell
链接：https://pan.baidu.com/s/1rfGqu6YA_6s0suF6cnH_kQ 
提取码：m0f3 
```

```shell
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff
	at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:195)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:39)
	at com.xunmeng.pinduoduo.secure.SecureNative.<init>(SecureNative.java:38)
	at com.xunmeng.pinduoduo.secure.SecureNative.main(SecureNative.java:46)
```
![图1](https://user-images.githubusercontent.com/46929436/123112388-3d9c2100-d470-11eb-9c2c-d7b63d480144.jpg)
![图2](https://user-images.githubusercontent.com/46929436/123115427-aedcd380-d472-11eb-880b-a0055f129c76.png)

### SecureNative.java
``` java
package com.xunmeng.pinduoduo.secure;


import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Module;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.jni.ProxyClassFactory;
import com.github.unidbg.memory.Memory;

import java.io.File;

public class SecureNative {
    private final AndroidEmulator emulator;
    private final Module module;

    private final DvmClass cNative;


    public SecureNative() {
        emulator = AndroidEmulatorBuilder
                .for32Bit()
                .setProcessName("com.xunmeng.pinduoduo")
                .build();


        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));

        VM vm = emulator.createDalvikVM();
        vm.setDvmClassFactory(new ProxyClassFactory());
        vm.setVerbose(true);

        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/pinduoduo_56600/armeabi-v7a/libpdd_secure.so"), true);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();

        cNative = vm.resolveClass("com/xunmeng/pinduoduo/secure/SecureNative");
    }


    public static void main(String[] args) throws Exception {
        SecureNative test = new SecureNative();
    }
}
```

**Comment by zhkl0228** [comment]
`package com.xunmeng.pinduoduo.secure;


import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.Module;
import com.github.unidbg.arm.Arm64Svc;
import com.github.unidbg.arm.ArmSvc;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.AbstractJni;
import com.github.unidbg.linux.android.dvm.BaseVM;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.VaList;
import com.github.unidbg.linux.android.dvm.jni.ProxyClassFactory;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.memory.SvcMemory;
import com.github.unidbg.pointer.UnidbgPointer;
import com.github.unidbg.virtualmodule.VirtualModule;

import java.io.File;
import java.util.Map;

public class SecureNative extends AbstractJni {

    private final AndroidEmulator emulator;
    private final Module module;

    private final DvmClass cNative;

    private static class UserEnvModule extends VirtualModule<Object> {

        protected UserEnvModule(Emulator<?> emulator) {
            super(emulator, null, "libUserEnv.so");
        }

        @Override
        protected void onInitialize(Emulator<?> emulator, Object extra, Map<String, UnidbgPointer> symbols) {
            SvcMemory svcMemory = emulator.getSvcMemory();
            symbols.put("GetUserEnvStr", svcMemory.registerSvc(new ArmSvc() {
                @Override
                public long handle(Emulator<?> emulator) {
                    throw new UnsupportedOperationException();
                }
            }));
            symbols.put("FreeUserEnvStr", svcMemory.registerSvc(new ArmSvc() {
                @Override
                public long handle(Emulator<?> emulator) {
                    throw new UnsupportedOperationException();
                }
            }));
            symbols.put("InitUserEnv", svcMemory.registerSvc(new ArmSvc() {
                @Override
                public long handle(Emulator<?> emulator) {
                    throw new UnsupportedOperationException();
                }
            }));
        }
    }

    public SecureNative() {
        emulator = AndroidEmulatorBuilder
                .for32Bit()
                .setProcessName("com.xunmeng.pinduoduo")
                .build();

        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));
        new UserEnvModule(emulator).register(memory);

        VM vm = emulator.createDalvikVM();
        vm.setJni(this);
        vm.setVerbose(true);

        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libpdd_secure.so"), false);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();

        cNative = vm.resolveClass("com/xunmeng/pinduoduo/secure/SecureNative");
    }

    @Override
    public void callStaticVoidMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        switch (signature) {
            case "com/tencent/mars/xlog/PLog->i(Ljava/lang/String;Ljava/lang/String;)V":
                return;
        }

        super.callStaticVoidMethodV(vm, dvmClass, signature, vaList);
    }

    public static void main(String[] args) throws Exception {
        SecureNative test = new SecureNative();
    }

}
`

**Comment by RickyCong** [comment]
收到，非常感谢大佬

**Comment by HuangZurong** [comment]
> 收到，非常感谢大佬

pdd逆向还在研究么

**Comment by RickyCong** [comment]
> > 收到，非常感谢大佬
> 
> pdd逆向还在研究么

在的
