### ISSUE TITLE
求助，调用so函数提示UC_ERR_INSN_INVALID

### ISSUE THREAD

**Issue by hangaoke1** [zhkl0228/unidbg#325]
示例代码
```java
package com.mydemo;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Module;
import com.github.unidbg.arm.backend.DynarmicFactory;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.linux.android.dvm.jni.ProxyClassFactory;
import com.github.unidbg.memory.Memory;

import java.io.File;
import java.io.IOException;

public class TTEncrypt extends AbstractJni {
    private final AndroidEmulator emulator;
    private final VM vm;
    private final Module module;
    private final DvmClass TTEncryptUtils;
    private final boolean logging;

    TTEncrypt(boolean logging) {
        this.logging = logging;

        emulator = AndroidEmulatorBuilder.for32Bit().setProcessName("com.greenpoint.android.jni").build(); // 创建模拟器实例，要模拟32位或者64位，在这里区分
        final Memory memory = emulator.getMemory(); // 模拟器的内存操作接口
        memory.setLibraryResolver(new AndroidResolver(23)); // 设置系统类库解析

        vm = emulator.createDalvikVM(); // 创建Android虚拟机
        vm.setDvmClassFactory(new ProxyClassFactory());
        vm.setVerbose(logging); // 设置是否打印Jni调用细节
        vm.setJni(this);
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/libjni.so"), false); // 加载libttEncrypt.so到unicorn虚拟内存，加载成功以后会默认调用init_array等函数
        dm.callJNI_OnLoad(emulator); // 手动执行JNI_OnLoad函数
        module = dm.getModule(); // 加载好的libttEncrypt.so对应为一个模块
        TTEncryptUtils = vm.resolveClass("com/greenpoint/android/jni/Algo");

        System.out.println(module.getRegions());
        System.out.println(emulator.getMemory().getLoadedModules());
    }

    void destroy() throws IOException {
        emulator.close();
        if (logging) {
            System.out.println("destroy");
        }
    }

    public static void main(String[] args) throws Exception {
        TTEncrypt test = new TTEncrypt(true);
        String methodSign = "Encrypt(Ljava/lang/String;)Lcom/greenpoint/android/jni/RsaInfo;";
        test.myJni(methodSign, "123456");

        test.destroy();
    }

    private String myJni(String methodSign, String str) {
        DvmObject<RsaInfo> ret = TTEncryptUtils.callStaticJniMethodObject(emulator, methodSign, new StringObject(vm, str)); // 执行Jni方法
        System.out.println("==== 返回结果 ====");
        System.out.println(ret);
        return "";
    }
}
```

```java
package com.mydemo;
public class RsaInfo {
    public int RetCode;
    public String Value;

    public int getRetCode() {
        return this.RetCode;
    }

    public String getValue() {
        return this.Value;
    }
}
```

返回异常信息
```
Java_com_greenpoint_android_jni_Algo_Encrypt
Find native function Java_com_greenpoint_android_jni_Algo_Encrypt(Ljava/lang/String;)Lcom/greenpoint/android/jni/RsaInfo; => RX@0x4000541d[libjni.so]0x541d
[15:34:03 631]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x4000541d[libjni.so]0x541d exception sp=unidbg@0xbffff788, msg=unicorn.UnicornException: Invalid instruction (UC_ERR_INSN_INVALID), offset=0ms
==== 返回结果 ====
null
destroy

Process finished with exit code 0
```

[so文件地址](https://hgkcdn.oss-cn-shanghai.aliyuncs.com/libjni.so)

**Comment by zhkl0228** [comment]
使用最新代码运行

`package com.greenpoint.android.jni;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.file.linux.AndroidFileIO;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.DvmObject;
import com.github.unidbg.linux.android.dvm.StringObject;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.jni.ProxyClassFactory;
import com.github.unidbg.linux.file.MapsFileIO;
import com.github.unidbg.memory.Memory;

import java.io.File;
import java.io.IOException;

public class Algo implements IOResolver<AndroidFileIO> {

    private final AndroidEmulator emulator;
    private final VM vm;
    private final DvmClass cAlgo;
    private final boolean logging;

    @Override
    public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
        if ("/proc/self/maps".equals(pathname)) {
            return FileResult.<AndroidFileIO>success(new MapsFileIO(oflags, pathname, emulator.getMemory().getLoadedModules(), "DexHelper") {});
        }
        return null;
    }

    Algo(boolean logging) {
        this.logging = logging;

        emulator = AndroidEmulatorBuilder.for32Bit().setProcessName("com.greenpoint.android.jni").build(); // 创建模拟器实例，要模拟32位或者64位，在这里区分
        final Memory memory = emulator.getMemory(); // 模拟器的内存操作接口
        memory.setLibraryResolver(new AndroidResolver(23)); // 设置系统类库解析
        emulator.getSyscallHandler().addIOResolver(this);

        vm = emulator.createDalvikVM(); // 创建Android虚拟机
        vm.setVerbose(logging); // 设置是否打印Jni调用细节
        vm.setDvmClassFactory(new ProxyClassFactory());
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libjni.so"), false); // 加载libttEncrypt.so到unicorn虚拟内存，加载成功以后会默认调用init_array等函数
        dm.callJNI_OnLoad(emulator); // 手动执行JNI_OnLoad函数
        cAlgo = vm.resolveClass("com/greenpoint/android/jni/Algo");
    }

    void destroy() throws IOException {
        emulator.close();
        if (logging) {
            System.out.println("destroy");
        }
    }

    public static void main(String[] args) throws Exception {
        Algo test = new Algo(true);
        String methodSign = "Encrypt(Ljava/lang/String;)Lcom/greenpoint/android/jni/RsaInfo;";
        System.out.println(test.myJni(methodSign, "123456"));
        System.out.println(test.myJni(methodSign, "7890ab"));

        test.destroy();
    }

    private RsaInfo myJni(String methodSign, String str) {
        DvmObject<RsaInfo> ret = cAlgo.callStaticJniMethodObject(emulator, methodSign, new StringObject(vm, str)); // 执行Jni方法
        return ret.getValue();
    }
}`

`package com.greenpoint.android.jni;

public class RsaInfo {

    public int RetCode;
    public String Value;

    @Override
    public String toString() {
        return "RsaInfo{" +
                "RetCode=" + RetCode +
                ", Value='" + Value + '\'' +
                '}';
    }
}`

**Comment by hangaoke1** [comment]
感谢大佬！
