### ISSUE TITLE
测试运行mp4v2.so文件的时候程序挂起了，哪位大神帮忙看下

### ISSUE THREAD

**Issue by kaixinwangzi1982** [zhkl0228/unidbg#326]
运行手机端的so文件的时候，第一个参数是一个视频文件的路径，第二个参数是一个字符窜，运行后程序挂起了，不知道代码问题还是哪里问题，程序也不打印结果File file = new File("/disk/apps/wubaapp/libMp4v2.dylib");
        DalvikModule dm = vm.loadLibrary(file.canRead() ? file : new File("/disk/apps/wubaapp/libMp4v2.dylib"), true);
        dm.callJNI_OnLoad(emulator);

        cUtilities = vm.resolveClass("com/wbvideo/encrypt/WBMp4v2");
        
        String filePath = "/Users/etui/Downloads/tesst/VID_20210625_130236391.mp4";
    	String key = "392284585";
        long start = System.currentTimeMillis();
//        emulator.traceCode();
        boolean success = cUtilities.callStaticJniMethodBoolean(emulator, "tagsWithFilePath(Ljava/lang/String;Ljava/lang/String;)Z", new StringObject(vm, filePath), new StringObject(vm, key));
//        Inspector.inspect("c offset=" + (System.currentTimeMillis() - start) + "ms");

下面是日志：
[libMp4v2.so]CallInitFunction: RX@0x400719a4[libMp4v2.so]0x719a4, offset=2ms
Find native function Java_com_wbvideo_encrypt_WBMp4v2_tagsWithFilePath(Ljava/lang/String;Ljava/lang/String;)Z => RX@0x400f09f8[libMp4v2.so]0xf09f8

LR=RX@0x4033e024[libc.so]0x1e024
SP=0xbfffddb0
PC=RX@0x4038ac14[libc.so]0x6ac14
nzcv: N=0, Z=0, C=0, V=0, EL0, use SP_EL0
debugger break at: 0x4038ac14

出现这个日志后程序就走不动了，代码就挂起了，服务也没停止

**Comment by zhkl0228** [comment]
发代码及相关文件

**Comment by kaixinwangzi1982** [comment]
@zhkl0228 我把代码和so文件放到附件里了,谢谢
[unidbgTest.zip](https://github.com/zhkl0228/unidbg/files/6730351/unidbgTest.zip)

**Comment by zhkl0228** [comment]
VID_20210625_130236391.mp4这个文件也要

**Comment by kaixinwangzi1982** [comment]
@zhkl0228 上传到附件了
https://user-images.githubusercontent.com/19239894/123738178-e74b3a00-d8d6-11eb-8aa8-1e84b584e489.mp4

**Comment by zhkl0228** [comment]
```
package com.github.unidbg.android;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.LibraryResolver;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.file.linux.AndroidFileIO;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.AbstractJni;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.file.SimpleFileIO;
import com.github.unidbg.memory.Memory;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

import java.io.File;
import java.io.IOException;

public class Mp4v2 extends AbstractJni implements IOResolver<AndroidFileIO> {

    public static void main(String[] args) throws IOException {
        Logger.getLogger("com.github.unidbg.linux.ARM64SyscallHandler").setLevel(Level.INFO);
        new Mp4v2().test();
    }

    private final AndroidEmulator emulator;
    private final DvmClass cWBMp4v2;

    private Mp4v2() {
        emulator = AndroidEmulatorBuilder.for64Bit()
                .build();
        Memory memory = emulator.getMemory();
        LibraryResolver resolver = new AndroidResolver(23);
        memory.setLibraryResolver(resolver);
        emulator.getSyscallHandler().addIOResolver(this);

        VM vm = emulator.createDalvikVM();
        vm.setVerbose(true);
        vm.setJni(this);
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/arm64-v8a/libMp4v2.dylib"), false);
        dm.callJNI_OnLoad(emulator);
        this.cWBMp4v2 = vm.resolveClass("com/wbvideo/encrypt/WBMp4v2");

//        {
//            Pointer pointer = memory.allocateStack(0x100);
//            System.out.println(new Stat64(pointer));
//        }
    }

    @Override
    public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
        if ("/Users/etui/Downloads/tesst/VID_20210625_130236391.mp4".equals(pathname)) {
            return FileResult.<AndroidFileIO>success(new SimpleFileIO(oflags, new File("unidbg-android/src/test/resources/123738178-e74b3a00-d8d6-11eb-8aa8-1e84b584e489.mp4"), pathname));
        }

        return null;
    }
//    @Override
//    public float callStaticFloatMethod(BaseVM vm, DvmClass dvmClass, String signature, VarArg varArg) {
//        if ("com/github/unidbg/android/AndroidTest->testStaticFloat(FD)F".equals(signature)) {
//            return 0.0023942017F;
//        }
//
//        return super.callStaticFloatMethod(vm, dvmClass, signature, varArg);
//    }
//
//    @Override
//    public boolean getStaticBooleanField(BaseVM vm, DvmClass dvmClass, String signature) {
//        if ("com/github/unidbg/android/AndroidTest->staticBooleanField:Z".equals(signature)) {
//            return true;
//        }
//
//        return super.getStaticBooleanField(vm, dvmClass, signature);
//    }
    

    private void test() {
    	String filePath = "/Users/etui/Downloads/tesst/VID_20210625_130236391.mp4";
    	String key = "392284585";
        boolean success = cWBMp4v2.callStaticJniMethodBoolean(emulator, "tagsWithFilePath(Ljava/lang/String;Ljava/lang/String;)Z;",
                filePath, key);

//        emulator.attach().addBreakPoint(null, 0x40080648);
        System.err.println("是否成功: " + success);
        try {
			emulator.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
//        emulator.destroy();
    }

}

```

**Comment by kaixinwangzi1982** [comment]
@zhkl0228 你好，我配置好了路径，测试了下你给我的demo，日志如附件
![WechatIMG15112](https://user-images.githubusercontent.com/19239894/123893369-db22b380-d98e-11eb-83a6-4c0c721fa3cc.png)

**Comment by zhkl0228** [comment]
这不是正常运行吗？怎样才算运行成功？

**Comment by kaixinwangzi1982** [comment]
我调用的方法返回值是boolean的，返回了false，返回true才算成功

**Comment by kaixinwangzi1982** [comment]
[mp4v2-Release-ThirdParty-MP4v2-5.0.0.zip](https://github.com/zhkl0228/unidbg/files/6737931/mp4v2-Release-ThirdParty-MP4v2-5.0.0.zip)
附件中是源码

**Comment by kaixinwangzi1982** [comment]
先不用看了,谢谢大神

**Comment by kaixinwangzi1982** [comment]
你好：
     有个so文件接口如下  privatestaticnativeStringencrypt(byte[]bArr);
我的代码// 密码加密

    publicstatic String encrypt(String info) throws IOException {

        // 1、需要调用的so文件所在路径

        String soFilePath = "/disk/apps/wubaapp/libcom_wuba_uc_rsa.so";

        // 2、需要调用函数所在的Java类完整路径，比如a/b/c/d等等，注意需要用/代替.

        String classPath = "com/wuba/uc/RsaCryptService";

        // 3、需要调用函数的函数签名，我这里调用EncryptUtils中的getGameKey方法，由于此方法没有参数列表，所以不需要传入

        String methodSign = "encrypt([B)Ljava/lang/String;";

        // 输出getGameKey方法调用结果

        WuBaAppSignUtils encryptUtilsJni = new WuBaAppSignUtils(soFilePath, classPath);

        byte[] bytes = (byte[]) null;

        if(StringUtils.isNotBlank(info)) {

        bytes = info.getBytes();

        }

        String encryption = encryptUtilsJni.myJni(methodSign, new ByteArray(encryptUtilsJni.vm, bytes));

        logger.info("移动经纪人加密结果:[{}]", encryption);

        encryptUtilsJni.destroy();

        returnencryption;

    }




  如下错误：java.lang.UnsatisfiedLinkError: no unicorn_java in java.library.path

at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)

at java.lang.Runtime.loadLibrary0(Runtime.java:872)

at java.lang.System.loadLibrary(System.java:1124)

at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136)

at unicorn.Unicorn.<clinit>(Unicorn.java:159)

at com.github.unidbg.AbstractEmulator.<init>(AbstractEmulator.java:83)

at com.github.unidbg.arm.AbstractARMEmulator.<init>(AbstractARMEmulator.java:49)

at com.github.unidbg.linux.android.AndroidARMEmulator.<init>(AndroidARMEmulator.java:52)

at com.github.unidbg.linux.android.AndroidARMEmulator.<init>(AndroidARMEmulator.java:44)

at com.github.unidbg.utils.WuBaAppSignUtils.<init>(WuBaAppSignUtils.java:54)

at com.github.unidbg.utils.WuBaAppSignUtils.encrypt(WuBaAppSignUtils.java:214)

at com.github.servlet.YdjjEncryptServlet.doPost(YdjjEncryptServlet.java:32)

at com.github.servlet.YdjjEncryptServlet.doGet(YdjjEncryptServlet.java:25)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)

at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)

at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)

at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)

at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)
















在 2021-06-30 11:51:34，"Banny" ***@***.***> 写道：

这不是正常运行吗？怎样才算运行成功？

**Comment by kaixinwangzi1982** [comment]
你好：
      调用so文件的代码在附件中，我们自己实现调用的代码是第二个附件，现在调用包报错
java.lang.IllegalArgumentException: find method failed: init(Landroid/content/Context)
	com.github.unidbg.linux.android.dvm.DvmClass.findNativeFunction(DvmClass.java:213)
	com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:88)
	com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:250)
	com.github.unidbg.utils.WuBaAppSignUtils.myJni(WuBaAppSignUtils.java:109)
	com.github.unidbg.utils.WuBaAppSignUtils.encrypt(WuBaAppSignUtils.java:217)
	com.github.servlet.YdjjEncryptServlet.doPost(YdjjEncryptServlet.java:32)
	com.github.servlet.YdjjEncryptServlet.doGet(YdjjEncryptServlet.java:25)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
       是不是我调用context参数的init方法写的语法有问题，请指教，谢谢
package com.wuba.uc;

import android.content.Context;
import android.text.TextUtils;
import android.util.Log;
import androidx.annotation.Keep;
import com.wuba.loginsdk.a;
import com.wuba.loginsdk.relinker.b;

@Keep
/* loaded from: /Users/adam/Downloads/out/_5865220.dex */
public class RsaCryptService {
    private static final String TAG = "RsaCryptService";
    private static boolean initSuccess;

    public static String doEncrypt(String str) {
        loadSoAndInit();
        try {
            if (TextUtils.isEmpty(str)) {
                Log.w("Log", "待加密串是空！！");
                return "";
            }
            byte[] bytes = str.getBytes("utf-8");
            if (bytes == null || bytes.length == 0) {
                Log.d(TAG, "encrypt: input is null or length is 0");
            }
            String encrypt = encrypt(bytes);
            if (TextUtils.isEmpty(encrypt)) {
                Log.d(TAG, "encrypt: data is null or length is 0");
            }
            return encrypt;
        } catch (Throwable th) {
            Log.w(TAG, "加密串发生异常！" + th.getMessage(), th);
            return "";
        }
    }

    private static native String encrypt(byte[] bArr);

    public static String getRsaVersion() {
        try {
            loadSoAndInit();
            return version();
        } catch (Exception e) {
            e.printStackTrace();
            return "UN_KNOW";
        }
    }

    private static native void init(Context context);

    private static void loadSoAndInit() {
        if (!initSuccess) {
            try {
                b.e(com.wuba.loginsdk.login.b.n, "com_wuba_uc_rsa", a.e);
                init(com.wuba.loginsdk.login.b.n);
                initSuccess = true;
            } catch (Throwable th) {
                Log.d(TAG, "init error", th);
            }
        }
    }

    private static native String version();
}
package com.github.unidbg.utils;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.security.MessageDigest;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.github.unidbg.arm.ARMEmulator;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.AbstractJni;
import com.github.unidbg.linux.android.dvm.BaseVM;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.DvmObject;
import com.github.unidbg.linux.android.dvm.HashMapObject;
import com.github.unidbg.linux.android.dvm.JniFunction;
import com.github.unidbg.linux.android.dvm.StringObject;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.VarArg;
import com.github.unidbg.linux.android.dvm.array.ArrayObject;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.linux.android.dvm.wrapper.DvmInteger;
import com.github.unidbg.memory.Memory;

import okhttp3.HttpUrl;

public class WuBaAppSignUtils extends AbstractJni {

	private static Logger logger = LoggerFactory.getLogger(WuBaAppSignUtils.class);
    // ARM模拟器
    private final ARMEmulator emulator;
    // vm
    private final  VM vm;
    // 载入的模块
//    private final Module module;
    private static final byte[] qro = new byte[0];
    private final DvmClass TTEncryptUtils;

    /**
     * @param soFilePath 需要执行的so文件路径
     * @param classPath  需要执行的函数所在的Java类路径
     * @throws IOException
     */
    public WuBaAppSignUtils(String soFilePath, String classPath) throws IOException {
        // 创建app进程，包名可任意写
        emulator = new AndroidARMEmulator("com.wuba");
        Memory memory = emulator.getMemory();
        // 作者支持19和23两个sdk
        memory.setLibraryResolver(new AndroidResolver(23));
        // 创建DalvikVM，利用apk本身，可以为null1
        vm = ((AndroidARMEmulator) emulator).createDalvikVM(null);
//        vm = ((AndroidARMEmulator) emulator).createDalvikVM(new File("/disk/apps/wubaapp/58client_v10.3.6_785.apk"));
//        vm.setVerbose(true);
        // （关键处1）加载so，填写so的文件路径
        DalvikModule dm = vm.loadLibrary(new File(soFilePath), false);
        // 调用jni
        dm.callJNI_OnLoad(emulator);
//        module = dm.getModule();
        // （关键处2）加载so文件中的哪个类，填写完整的类路径
        TTEncryptUtils = vm.resolveClass(classPath);
        vm.setJni(new JniFunction() {
            @Override
            public int callIntMethod(BaseVM vm, DvmObject<?> dvmObject, String signature, VarArg varArg) {
                if (signature.equals("java/util/HashMap->size()I")) {
                    Map<?, ?> map = (Map<?, ?>) dvmObject.getValue();
                    return map.size();
                }
                throw new UnsupportedOperationException(signature);
            }

            @Override
            public DvmObject<?> callObjectMethod(BaseVM vm, DvmObject<?> dvmObject, String signature, VarArg varArg) {
                if ("java/util/HashMap->keySet()Ljava/util/Set;".equals(signature)) {
                    Map<StringObject, ?> map = (Map<StringObject, ?>) dvmObject.getValue();
                    return new DvmObject<>(vm, vm.resolveClass("java/util/Set"), map.keySet());
                } else if ("java/util/Set->toArray()[Ljava/lang/Object;".equals(signature)) {
                    Set<StringObject> set = (Set<StringObject>) dvmObject.getValue();
                    ArrayObject arrayObject = ArrayObject.newStringArray(vm, set);
                    return arrayObject;
                } else {
                    if ("java/util/HashMap->get(Ljava/lang/Object;)Ljava/lang/Object;".equals(signature)) {
                        Map<StringObject, ByteArray> map = (Map<StringObject, ByteArray>) dvmObject.getValue();
                        StringObject key = varArg.getObject(0);
                        return map.get(key);
                    }
                }
                throw new UnsupportedOperationException(signature);
            }
        });
    }

    /**
     * 调用so文件中的指定函数
     *
     * @param methodSign 传入你要执行的函数信息，需要完整的smali语法格式的函数签名
     * @param args       是即将调用的函数需要的参数
     * @return 函数调用结果
     */
    private String myJni(String methodSign, Object... args) {
        // 使用jni调用传入的函数签名对应的方法（）
        DvmObject<?> dvmObject = TTEncryptUtils.callStaticJniMethodObject(emulator, methodSign, args);
        if (dvmObject == null) return "";
        Object value = dvmObject.getValue();
        if (value == null) return "";
        return dvmObject.getValue().toString();
    }
    /**
     * 关闭模拟器
     *
     * @throws IOException
     */
    private void destroy() throws IOException {
        emulator.close();
        System.out.println("emulator destroy...");
    }
    public static HashMap<String, byte[]> buildMapParams(Map<String, String> map) {
        for (String next : map.keySet()) {
            if (map.get(next) == null) {
                map.put(next, "");
            }
        }
        HashMap<String, byte[]> hashMap = new HashMap();
        for (String next2 : map.keySet()) {
            byte[] bytes = map.get(next2).getBytes(Charset.forName("UTF-8"));
            hashMap.put(next2, bytes);
        }
        return hashMap;
    }
    
    public static String getPhoneSign(String url) throws IOException {
        logger.info(url);
        HttpUrl httpUrl = HttpUrl.parse(url);
        return getSign(httpUrl);
    }
    
    public static String getSign(HttpUrl httpUrl) throws IOException {
        // 1、需要调用的so文件所在路径
        String soFilePath = "/disk/apps/wubaapp/libsignutil.dylib";
        // 2、需要调用函数所在的Java类完整路径，比如a/b/c/d等等，注意需要用/代替.
        String classPath = "com/anjuke/mobile/sign/SignUtil";
        // 3、需要调用函数的函数签名，我这里调用EncryptUtils中的getGameKey方法，由于此方法没有参数列表，所以不需要传入
//        String methodSign = "getSign0()Ljava/lang/String;";
        String methodSign = "getSign0(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Ljava/lang/String;I)Ljava/lang/String;";
        // 输出getGameKey方法调用结果
        WuBaAppSignUtils encryptUtilsJni = new WuBaAppSignUtils(soFilePath, classPath);
        byte[] bytes = (byte[]) null;
        if (bytes == null) bytes = qro;
        String byteParams = md5Params(bytes);
        HashMap<String, byte[]> stringHashMap = buildMapParams(params2Str(httpUrl));
        String nsgin = encryptUtilsJni.myJni(methodSign,
                new StringObject(encryptUtilsJni.vm, httpUrl.url().getPath()),
                new StringObject(encryptUtilsJni.vm, byteParams),
                HashMapObject.newStringMap(encryptUtilsJni.vm, stringHashMap),
                new StringObject(encryptUtilsJni.vm, ""),
                DvmInteger.valueOf(encryptUtilsJni.vm, bytes.length));
        nsgin = StringUtils.substring(nsgin, 0, 36);
        logger.info("结果:[{}]", nsgin);
        encryptUtilsJni.destroy();
        return nsgin;
    }
    
    public static String getnSign(String url,String nsignuuid,String rqBody) throws IOException {
        HttpUrl httpUrl = HttpUrl.parse(url);
        return getSign4Anjuke(httpUrl,nsignuuid,rqBody);
    }
    
    //移动经纪人解密
    public static String getSign4Anjuke(HttpUrl httpUrl,String getSign4Anjuke,String rqBody) throws IOException {
        // 1、需要调用的so文件所在路径
        String soFilePath = "/disk/apps/wubaapp/libsignutil.dylib";
        // 2、需要调用函数所在的Java类完整路径，比如a/b/c/d等等，注意需要用/代替.
        String classPath = "com/anjuke/mobile/sign/SignUtil";
        // 3、需要调用函数的函数签名，我这里调用EncryptUtils中的getGameKey方法，由于此方法没有参数列表，所以不需要传入
        String methodSign = "getSign0(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Ljava/lang/String;I)Ljava/lang/String;";
        // 输出getGameKey方法调用结果
        WuBaAppSignUtils encryptUtilsJni = new WuBaAppSignUtils(soFilePath, classPath);
        byte[] bytes = (byte[]) null;
        if(StringUtils.isNotBlank(rqBody)) {
        	bytes = rqBody.getBytes();
        }
        if (bytes == null) bytes = qro;
        String byteParams = md5Params(bytes);
        Map<String,String> argsMap = params2Str(httpUrl);
        //获取nsign uuid
        HashMap<String, byte[]> stringHashMap = buildMapParams(argsMap);
        String nsgin = encryptUtilsJni.myJni(methodSign,
                new StringObject(encryptUtilsJni.vm, httpUrl.url().getPath()),
                new StringObject(encryptUtilsJni.vm, byteParams),
                HashMapObject.newStringMap(encryptUtilsJni.vm, stringHashMap),
                new StringObject(encryptUtilsJni.vm, getSign4Anjuke),
                DvmInteger.valueOf(encryptUtilsJni.vm, bytes.length));
        logger.info("移动经纪人解密nsgin结果:[{}]",nsgin);
        encryptUtilsJni.destroy();
        return nsgin;
    }
    
    // 密码加密
    public static String encrypt(String info) throws IOException {
        // 1、需要调用的so文件所在路径
        String soFilePath = "/disk/apps/wubaapp/libcom_wuba_uc_rsa.so";
        // 2、需要调用函数所在的Java类完整路径，比如a/b/c/d等等，注意需要用/代替.
        String classPath = "com/wuba/uc/RsaCryptService";
        // 3、需要调用函数的函数签名，我这里调用EncryptUtils中的getGameKey方法，由于此方法没有参数列表，所以不需要传入
        String methodEncryp = "encrypt([B)Ljava/lang/String;";
        // 输出getGameKey方法调用结果
        WuBaAppSignUtils encryptUtilsJni = new WuBaAppSignUtils(soFilePath, classPath);
        //调用native init方法
        String methodInit = "init(Landroid/content/Context)";
        encryptUtilsJni.myJni(methodInit, encryptUtilsJni.vm.resolveClass("android/content/Context").newObject(null));
        byte[] bytes = (byte[]) null;
        if(StringUtils.isNotBlank(info)) {
        	bytes = info.getBytes();
        }
        logger.info("加密接收到的字符为info:[{}]", info);
        String encryption = encryptUtilsJni.myJni(methodEncryp, new ByteArray(encryptUtilsJni.vm, bytes));
        logger.info("移动经纪人加密结果:[{}]", encryption);
        encryptUtilsJni.destroy();
        return encryption;
    }
    
    

    private static String md5Params(byte[] bArr) {
        try {
            if (bArr == null) {
                bArr = new byte[0];
            }
            char[] cArr = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};
            byte[] digest = MessageDigest.getInstance("MD5").digest(bArr);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < digest.length; i++) {
                sb.append(cArr[(digest[i] & 240) >>> 4]);
                sb.append(cArr[digest[i] & 15]);
            }
            return sb.toString();
        } catch (Exception unused) {
            return "";
        }
    }

    /* renamed from: b */
    private static Map<String, String> params2Str(HttpUrl httpUrl) {
        HashMap hashMap = new HashMap();
        for (String str : httpUrl.queryParameterNames()) {
            for (String put : httpUrl.queryParameterValues(str)) {
                hashMap.put(str, put);
            }
        }
        return hashMap;
    }
}
