### ISSUE TITLE
请问如何在上下文之间传参

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#329]
一般场景单台设备肯定对应单个设备ID，会在某个接口获取到设备ID传入
当高并发时设备ID会有很多，这就希望能在vm 或者 moudule 级别传一个参数。在另一个函数去读取，是否有相关的demo呢

**Comment by zhkl0228** [comment]
ThreadLocal应该可以

**Comment by kevinsir** [comment]
额，能不能说的具体一些，我现在用的springboot 单个control 只能使用 sync 来保证同步

**Comment by kevinsir** [comment]
举个例子 callVoidMethodV 这个重写的方法，我如何知道此次是通过哪次请求进来访问的

**Comment by zhkl0228** [comment]
sync同步以后，ThreadLocal的对象是线程共享

**Comment by kevinsir** [comment]
额，我是不希望线程共享。比如我拿到了设备ID 但是第二个线程是另一个设备ID 然而我现在设备ID是在controller 外部的全局变量。这样只能使用sync  来进行同步防止多个线程同时赋值这个设备ID。我还是希望能够在callVoidMethodV  这个方法中如何拿到此次访问的是哪个设备ID 而不是全局变量

**Comment by kevinsir** [comment]
额，我是不希望线程共享。比如我拿到了设备ID 但是第二个线程是另一个设备ID 然而我现在设备ID是在controller 外部的全局变量。这样只能使用sync  来进行同步防止多个线程同时赋值这个设备ID。我还是希望能够在callVoidMethodV  这个方法中如何拿到此次访问的是哪个设备ID 而不是全局变量

**Comment by zhouxy158** [comment]
ThreadLocal能解决你说这种问题

**Comment by kevinsir** [comment]
好的，我去研究一下，感谢
