### ISSUE TITLE
如何在生产环境让日志不输出

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#335]
JNIEnv->CallObject 这些日志可以关闭吗？请问要如何操作，谢谢

**Comment by zhkl0228** [comment]
vm.setVerbose

**Comment by kevinsir** [comment]
谢谢

**Comment by 18463105800** [comment]
请问下下面这种日志如何关闭呢？
XYSignReqeust#constructor,count:0
XYSignRequest#destructor,count:0

**Comment by Epxir** [comment]
unidbg-master\unidbg-android\src\test\resources\log4j.properties文件所有INFO改为OFF

**Comment by baserker2** [comment]
请问UC_HOOK_MEM_WRITE要怎么关掉呢

**Comment by wtx0820** [comment]
> 请问UC_HOOK_MEM_WRITE要怎么关掉呢

能关掉了吗
