### ISSUE TITLE
unidbg单步调试打印寄存器值

### ISSUE THREAD

**Issue by LLYJT** [zhkl0228/unidbg#34]
@zhkl0228
大佬我想问一下能不能打印单步调试中寄存器在内存中的值，就比如某一步调试中，“r0=0xbfffe22c”，打印这个r0寄存器的值

**Comment by zhkl0228** [comment]
可以使用mr0

**Comment by zhkl0228** [comment]
也可以使用mr0 16打印16字节，也可以使用m0xbfffe22c

**Comment by LLYJT** [comment]
这个mr0的api是什么啊，在demo中有没有啊

**Comment by zhkl0228** [comment]
单步调试的命令

**Comment by LLYJT** [comment]
大佬我想问一下，就现在我这边测试，单步调试有一个方法返回有问题，我们想在代码中对它的返回进行修改。然后借鉴你公布的demo中的部分hook方法，确实可以提取到ctx中寄存器的数据，但是hook结束后调试就会报错，因为正常不进入hook不会报错，所以想问下是不是我们的hook缺少什么东西。另外想问一下怎么对hook的方法返回值进行修改，从demo中没有能学习到明确的做法，所以希望大佬能教教我，谢谢
private void hook() throws IOException {
   IHookZz hookZz = HookZz.getInstance(emulator);
        hookZz.enable_arm_arm64_b_branch();
        hookZz.replace(module.base + 0x0000BA20, new ReplaceCallback() {
            @Override
            public HookStatus onCall(Emulator emulator, long originFunction) {
                System.out.println("R0=" + emulator.getContext().getLongArg(0) + ", R0=0x" + Long.toHexString(emulator.getContext().getLongArg(0)));
                
                return HookStatus.RET(emulator, originFunction);
            }
        });
        hookZz.disable_arm_arm64_b_branch();
    }
这个是我仿写的hook方法

**Comment by zhkl0228** [comment]
module.base + 0x0000BA20如果是thumb代码的话，需要+1

**Comment by zhkl0228** [comment]
为了兼容64位的返回值，所以使用long，你可以直接传int就行

**Comment by LLYJT** [comment]
我现在就是想传一个字符串数据作为返回，然后我写了下面这样的hook
     hookZz.replace(module.base + 0x0000BA20 , new ReplaceCallback() {
            @Override
            public HookStatus onCall(Emulator emulator, long originFunction) {
                System.out.println("---------------------------------------------------------------------------------------------------------------");
                System.out.println("R0=" + emulator.getContext().getLongArg(0) + ", R0=0x" + Long.toHexString(emulator.getContext().getLongArg(0)));
                System.out.println("---------------------------------------------------------------------------------------------------------------");
                long currentTimeMillis = System.currentTimeMillis();
                EditableArm32RegisterContext context = emulator.getContext();
                String aaa = "test test test";
                ByteArray bbb = new ByteArray(aaa.getBytes());
                return HookStatus.LR(emulator, vm.addLocalObject(bbb));

            }
        });
我的计划是利用vm.addLocalObject将这段字符串存入内存地址，然后将这个地址返回，想问下这样的操作行得通吗，我这样做是否有什么问题

**Comment by LLYJT** [comment]
大佬我就是用上面描述的这样的hook，在单步调试中已经可以看到R0寄存器的地址被修改了，但是使用mr0的命令却会报错
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.mem_read(Native Method)
	at cn.banny.unidbg.pointer.UnicornPointer.getByteArray(UnicornPointer.java:233)
	at cn.banny.unidbg.arm.AbstractARMDebugger.dumpMemory(AbstractARMDebugger.java:223)
	at cn.banny.unidbg.arm.SimpleARMDebugger.loop(SimpleARMDebugger.java:105)
	at cn.banny.unidbg.arm.AbstractARMDebugger.hook(AbstractARMDebugger.java:151)
	at unicorn.Unicorn.invokeCodeCallbacks(Unicorn.java:143)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:140)
	at com.ss.sys.ces.CMSTest.sign(CMSTest.java:168)
	at com.ss.sys.ces.CMSTest.main(CMSTest.java:87)
报错日志就是这样的

**Comment by zhkl0228** [comment]
返回ByteArray吗？实际你要改的函数返回什么的？

**Comment by LLYJT** [comment]
我这里hook的就是getEnv函数，函数返回应该是c字符串
