### ISSUE TITLE
请问可以设置上下文的时间格式吗。

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#346]
有一个so 我调用了之后生成的时间是 202108260251。但是实际我需要的是 202108261451 是否哪里可以设置上下文的时间戳。因为还涉及到其他加密方式。这个只是字符串的前一部分，还有后一部分跟这部分是关联加密的，所以不好在生成完再改了。
可以vm 或者哪里修改吗。谢谢

**Comment by kevinsir** [comment]
额，发现是 请求 /system/usr/share/zoneinfo/tzdata 这个文件需要怎么解决了呢，能帮忙看一下吗

**Comment by Pr0214** [comment]
你好，可以附带一下样本
