### ISSUE TITLE
32位下为什么做高16位填充

### ISSUE THREAD

**Issue by cuicuicuinice** [zhkl0228/unidbg#347]
不知道是bug，还是个人能力问题，真的没理解接下来这块处理含义，之所以产生疑问，是因为在【 HookStatus.LR】的时候，已经影响返回值结果，导致结果不正确。

在【unidbg-api\src\main\java\com\github\unidbg\AbstractEmulator.java】第374行：
![image](https://user-images.githubusercontent.com/34976688/131211417-4591c10d-ef5a-40a4-b932-3ae5fc41dfc5.png)
【 ((r1.intValue() & 0xffffffffL) << 32)】这块代码，我的理解是做高16位填充，如果“r1”为0没任何问题（如果r1为0，这一步似乎也没看出有啥意义诶............），***但是再连续hook函数的时候，“r1没有做清零操作”***，“r1”的值会导致高16位会被填充为其他值，最后r0和r1一合并，值就变成非预期的值。

本身【r0.intValue() & 0xffffffffL】就算是扩充为32位了，高位全部为0，似乎也不许对高位做什么操作。
所以不太理解这里的含义，是有什么特殊含义吗？但是这样的操作，确实产生了非预期行为。
最后的reture，如果直接改成【return r0.intValue() & 0xffffffffL;】，反而是符合预期结果.............

**Comment by zhkl0228** [comment]
有示例代码吗？得运行看看

**Comment by cuicuicuinice** [comment]
> 有示例代码吗？得运行看看

![image](https://user-images.githubusercontent.com/34976688/131212425-4397c1bd-3f87-419b-af19-893218d8566d.png)
这里hook两个函数，

**Comment by cuicuicuinice** [comment]
> 有示例代码吗？得运行看看

![image](https://user-images.githubusercontent.com/34976688/131212440-44972bf9-37c2-4cb0-b7d6-e54bfbba4077.png)
这里hook了2个函数，第一个返回值是29，第二个返回值99，

接下来从上到下连续调用两个函数，
第一个调用有一r1是0，所以返回值正确，是29.
第二个调用，由于r1被第一个函数修改过，没有清零，导致第二个函数返回值是个很大的数，不是预期的99

**Comment by zhkl0228** [comment]
要有代码及so运行才好沟通

**Comment by cuicuicuinice** [comment]
理解错了  并不是啥高地位填充 .....打脸

**Comment by cuicuicuinice** [comment]
> 要有代码及so运行才好沟通
[测试so和java.zip](https://github.com/zhkl0228/unidbg/files/7071912/so.java.zip)

**Comment by cuicuicuinice** [comment]
> 要有代码及so运行才好沟通

[测试so和java.zip](https://github.com/zhkl0228/unidbg/files/7071915/so.java.zip)
