### ISSUE TITLE
exit with code: 127怎么解决

### ISSUE THREAD

**Issue by CrazyFireGame** [zhkl0228/unidbg#351]
case 11：
backend.reg_write(ArmConst.UC_ARM_REG_R0, execve(emulator));
要怎么给返回值，return不好使。
返回case248 exit with code: 127

**Comment by CrazyFireGame** [comment]
> case 11：
> backend.reg_write(ArmConst.UC_ARM_REG_R0, execve(emulator));
> 要怎么给返回值，return不好使。
> 返回case248 exit with code: 127

**Comment by Pr0214** [comment]
你好，可以通过hook的方式解决
