### ISSUE TITLE
请教各位大佬getFilesDir怎么搞

### ISSUE THREAD

**Issue by gap1994** [zhkl0228/unidbg#356]
问题：GetMethodID(java/io/File.getAbsolutePath()Ljava/lang/String;)这里还正常执行，后面就空值了
![image](https://user-images.githubusercontent.com/9198081/132618090-a8cfe537-f235-47a5-bdb0-353929f3a07a.png)

我这么写出错的：
```
@Override
    public DvmObject callObjectMethodV(BaseVM vm, DvmObject dvmObject, String signature, VaList vaList) {
switch (signature) {
case "android/app/Application->getFilesDir()Ljava/io/File;":
                return vm.resolveClass("java/io/File").newObject(null);
}
}
```

**Comment by Andyworker** [comment]
这个可以使用使用`IOResolver`类来继承，把resolve对象实现了就行。

---

**实例代码如下：**


```java
public class Crypto extends AbstractJni implements IOResolver<AndroidFileIO> {
    private final AndroidEmulator emulator;
    private final DvmClass cNative;
    private VM vm;

    @Override
    public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
        System.out.println("Open Path with " + pathname);
        if (pathname.equals("/proc/self/cmdline")) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname, "".getBytes(StandardCharsets.UTF_8)));
        }
        return null;
    }
}
```

**Comment by gap1994** [comment]
> 这个可以使用使用`IOResolver`类来继承，把resolve对象实现了就行。
> 
> **实例代码如下：**
> 
> ```java
> public class Crypto extends AbstractJni implements IOResolver<AndroidFileIO> {
>     private final AndroidEmulator emulator;
>     private final DvmClass cNative;
>     private VM vm;
> 
>     @Override
>     public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
>         System.out.println("Open Path with " + pathname);
>         if (pathname.equals("/proc/self/cmdline")) {
>             return FileResult.success(new ByteArrayFileIO(oflags, pathname, "".getBytes(StandardCharsets.UTF_8)));
>         }
>         return null;
>     }
> }
> ```

大佬，有没有群可以让我加一下，自己学太难了，非常感谢你的帮忙

**Comment by Andyworker** [comment]
> > 这个可以使用使用`IOResolver`类来继承，把resolve对象实现了就行。
> > **实例代码如下：**
> > ```java
> > public class Crypto extends AbstractJni implements IOResolver<AndroidFileIO> {
> >     private final AndroidEmulator emulator;
> >     private final DvmClass cNative;
> >     private VM vm;
> > 
> >     @Override
> >     public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
> >         System.out.println("Open Path with " + pathname);
> >         if (pathname.equals("/proc/self/cmdline")) {
> >             return FileResult.success(new ByteArrayFileIO(oflags, pathname, "".getBytes(StandardCharsets.UTF_8)));
> >         }
> >         return null;
> >     }
> > }
> > ```
> 
> 大佬，有没有群可以让我加一下，自己学太难了，非常感谢你的帮忙

这块确实很难，可以目前既没有文档也没有一个交流群，所以只能多看看源码，我觉得大家可以组织在一起，想办法写个文档吧

**Comment by Pr0214** [comment]
你好，这里是methodID不匹配带来的问题，而非上述IO重定向的问题

**Comment by gap1994** [comment]
> 你好，这里是methodID不匹配带来的问题，而非上述IO重定向的问题

 我到现在都不明白这个需要怎么解决，请问要用什么方式处理呢

**Comment by Pr0214** [comment]
你好，可以看过往的issue，或者看这篇内容 https://t.zsxq.com/2byjIMr
