### ISSUE TITLE
ByteArray对象调用GetObjectClass方法失败

### ISSUE THREAD

**Issue by xjohjrdy** [zhkl0228/unidbg#36]
[GetObjectClass方法模拟实现](https://github.com/zhkl0228/unidbg/blob/3d103c9d7e81b5efc54ac6e56b4ab360c057baec/src/main/java/cn/banny/unidbg/linux/android/dvm/DalvikVM.java#L222)

so源码：
```c
jbyteArray array = (*env)->NewByteArray(env,10);
jclass clazz = (*env)->GetObjectClass(env,array);
```
使用unidbg调用编译后的so时，执行到GetObjectClass时发生错误，`dvmObject.objectType = null`，请问这种情况该怎么处理？

![image](https://user-images.githubusercontent.com/45351539/61514350-75072500-aa32-11e9-9036-8af362bb873c.png)

**Comment by zhkl0228** [comment]
GetObjectClass对ByteArray正常应该返回什么？

**Comment by xjohjrdy** [comment]
![image](https://user-images.githubusercontent.com/45351539/61579900-f3042280-ab3d-11e9-8c20-9b9d62ba75a0.png)
正常情况下，如java/lang/Long 对象调用GetObjectClass时，返回的是globalObjectMap中对应的hash值(key)。 

当ByteArray调用这个方法的时候，我尝试返回 `vm.resolveClass("[B").hashCode()`，导致了更多的错误。。。

`cn.banny.unidbg.linux.android.dvm.array.ByteArray` 与其他DvmObject不太一样，其他继承DvmObject的类型，初始化的时候都要传入vm，设置objectType。`cn.banny.unidbg.linux.android.dvm.array.ByteArray` 继承了`cn.banny.unidbg.linux.android.dvm.array.BaseArray` ，BaseArray中直接将objectType设置为null。

**Comment by zhkl0228** [comment]
测试用例方便发出来吗

**Comment by xjohjrdy** [comment]
搞定了，还是强制返回`[B`的hashCode，只是我调用的这个so有很多坑，有太多java的方法需要模拟实现。
unidbg很好很强大！

**Comment by zhkl0228** [comment]
如果unidbg有bug的话，还望有空的时候提个PR
