### ISSUE TITLE
某梆加壳，unidbg so loader 失败

### ISSUE THREAD

**Issue by Lv9S** [zhkl0228/unidbg#369]
`public class MissFresh extends AbstractJni {

    private final AndroidEmulator emulator;
    private final VM vm;
    private final Module module;

    public MissFresh()  {
        emulator = AndroidEmulatorBuilder.for32Bit().setProcessName("cn.missfresh.application")
                .build();
        final Memory memory = emulator.getMemory(); // 模拟器的内存操作接口
        memory.setLibraryResolver(new AndroidResolver(23)); // 设置系统类库解析
        vm = emulator.createDalvikVM(new File("unidbg-android/src/main/resources/app/meiriyouxian_v9.9.13.apk"));
        vm.setVerbose(true);
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/main/resources/binaries/libsign.so"),true);

        module = dm.getModule();

        vm.setJni(this);
        dm.callJNI_OnLoad(emulator);

    }

    public static void main(String[] args) {
        MissFresh missFresh = new MissFresh();
    }
`
![image](https://user-images.githubusercontent.com/22839142/136538755-eaed55aa-c1d6-4e7e-be00-9ea6da0b698f.png)

**Comment by Pr0214** [comment]
是你的问题，你初始化没做好

**Comment by Lv9S** [comment]
系统文件补一下就ok
