### ISSUE TITLE
关于 _system_property_get__的模拟

### ISSUE THREAD

**Issue by JiangJianCong** [zhkl0228/unidbg#37]
请问作者如果底层用__system_property_get来读取信息，能否进行模拟？

**Comment by zhkl0228** [comment]
配合hook模拟

**Comment by JiangJianCong** [comment]
> 配合hook模拟

ok，以前的测试用例有参考的么

**Comment by zhkl0228** [comment]
SystemPropertyHook

**Comment by JiangJianCong** [comment]
> SystemPropertyHook

有点没看懂怎么用，在测试用例那一边新建一个SystemPropertyHook对象用吗？能不能说一下怎么用

**Comment by zhkl0228** [comment]
memory.addHookListener(systemPropertyHook);
setPropertyProvider(SystemPropertyProvider propertyProvider);
