### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff   ava.lang.ClassNotFoundException: android.app.ActivityThread

### ISSUE THREAD

**Issue by geekplus001** [zhkl0228/unidbg#381]
报错下半部分
![image](https://user-images.githubusercontent.com/14014551/142555823-c64736a2-ac68-4891-bcaf-8470ad3a0a89.png)

上半部分

![image](https://user-images.githubusercontent.com/14014551/142555871-734f703d-eee5-4636-af44-11538c1fb1b1.png)

代码
![image](https://user-images.githubusercontent.com/14014551/142555911-eee4f4d5-72f2-42e4-a77d-09a48ef62a7c.png)

**Comment by geekplus001** [comment]
不知道做了什么报错变了。。变成这样：
java.lang.UnsupportedOperationException: android/app/ActivityThread->currentPackageName()Ljava/lang/String;

**Comment by thouger** [comment]
相同的问题，不知道要补什么环境
