### ISSUE TITLE
 [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:64) - Read memory failed: address=0x63bb9042, size=1, value=0x0, PC=RX@0x40a49cec

### ISSUE THREAD

**Issue by heckerstone** [zhkl0228/unidbg#393]
so 调用native方法发生上述异常，望大侠不吝赐教。
java代码：
package com.heckerstone.soul.libsoulpower;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.Module;
import com.github.unidbg.arm.HookStatus;
import com.github.unidbg.arm.backend.Backend;
import com.github.unidbg.arm.backend.EventMemHook;
import com.github.unidbg.arm.backend.UnHook;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.hook.HookContext;
import com.github.unidbg.hook.ReplaceCallback;
import com.github.unidbg.hook.hookzz.Dobby;
import com.github.unidbg.hook.hookzz.HookZz;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.pointer.UnidbgPointer;
import com.github.unidbg.virtualmodule.android.AndroidModule;
import com.sun.media.jfxmedia.logging.Logger;
import unicorn.Arm64Const;
import unicorn.ArmConst;
import unicorn.Hook;
import unicorn.UnicornConst;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class LibSoulpower extends AbstractJni implements IOResolver{
    private final AndroidEmulator emulator;
    private final VM vm;
    private final Module module;
    //    private final String className = "cn.soulapp.android.soulpower.utils.AESUtil";
    private final String className = "cn/soulapp/android/soulpower/imlib/ImEncryptUtils";
    private final String deviceClassName = "cn.soulapp.android.client.component.middle.platform.utils.DeviceUtils";
    private final DvmClass dvmClass;
    private final DvmClass deviceUtilsClass;
    private static String desKey = "789!@#xswEDCzxcv";
    public DvmClass cNative;

    static{
//        Logger.getLogger("com.github.unidbg.linux.ARM32SyscallHandler").setLevel(Level.DEBUG);
//        Logger.getLogger("com.github.unidbg.unix.UnixSyscallHandler").setLevel(Level.DEBUG);
//        Logger.getLogger("com.github.unidbg.AbstractEmulator").setLevel(Level.DEBUG);
//        Logger.getLogger("com.github.unidbg.linux.android.dvm.DalvikVM").setLevel(Level.DEBUG);
//        Logger.getLogger("com.github.unidbg.linux.android.dvm.BaseVM").setLevel(Level.DEBUG);
//        Logger.getLogger("com.github.unidbg.linux.android.dvm").setLevel(Level.DEBUG);

    }

    public LibSoulpower() {

        emulator = AndroidEmulatorBuilder
                .for32Bit()
                .setRootDir(new File("target/rootfs"))
                .build();
//        emulator = builder.setRootDir(new File("target/rootfs")).build();
        // 获取模拟器的内存操作接口
        final Memory memory = emulator.getMemory();
        // 设置系统类库解析
        memory.setLibraryResolver(new AndroidResolver(23));
        // 绑定重定向
        emulator.getSyscallHandler().setVerbose(true);
        vm = emulator.createDalvikVM(new File("D:\\google_download\\unidbg-master2\\unidbg-master\\unidbg-so\\src\\main\\resources\\so\\soul\\411.apk"));
        new AndroidModule(emulator, vm).register(memory);
//        emulator.attach().addBreakPoint(0x40328714);
        //获取导出函数地址
        cNative = vm.resolveClass("cn.soulapp.android.ui.main.MainActivity");
//        hookAndEditRV();
//        patch();
        vm.setJni(this);
        vm.setVerbose(true); // 打印日志

        DalvikModule incite = vm.loadLibrary(new File("D:\\google_download\\unidbg-master2\\unidbg-master\\unidbg-android\\src\\test\\resources\\example_binaries\\armeabi-v7a\\libIncite.so"), true); // 加载so到虚拟内存
//        patch2();
        DalvikModule dm = vm.loadLibrary(new File("D:\\google_download\\unidbg-master2\\unidbg-master\\unidbg-so\\src\\main\\resources\\so\\soul\\libsoulpower.so"), true); // 加载so到虚拟内存
        //获取本SO模块的句柄,后续需要用它
        module = dm.getModule();

        //查找so中函数名
        dm.callJNI_OnLoad(emulator); // 调用JNI OnLoad
        dvmClass = vm.resolveClass(className);
        deviceUtilsClass = vm.resolveClass(deviceClassName);
    }

    /**
     * arg0 = cn.soulapp.android.SoulApp@6464fbd
     * 	arg1 = 1642073776
     * 	arg2 = /experiment/listConfig?bi=["17e53395fed",-1,"google","Android",25,"7.1.1","Nexus6P","Huawei",560,"1440*2392","yyb","DISCONNECT","zh_CN_#Hans"]&bik=32755
     * 	arg3 = cn.soulapp.android/b25cff Mozilla/5.0 (Linux; Android 7.1.1; Nexus 6P Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.135 Mobile Safari/537.361000000317e53395ffd4.1.1Ydrt4cKaCFEDANO8Ecgcc/0XTmV4dXMgNlAkEoaEF4QPcw__8acdd854a9f93719a91812dab8d29bee
     *getCs()
     */
    public void soulpowerH(){
        //0xb6080
        List<Object> list = new ArrayList<>(10);
        list.add(vm.getJNIEnv());
        DvmObject<?> cnative = cNative.newObject(null);
        list.add(cnative.hashCode());
        DvmObject<?> obj = vm.resolveClass("android/content/Context").newObject(null);
        list.add(vm.addLocalObject(obj));
        int arg1 = (int)(System.currentTimeMillis()/1000);
        String arg2 = "/experiment/listConfig?bi=[\"17e67ae411b\",-1,\"google\",\"Android\",25,\"7.1.1\",\"Nexus6P\",\"Huawei\",560,\"1440*2392\",\"yyb\",\"DISCONNECT\",\"zh_CN_#Hans\"]&bik=32755";
        String arg3 = "cn.soulapp.android/b25cff Mozilla/5.0 (Linux; Android 7.1.1; Nexus 6P Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.135 Mobile Safari/537.361000000317e53395ffd4.1.1Ydrt4cKaCFEDANO8Ecgcc/0XTmV4dXMgNlAkEoaEF4QPcw__8acdd854a9f93719a91812dab8d29bee";
        list.add(arg1);
        list.add(vm.addLocalObject(new StringObject(vm,arg2)));
//        list.add(vm.addLocalObject(new StringObject(vm,new StringBuilder().toString())));
        list.add(vm.addLocalObject(new StringObject(vm,arg3)));
        Number number = module.callFunction(emulator,0xb6080,list.toArray());
        System.out.println("soulpowerH-->getCs()====="+vm.getObject(number.intValue()).getValue().toString());
    }

    public void patch(){
        emulator.getBackend().hook_add_new(new EventMemHook() {

            @Override
            public boolean hook(Backend backend, long address, int size, long value, Object user, UnmappedType unmappedType) {
                System.out.println("fuck patch ");
                System.out.println(Long.toHexString(address));
                emulator.getBackend().mem_map(address / 0x1000 * 0x1000,0x1000, UnicornConst.UC_PROT_ALL);
                byte [] rep = new byte[]{0x00, (byte) 0xF0,0x20, (byte) 0xE3};
                emulator.getBackend().mem_write(address, rep);
                return true;
            }

//            @Override
//            public boolean hook(Backend backend, long address, int size, long value, Object user) {
//                System.out.println("fuck patch ");
//                System.out.println(Long.toHexString(address));
//                emulator.getBackend().mem_map(address / 0x1000 * 0x1000,0x1000, UnicornConst.UC_PROT_ALL);
//                emulator.getBackend().mem_write(address, new byte[4]);
//                return true;
//            }
            @Override
            public void onAttach(UnHook unHook) {
            }
            @Override
            public void detach() {
                throw new UnsupportedOperationException();
            }
        }, UnicornConst.UC_HOOK_MEM_READ_UNMAPPED | UnicornConst.UC_HOOK_MEM_WRITE_UNMAPPED | UnicornConst.UC_HOOK_MEM_FETCH_UNMAPPED, null);
    }

    @Override
    public byte getStaticByteField(BaseVM vm, DvmClass dvmClass, String signature) {
        switch (signature) {
            case "cn/soulapp/android/soulpower/InfoGather->aa:B": {
                return 0;
            }
        }
        return super.getStaticByteField(vm, dvmClass, signature);
    }

    @Override
    public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        switch (signature){
            case "cn/soulapp/android/soulpower/SoulPowerful->getSoulPowerfulString()Ljava/lang/String;":{
                return new StringObject(vm,"ss");
            }
        }
        return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);
    }

    @Override
    public DvmObject<?> getStaticObjectField(BaseVM vm, DvmClass dvmClass, String signature) {
        switch (signature){
            case "android/os/Build$VERSION->RELEASE:Ljava/lang/String;":{
                return new StringObject(vm,"6.1.1");
            }
            case "android/os/Build$VERSION->SDK:Ljava/lang/String;":{
                return new StringObject(vm,"23");
            }
        }
        return super.getStaticObjectField(vm, dvmClass, signature);
    }

    @Override
    public FileResult resolve(Emulator emulator, String pathname, int i) {
        System.out.println("lilac Path:" + pathname);
        return null;
    }

    public static void main(String[] args) {
        LibSoulpower lsl = new LibSoulpower();
        lsl.soulpowerH();
    }

}
[libsoulpower.so.zip](https://github.com/zhkl0228/unidbg/files/7886831/libsoulpower.so.zip)

app为：soul-4.1.1 版本

**Comment by Freek3r** [comment]
请问师傅解决了吗？
