### ISSUE TITLE
Some weird issues with calling native method on an sgmain.so lib

### ISSUE THREAD

**Issue by SiriusED** [zhkl0228/unidbg#399]
Trying to call native method on .so library and getting some weird errors.
Tried three deferent library versions, all have the same error... Seems like library loaded successfully itself, but somehow it can't compute the things, I have been reading some relative articles about this library and I guess I do all correctly in my code but still have errors, maybe someone knows how to successfully call `doCommonNative` method and pass arguments, because seems like arguments are the issue here, look like this `SecException` is an internal library's exception and it can be because I pass wrong arguments\types or something else on my side is wrong

Here is the code I call the method:
![image](https://user-images.githubusercontent.com/13561846/154245655-561bd117-ef69-4a17-8515-a3aa071036c4.png)

Also in my `resolve` method I have paths like `D:\Java\....\ab914f43b8296c2c.lock` and some same `.txt` file so I just create them like this:

```
if (pathname.contains(".lock") || pathname.contains(".txt")) {
            String pathReplaced = pathname.replace("/", "\\");
            File newFile = new File(pathReplaced);
            try {
                boolean success = newFile.createNewFile();
            }
            catch (Exception ex) {
                log(ex.getMessage());
            }
            return FileResult.success(new SimpleFileIO(oflags, newFile, FilenameUtils.getPath(pathReplaced)));
}
```

Didn't really understand what to do when I have path of the folder in my `resolve` method, I just ignore paths when it's folder, maybe this is the issue? Please help.

**Comment by Jun-bit** [comment]
Have you got the signature? I feel that there is something wrong with the calculated signature.
