### ISSUE TITLE
NPE when argument is null

### ISSUE THREAD

**Issue by rasentry** [zhkl0228/unidbg#404]
https://github.com/zhkl0228/unidbg/blob/d8ecf25ed496537af577552941ac6eb1f71e9c9f/unidbg-android/src/main/java/com/github/unidbg/linux/android/dvm/JValueList.java#L22
```
UnidbgPointer ptr = (UnidbgPointer) pointer.getPointer(0);
```
here, ptr is null when argument is null

**Comment by zhkl0228** [comment]
master version fixed

**Comment by rasentry** [comment]
thanks
