### ISSUE TITLE
请问一下，这个是因为我没补全吗？结果总是null，如果要补全，应该从哪里下手。感谢大佬赐教

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#425]
先上日志
`[10:47:34 949]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:470) - libtiny.so load dependency libmediandk.so failed
[10:47:34 970]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=localeconv, type=function, size=0] is missing relocationAddr=RW@0x4007ae88[libtiny.so]0x7ae88, offset=0x0
[10:47:34 972]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=__read_chk, type=function, size=0] is missing relocationAddr=RW@0x4007aef0[libtiny.so]0x7aef0, offset=0x0
[10:47:34 972]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=AMediaDrm_createByUUID, type=function, size=0] is missing relocationAddr=RW@0x4007af30[libtiny.so]0x7af30, offset=0x0
[10:47:34 973]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=AMediaDrm_getPropertyByteArray, type=function, size=0] is missing relocationAddr=RW@0x4007af34[libtiny.so]0x7af34, offset=0x0
[10:47:34 973]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=AMediaDrm_release, type=function, size=0] is missing relocationAddr=RW@0x4007af38[libtiny.so]0x7af38, offset=0x0
[10:47:34 973]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=wcstoll, type=function, size=0] is missing relocationAddr=RW@0x4007af7c[libtiny.so]0x7af7c, offset=0x0
[10:47:34 973]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=wcstoull, type=function, size=0] is missing relocationAddr=RW@0x4007af80[libtiny.so]0x7af80, offset=0x0
[10:47:34 973]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:206) - [libtiny.so]symbol ElfSymbol[name=wcstof, type=function, size=0] is missing relocationAddr=RW@0x4007af84[libtiny.so]0x7af84, offset=0x0
[10:47:35 038]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]localeconv symbol is missing before init relocationAddr=RW@0x4007ae88[libtiny.so]0x7ae88
[10:47:35 039]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]__read_chk symbol is missing before init relocationAddr=RW@0x4007aef0[libtiny.so]0x7aef0
[10:47:35 039]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]AMediaDrm_createByUUID symbol is missing before init relocationAddr=RW@0x4007af30[libtiny.so]0x7af30
[10:47:35 039]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]AMediaDrm_getPropertyByteArray symbol is missing before init relocationAddr=RW@0x4007af34[libtiny.so]0x7af34
[10:47:35 039]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]AMediaDrm_release symbol is missing before init relocationAddr=RW@0x4007af38[libtiny.so]0x7af38
[10:47:35 039]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]wcstoll symbol is missing before init relocationAddr=RW@0x4007af7c[libtiny.so]0x7af7c
[10:47:35 039]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]wcstoull symbol is missing before init relocationAddr=RW@0x4007af80[libtiny.so]0x7af80
[10:47:35 045]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:129) - [libtiny.so]wcstof symbol is missing before init relocationAddr=RW@0x4007af84[libtiny.so]0x7af84
JNIEnv->FindClass(com/xingin/tiny/internal/Hybrid) was called from RX@0x40006a3f[libtiny.so]0x6a3f
JNIEnv->RegisterNatives(com/xingin/tiny/internal/Hybrid, unidbg@0xbffff700, 1) was called from RX@0x40006a17[libtiny.so]0x6a17
RegisterNative(com/xingin/tiny/internal/Hybrid, callNative(I[Ljava/lang/Object;)Ljava/lang/Object;, RX@0x400057a5[libtiny.so]0x57a5)
JNIEnv->FindClass(android/content/Intent) was called from RX@0x4005f5b1[libtiny.so]0x5f5b1
JNIEnv->NewGlobalRef(class android/content/Intent) was called from RX@0x4005f5c1[libtiny.so]0x5f5c1
JNIEnv->GetMethodID(android/content/Intent.<init>(Ljava/lang/String;)V) => 0xc14c8f0a was called from RX@0x4005f673[libtiny.so]0x5f673
JNIEnv->GetMethodID(android/content/Intent.getIntExtra(Ljava/lang/String;I)I) => 0xddd1beeb was called from RX@0x4005f78f[libtiny.so]0x5f78f
JNIEnv->GetMethodID(android/content/Intent.getBooleanExtra(Ljava/lang/String;Z)Z) => 0xd9395d74 was called from RX@0x4005f861[libtiny.so]0x5f861
JNIEnv->GetMethodID(android/content/Intent.addCategory(Ljava/lang/String;)Landroid/content/Intent;) => 0xffb4b930 was called from RX@0x4005fc0d[libtiny.so]0x5fc0d
JNIEnv->FindClass(android/content/Context) was called from RX@0x40060001[libtiny.so]0x60001
JNIEnv->NewGlobalRef(class android/content/Context) was called from RX@0x40060011[libtiny.so]0x60011
JNIEnv->GetMethodID(android/content/Context.getPackageManager()Landroid/content/pm/PackageManager;) => 0x3acc78f0 was called from RX@0x4006042f[libtiny.so]0x6042f
JNIEnv->GetMethodID(android/content/Context.getContentResolver()Landroid/content/ContentResolver;) => 0x3fe770ea was called from RX@0x40060327[libtiny.so]0x60327
JNIEnv->GetMethodID(android/content/Context.getSystemService(Ljava/lang/String;)Ljava/lang/Object;) => 0x545bcf2d was called from RX@0x40060485[libtiny.so]0x60485
JNIEnv->GetMethodID(android/content/Context.getSharedPreferences(Ljava/lang/String;I)Landroid/content/SharedPreferences;) => 0xa0a12d1f was called from RX@0x400604dd[libtiny.so]0x604dd
JNIEnv->GetMethodID(android/content/Context.checkPermission(Ljava/lang/String;II)I) => 0x9daa2205 was called from RX@0x40060b65[libtiny.so]0x60b65
JNIEnv->FindClass(com/xingin/tiny/internal/Hybrid) was called from RX@0x40060d31[libtiny.so]0x60d31
JNIEnv->NewGlobalRef(class com/xingin/tiny/internal/Hybrid) was called from RX@0x40060d41[libtiny.so]0x60d41
JNIEnv->GetStaticMethodID(com/xingin/tiny/internal/Hybrid.callJava(I[Ljava/lang/Object;)Ljava/lang/Object;) => 0x5d3c8a71 was called from RX@0x40060fdd[libtiny.so]0x60fdd
JNIEnv->FindClass(java/lang/Class) was called from RX@0x400613d5[libtiny.so]0x613d5
JNIEnv->NewGlobalRef(class java/lang/Class) was called from RX@0x400613e3[libtiny.so]0x613e3
JNIEnv->FindClass(java/lang/Object) was called from RX@0x40061511[libtiny.so]0x61511
JNIEnv->NewGlobalRef(class java/lang/Object) was called from RX@0x4006151d[libtiny.so]0x6151d
JNIEnv->FindClass(java/util/Collection) was called from RX@0x4006197f[libtiny.so]0x6197f
JNIEnv->GetMethodID(java/util/Collection.iterator()Ljava/util/Iterator;) => 0xecb22abf was called from RX@0x40061a25[libtiny.so]0x61a25
JNIEnv->FindClass(java/util/Iterator) was called from RX@0x40061e37[libtiny.so]0x61e37
JNIEnv->GetMethodID(java/util/Iterator.hasNext()Z) => 0x74f5adeb was called from RX@0x40061c61[libtiny.so]0x61c61
JNIEnv->GetMethodID(java/util/Iterator.next()Ljava/lang/Object;) => 0xc9be0fcf was called from RX@0x40061ed7[libtiny.so]0x61ed7
JNIEnv->FindClass(java/util/Map) was called from RX@0x40062619[libtiny.so]0x62619
JNIEnv->NewGlobalRef(class java/util/Map) was called from RX@0x40062629[libtiny.so]0x62629
JNIEnv->GetMethodID(java/util/Map.size()I) => 0x95e5057a was called from RX@0x40062799[libtiny.so]0x62799
JNIEnv->GetMethodID(java/util/Map.get(Ljava/lang/Object;)Ljava/lang/Object;) => 0x7f03ab0a was called from RX@0x400622f1[libtiny.so]0x622f1
JNIEnv->GetMethodID(java/util/Map.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;) => 0x6fb34d67 was called from RX@0x400627d1[libtiny.so]0x627d1
JNIEnv->GetMethodID(java/util/Map.remove(Ljava/lang/Object;)Ljava/lang/Object;) => 0xc7b2e6f2 was called from RX@0x400625a1[libtiny.so]0x625a1
JNIEnv->GetMethodID(java/util/Map.keySet()Ljava/util/Set;) => 0x24c91734 was called from RX@0x40062ab7[libtiny.so]0x62ab7
JNIEnv->FindClass(java/util/HashMap) was called from RX@0x40062c75[libtiny.so]0x62c75
JNIEnv->NewGlobalRef(class java/util/HashMap) was called from RX@0x40062c85[libtiny.so]0x62c85
JNIEnv->GetMethodID(java/util/HashMap.<init>()V) => 0xa7b3cd64 was called from RX@0x40062e35[libtiny.so]0x62e35
JNIEnv->FindClass(android/content/pm/PackageInfo) was called from RX@0x400635dd[libtiny.so]0x635dd
JNIEnv->NewGlobalRef(class android/content/pm/PackageInfo) was called from RX@0x400635ed[libtiny.so]0x635ed
JNIEnv->GetFieldID(android/content/pm/PackageInfo.packageName Ljava/lang/String;) => 0x20518ffc was called from RX@0x4006393d[libtiny.so]0x6393d
JNIEnv->GetFieldID(android/content/pm/PackageInfo.versionName Ljava/lang/String;) => 0xbcc0232a was called from RX@0x40063745[libtiny.so]0x63745
JNIEnv->GetFieldID(android/content/pm/PackageInfo.firstInstallTime J) => 0x215b0bd1 was called from RX@0x400637f9[libtiny.so]0x637f9
JNIEnv->GetFieldID(android/content/pm/PackageInfo.lastUpdateTime J) => 0xb7c07d45 was called from RX@0x400639f1[libtiny.so]0x639f1
JNIEnv->GetFieldID(android/content/pm/PackageInfo.versionCode I) => 0x41c3e70b was called from RX@0x40063b73[libtiny.so]0x63b73
JNIEnv->GetFieldID(android/content/pm/PackageInfo.applicationInfo Landroid/content/pm/ApplicationInfo;) => 0xb287dbb2 was called from RX@0x40063143[libtiny.so]0x63143
JNIEnv->FindClass(android/content/pm/PackageManager) was called from RX@0x400642a7[libtiny.so]0x642a7
JNIEnv->GetMethodID(android/content/pm/PackageManager.getPackageInfo(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;) => 0x3bca8377 was called from RX@0x40063d77[libtiny.so]0x63d77
JNIEnv->GetMethodID(android/content/pm/PackageManager.queryIntentActivities(Landroid/content/Intent;I)Ljava/util/List;) => 0x4d4c5819 was called from RX@0x400643eb[libtiny.so]0x643eb
JNIEnv->GetMethodID(android/content/pm/PackageManager.getInstallerPackageName(Ljava/lang/String;)Ljava/lang/String;) => 0xed3a354c was called from RX@0x4006458b[libtiny.so]0x6458b
JNIEnv->FindClass(android/content/pm/ApplicationInfo) was called from RX@0x400650d3[libtiny.so]0x650d3
JNIEnv->NewGlobalRef(class android/content/pm/ApplicationInfo) was called from RX@0x400650e3[libtiny.so]0x650e3
JNIEnv->GetFieldID(android/content/pm/ApplicationInfo.targetSdkVersion I) => 0x74a55c91 was called from RX@0x400654bd[libtiny.so]0x654bd
JNIEnv->GetFieldID(android/content/pm/ApplicationInfo.sourceDir Ljava/lang/String;) => 0x304a6a5 was called from RX@0x400652c3[libtiny.so]0x652c3
JNIEnv->GetFieldID(android/content/pm/ApplicationInfo.dataDir Ljava/lang/String;) => 0xef83d1b4 was called from RX@0x400653ad[libtiny.so]0x653ad
JNIEnv->GetMethodID(android/content/pm/ApplicationInfo.loadLabel(Landroid/content/pm/PackageManager;)Ljava/lang/CharSequence;) => 0xe6b638b6 was called from RX@0x400659c7[libtiny.so]0x659c7
JNIEnv->FindClass(android/provider/Settings$Global) was called from RX@0x4006617d[libtiny.so]0x6617d
JNIEnv->NewGlobalRef(class android/provider/Settings$Global) was called from RX@0x4006618d[libtiny.so]0x6618d
JNIEnv->GetStaticMethodID(android/provider/Settings$Global.getString(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;) => 0x11d9f943 was called from RX@0x400663e7[libtiny.so]0x663e7
JNIEnv->GetStaticMethodID(android/provider/Settings$Global.getInt(Landroid/content/ContentResolver;Ljava/lang/String;)I) => 0x49fead70 was called from RX@0x4006646f[libtiny.so]0x6646f
JNIEnv->FindClass(android/provider/Settings$Secure) was called from RX@0x40066a2b[libtiny.so]0x66a2b
JNIEnv->NewGlobalRef(class android/provider/Settings$Secure) was called from RX@0x40066a3b[libtiny.so]0x66a3b
JNIEnv->GetStaticMethodID(android/provider/Settings$Secure.getString(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;) => 0x3efce417 was called from RX@0x4006675b[libtiny.so]0x6675b
JNIEnv->GetStaticMethodID(android/provider/Settings$Secure.getInt(Landroid/content/ContentResolver;Ljava/lang/String;)I) => 0x235c4a44 was called from RX@0x40066c45[libtiny.so]0x66c45
JNIEnv->FindClass(android/provider/Settings$System) was called from RX@0x40067391[libtiny.so]0x67391
JNIEnv->NewGlobalRef(class android/provider/Settings$System) was called from RX@0x4006739f[libtiny.so]0x6739f
JNIEnv->GetStaticMethodID(android/provider/Settings$System.getString(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;) => 0x1798fccf was called from RX@0x4006715d[libtiny.so]0x6715d
JNIEnv->GetStaticMethodID(android/provider/Settings$System.getInt(Landroid/content/ContentResolver;Ljava/lang/String;)I) => 0xd541eefc was called from RX@0x40067429[libtiny.so]0x67429
JNIEnv->FindClass(android/telephony/TelephonyManager) was called from RX@0x40067b87[libtiny.so]0x67b87
JNIEnv->NewGlobalRef(class android/telephony/TelephonyManager) was called from RX@0x40067b97[libtiny.so]0x67b97
JNIEnv->GetMethodID(android/telephony/TelephonyManager.getSimState()I) => 0xbb348335 was called from RX@0x4006771b[libtiny.so]0x6771b
JNIEnv->GetMethodID(android/telephony/TelephonyManager.getSimOperator()Ljava/lang/String;) => 0xa88ed76d was called from RX@0x40067cab[libtiny.so]0x67cab
JNIEnv->GetMethodID(android/telephony/TelephonyManager.getSimOperatorName()Ljava/lang/String;) => 0x369d2198 was called from RX@0x400679af[libtiny.so]0x679af
JNIEnv->GetMethodID(android/telephony/TelephonyManager.getImei(I)Ljava/lang/String;) => 0xaaca4c31 was called from RX@0x40067dd3[libtiny.so]0x67dd3
JNIEnv->FindClass(android/content/SharedPreferences) was called from RX@0x4006823f[libtiny.so]0x6823f
JNIEnv->NewGlobalRef(class android/content/SharedPreferences) was called from RX@0x4006824f[libtiny.so]0x6824f
JNIEnv->GetMethodID(android/content/SharedPreferences.getString(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;) => 0x2c5b4190 was called from RX@0x40068193[libtiny.so]0x68193
JNIEnv->GetMethodID(android/content/SharedPreferences.edit()Landroid/content/SharedPreferences$Editor;) => 0x5913f014 was called from RX@0x400684f1[libtiny.so]0x684f1
JNIEnv->FindClass(android/content/SharedPreferences$Editor) was called from RX@0x40068be1[libtiny.so]0x68be1
JNIEnv->NewGlobalRef(class android/content/SharedPreferences$Editor) was called from RX@0x40068bf1[libtiny.so]0x68bf1
JNIEnv->GetMethodID(android/content/SharedPreferences$Editor.putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;) => 0x201e0563 was called from RX@0x40068cfd[libtiny.so]0x68cfd
JNIEnv->GetMethodID(android/content/SharedPreferences$Editor.remove(Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;) => 0x2eafa01b was called from RX@0x40068ae7[libtiny.so]0x68ae7
JNIEnv->GetMethodID(android/content/SharedPreferences$Editor.apply()V) => 0x3434ff8c was called from RX@0x40068b11[libtiny.so]0x68b11
JNIEnv->FindClass(android/net/wifi/WifiInfo) was called from RX@0x40069175[libtiny.so]0x69175
JNIEnv->NewGlobalRef(class android/net/wifi/WifiInfo) was called from RX@0x40069185[libtiny.so]0x69185
JNIEnv->GetMethodID(android/net/wifi/WifiInfo.getSSID()Ljava/lang/String;) => 0x2d3b6000 was called from RX@0x40069247[libtiny.so]0x69247
JNIEnv->GetMethodID(android/net/wifi/WifiInfo.getBSSID()Ljava/lang/String;) => 0xffe5450e was called from RX@0x4006970d[libtiny.so]0x6970d
JNIEnv->GetMethodID(android/net/wifi/WifiInfo.getIpAddress()I) => 0x6b0928d5 was called from RX@0x40069473[libtiny.so]0x69473
JNIEnv->GetMethodID(android/net/wifi/WifiInfo.getMacAddress()Ljava/lang/String;) => 0x7e5bebca was called from RX@0x400697b5[libtiny.so]0x697b5
JNIEnv->FindClass(android/net/wifi/WifiManager) was called from RX@0x40069b8d[libtiny.so]0x69b8d
JNIEnv->NewGlobalRef(class android/net/wifi/WifiManager) was called from RX@0x40069b9d[libtiny.so]0x69b9d
JNIEnv->GetMethodID(android/net/wifi/WifiManager.getWifiState()I) => 0xedbe0581 was called from RX@0x40069911[libtiny.so]0x69911
JNIEnv->GetMethodID(android/net/wifi/WifiManager.getConnectionInfo()Landroid/net/wifi/WifiInfo;) => 0x6b848ba was called from RX@0x40069dab[libtiny.so]0x69dab
JNIEnv->FindClass(android/hardware/SensorManager) was called from RX@0x4006aa15[libtiny.so]0x6aa15
JNIEnv->NewGlobalRef(class android/hardware/SensorManager) was called from RX@0x4006aa25[libtiny.so]0x6aa25
JNIEnv->GetMethodID(android/hardware/SensorManager.getSensorList(I)Ljava/util/List;) => 0xcbe7ed08 was called from RX@0x4006aa87[libtiny.so]0x6aa87
JNIEnv->FindClass(android/hardware/Sensor) was called from RX@0x4006a31b[libtiny.so]0x6a31b
JNIEnv->NewGlobalRef(class android/hardware/Sensor) was called from RX@0x4006a329[libtiny.so]0x6a329
JNIEnv->GetMethodID(android/hardware/Sensor.getName()Ljava/lang/String;) => 0xfc35b75a was called from RX@0x4006a427[libtiny.so]0x6a427
JNIEnv->GetMethodID(android/hardware/Sensor.getType()I) => 0xaee0c2ea was called from RX@0x4006a47f[libtiny.so]0x6a47f
JNIEnv->GetMethodID(android/hardware/Sensor.getVendor()Ljava/lang/String;) => 0x3e979097 was called from RX@0x40069fdb[libtiny.so]0x69fdb
JNIEnv->GetMethodID(android/hardware/Sensor.getVersion()I) => 0x38250514 was called from RX@0x4006a679[libtiny.so]0x6a679
JNIEnv->FindClass(android/content/pm/ActivityInfo) was called from RX@0x40064f1f[libtiny.so]0x64f1f
JNIEnv->GetFieldID(android/content/pm/ActivityInfo.packageName Ljava/lang/String;) => 0xde64413d was called from RX@0x40064eed[libtiny.so]0x64eed
JNIEnv->GetFieldID(android/content/pm/ActivityInfo.applicationInfo Landroid/content/pm/ApplicationInfo;) => 0xd8a7b633 was called from RX@0x40064f77[libtiny.so]0x64f77
JNIEnv->FindClass(android/content/pm/ResolveInfo) was called from RX@0x4006471b[libtiny.so]0x6471b
JNIEnv->GetFieldID(android/content/pm/ResolveInfo.activityInfo Landroid/content/pm/ActivityInfo;) => 0x5c547120 was called from RX@0x40064879[libtiny.so]0x64879
JNIEnv->FindClass(java/lang/CharSequence) was called from RX@0x40065bfb[libtiny.so]0x65bfb
JNIEnv->GetMethodID(java/lang/CharSequence.toString()Ljava/lang/String;) => 0x13c3c453 was called from RX@0x40065bb5[libtiny.so]0x65bb5
JNIEnv->FindClass(android/app/ActivityManager) was called from RX@0x4006ade7[libtiny.so]0x6ade7
JNIEnv->GetMethodID(android/app/ActivityManager.getMemoryInfo(Landroid/app/ActivityManager$MemoryInfo;)V) => 0xdb1b58dd was called from RX@0x4006ab6f[libtiny.so]0x6ab6f
JNIEnv->FindClass(android/app/ActivityManager$MemoryInfo) was called from RX@0x4006b2b5[libtiny.so]0x6b2b5
JNIEnv->NewGlobalRef(class android/app/ActivityManager$MemoryInfo) was called from RX@0x4006b2c5[libtiny.so]0x6b2c5
JNIEnv->GetMethodID(android/app/ActivityManager$MemoryInfo.<init>()V) => 0xcba7b8af was called from RX@0x4006b257[libtiny.so]0x6b257
JNIEnv->GetFieldID(android/app/ActivityManager$MemoryInfo.totalMem J) => 0x4e593b95 was called from RX@0x4006b475[libtiny.so]0x6b475
JNIEnv->GetFieldID(android/app/ActivityManager$MemoryInfo.availMem J) => 0x2c4064ca was called from RX@0x4006b385[libtiny.so]0x6b385
JNIEnv->FindClass(android/view/MotionEvent) was called from RX@0x4006b92d[libtiny.so]0x6b92d
JNIEnv->GetMethodID(android/view/MotionEvent.getDeviceId()I) => 0x3daaa60c was called from RX@0x4006ba59[libtiny.so]0x6ba59
JNIEnv->GetMethodID(android/view/MotionEvent.getEventTime()J) => 0xa8e0edcd was called from RX@0x4006bb11[libtiny.so]0x6bb11
JNIEnv->FindClass(android/location/Location) was called from RX@0x4006be09[libtiny.so]0x6be09
JNIEnv->GetMethodID(android/location/Location.getLongitude()D) => 0x6a15fe8a was called from RX@0x4006bc91[libtiny.so]0x6bc91
JNIEnv->GetMethodID(android/location/Location.getLatitude()D) => 0x3fb04981 was called from RX@0x4006c033[libtiny.so]0x6c033
JNIEnv->GetMethodID(android/location/Location.getTime()J) => 0x1e7e9086 was called from RX@0x4006c1df[libtiny.so]0x6c1df
Find native function Java_com_xingin_tiny_internal_Hybrid_callNative => RX@0x400057a5[libtiny.so]0x57a5
JNIEnv->GetObjectArrayElement(["GET", "https://www.xiaohongshu.com/api/sns/v2/message/config", [B@233795b6], 0) => "GET" was called from RX@0x400063e9[libtiny.so]0x63e9
JNIEnv->GetObjectArrayElement(["GET", "https://www.xiaohongshu.com/api/sns/v2/message/config", [B@233795b6], 1) => "https://www.xiaohongshu.com/api/sns/v2/message/config" was called from RX@0x40005a1f[libtiny.so]0x5a1f
JNIEnv->GetObjectArrayElement(["GET", "https://www.xiaohongshu.com/api/sns/v2/message/config", [B@233795b6], 2) => [B@233795b6 was called from RX@0x40005daf[libtiny.so]0x5daf
JNIEnv->GetStringUtfChars("GET") was called from RX@0x4006162f[libtiny.so]0x6162f
JNIEnv->ReleaseStringUTFChars("GET") was called from RX@0x40061667[libtiny.so]0x61667
JNIEnv->GetStringUtfChars("https://www.xiaohongshu.com/api/sns/v2/message/config") was called from RX@0x4006162f[libtiny.so]0x6162f
JNIEnv->ReleaseStringUTFChars("https://www.xiaohongshu.com/api/sns/v2/message/config") was called from RX@0x40061667[libtiny.so]0x61667
JNIEnv->GetArrayLength([B@233795b6 => 0) was called from RX@0x40006313[libtiny.so]0x6313
JNIEnv->GetByteArrayRegion([B@233795b6, 0, 0, unidbg@0xbffff665) was called from RX@0x400060d5[libtiny.so]0x60d5
null`

一直null是不是哪里环境没补全，应该用什么方式去补呢，没有报错，无从下手了。

链接: https://pan.baidu.com/s/1_j_oWT3CRHfLpncWHcVMyg?pwd=eq2h 提取码: eq2h 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by kevinsir** [comment]
额，因为看jeb 那边返回的应该是一个map

**Comment by kevinsir** [comment]
解决了

**Comment by wengxianxun** [comment]
大佬，java.lang.UnsupportedOperationException: android/provider/Settings$Secure->getString(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;
这个怎么补的

**Comment by yamsvc** [comment]
请问是怎么解决的，我也遇到了这个问题，感谢大佬赐教

**Comment by smzll** [comment]
> 请问是怎么解决的，我也遇到了这个问题，感谢大佬赐教

解决了吗,我也遇到了这个问题
