### ISSUE TITLE
unidbg用java层的类名无法调用

### ISSUE THREAD

**Issue by richor1042** [zhkl0228/unidbg#43]
![image](https://user-images.githubusercontent.com/53560819/62282023-66345f80-b481-11e9-9a5e-721ec7236f42.png)
java层的类名如上
![image](https://user-images.githubusercontent.com/53560819/62282050-79dfc600-b481-11e9-92cc-c92cfebfae90.png)
so层的类名如上(有带1)
![image](https://user-images.githubusercontent.com/53560819/62282130-9976ee80-b481-11e9-84ad-fc431727b849.png)
调用的时候要用so层的才能时候，否则报错找不到

**Comment by lgxlovett** [comment]
如果不放dll到 system32  之前报这个错 

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'capstone': Native library (win32-x86-64/capstone.dll) not found in resource path ([file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/charsets.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/deploy.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/ext/dnsns

**Comment by zhkl0228** [comment]
测试用例方便发出来测试下吗？

**Comment by richor1042** [comment]
您好，大佬请查收
rps是非虫写的demo，so文件是libcalc



------------------ 原始邮件 ------------------
发件人: "Banny"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 晚上7:29
收件人: "zhkl0228/unidbg"<unidbg@noreply.github.com>;
抄送: "HU BONG 抢"<1042053319@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhkl0228/unidbg] unidbg用java层的类名无法调用 (#43)




测试用例方便发出来测试下吗？

**Comment by zhkl0228** [comment]
邮件发zhkl0228@gmail.com

**Comment by richor1042** [comment]
大佬，发不了     无法发送到 zhkl0228@gmail.com
  退信原因 您的邮件被收件人（zhkl0228@gmail.com）所在服务商判为垃圾邮件，对方不予接收。 
host gmail-smtp-in.l.google.com[74.125.204.26] said: 552 5.7.0 message content and attachment content guidelines. b5si39767573pgc.396 - gsmtp (in reply to end of DATA command) 
  解决方案 请避免您的邮件含有广告，欺诈，政治类信息，以及携带病毒。 如您的邮件正常但仍被判为垃圾邮件，请向我们反馈。 您也可以向管理员报告此退信。

  

 

 ------------------ 原始邮件 ------------------
  发件人: "Banny"<notifications@github.com>;
 发送时间: 2019年8月7日(星期三) 下午3:54
 收件人: "zhkl0228/unidbg"<unidbg@noreply.github.com>;
 抄送: "HU BONG 抢"<1042053319@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [zhkl0228/unidbg] unidbg用java层的类名无法调用 (#43)

 

 
邮件发zhkl0228@gmail.com

**Comment by zhkl0228** [comment]
上传到云盘再发到这

**Comment by richor1042** [comment]
链接：https://pan.baidu.com/s/1mzIlV-62SXwjVudHS9iQ4A 
提取码：ecpv 
大佬请查收
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Banny"<notifications@github.com>;
 发送时间: 2019年8月8日(星期四) 中午1:34
 收件人: "zhkl0228/unidbg"<unidbg@noreply.github.com>;
 抄送: "HU BONG 抢"<1042053319@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [zhkl0228/unidbg] unidbg用java层的类名无法调用 (#43)

 

 
上传到云盘再发到这

**Comment by zhkl0228** [comment]
除了so以外，你写的java测试代码也发出来看下

**Comment by richor1042** [comment]
private test2() throws IOException {
    emulator = createARMEmulator();
    final Memory memory = emulator.getMemory();
    memory.setLibraryResolver(createLibraryResolver());
    memory.setCallInitFunction();

    vm = emulator.createDalvikVM(null);
    vm.setJni(this);
    DalvikModule dm = vm.loadLibrary(new File("src/test/resources/example_binaries/libcalc.so"), false);
    dm.callJNI_OnLoad(emulator);

    Native = vm.resolveClass("com/example/seccon2015/rock_1paper_1scissors/MainActivity");
    Number ret = Native.callStaticJniMethod(emulator, "calc()J");
    System.out.print(ret);
}大佬，代码如上



------------------ 原始邮件 ------------------
发件人: "Banny"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 凌晨2:39
收件人: "zhkl0228/unidbg"<unidbg@noreply.github.com>;
抄送: "HU BONG 抢"<1042053319@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhkl0228/unidbg] unidbg用java层的类名无法调用 (#43)




除了so以外，你写的java测试代码也发出来看下

**Comment by zhkl0228** [comment]
是的，必须用so层的类名才能调用，这是jni规范
