### ISSUE TITLE
Unicorn在处理ITT LT的BUG

### ISSUE THREAD

**Issue by bluzye** [zhkl0228/unidbg#434]
您好，在使用unidbg测试某so时，遇到thumb指令：
ITT LT，条件是满足的，但没有执行下面两条指令。

指令手册：
ITT refers to If-Then-Then (next 2 instructions are conditional)

在unicorn issues中找到：
[作者说在uc2中修复](https://github.com/unicorn-engine/unicorn/issues/1412)

使用unidbg master最新代码，此问题还未解决。

**Comment by zhouxy158** [comment]
用Unicorn2Backend试下

**Comment by bluzye** [comment]
使用addBackendFactory(new Unicorn2Factory(false))，未解决

**Comment by bluzye** [comment]
Stalker跟踪的问题
