### ISSUE TITLE
关于ContextImpl  JNIEnv->GetMethodID 异常报错问题

### ISSUE THREAD

**Issue by bamqj** [zhkl0228/unidbg#444]
运行的时候报错，补了ContextImpl 的环境，
<img width="877" alt="image" src="https://user-images.githubusercontent.com/23720931/174439099-d4bfa12c-73ed-41cd-b7aa-0dcf9439b6fb.png">
然后又报错误，看异常提示说通过反射获取的ContextImpl 对象，获取其 getPackageManager  的methodID没有获取到。找了很多帖子，有可能是类继承问题，请问该怎么处理啊？谢谢各位。
<img width="832" alt="image" src="https://user-images.githubusercontent.com/23720931/174438643-8d797bcf-d27e-44a7-b478-02b8a0778b0c.png">

这个是整个异常的截图：
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/23720931/174438546-bc424858-ec97-4f97-b75e-df4303c715be.png">

**Comment by Pr0214** [comment]
methodid问题

**Comment by bamqj** [comment]
> Pr0214

噢，是不是unidbg没有获取到ContextImpl的对象实例啊，导致获取不到methodID呀，那这个methodID问题该怎么解决呢？

**Comment by Pr0214** [comment]
我仔细看了一下，你补错了，应该是“android/xxx”，你多了一个L前缀。

**Comment by bamqj** [comment]
> 我仔细看了一下，你补错了，应该是“android/xxx”，你多了一个L前缀。

我尝试了一下去掉前缀"L"，可还是一样的报错，/哭笑。。。。

**Comment by bamqj** [comment]
尝试使用继承关系依然报错。。。
```
switch (signature) {
            case "android/app/ActivityThread->getSystemContext()Landroid/app/ContextImpl;":
                return vm.resolveClass("android/app/ContextImpl;", vm.resolveClass("android/content/Context")).newObject(null);
```

**Comment by Pr0214** [comment]
我又仔细看了一下，你不仅前面多了L，后面还多了分号哟
