### ISSUE TITLE
[BUG]AbstractJni.java 含有错误的环境代码

### ISSUE THREAD

**Issue by bhwxha** [zhkl0228/unidbg#466]
报错,看了下源头,应该是unidbg代码笔误了

![image](https://user-images.githubusercontent.com/107301547/184915112-b9a83628-8a21-44ba-9b6c-e68d912f1ff6.png)

            case "java/lang/String->startsWith(Ljava/lang/String;)Z":{
                StringObject stringObject = (StringObject) dvmObject.getValue();
                StringObject prefix = vaList.getObjectArg(0);
                return stringObject.value.startsWith(prefix.value);
            }

dvmObject已经是StringObject;
dvmObject.getValue()得到的是String;
这边应该是笔误,应该删除.getValue()
https://github.com/zhkl0228/unidbg/blob/2324daf5c7cbdb6c30edcba6aee50d192f9b47c9/unidbg-android/src/main/java/com/github/unidbg/linux/android/dvm/AbstractJni.java#L618

**Comment by zhkl0228** [comment]
已修复

**Comment by bhwxha** [comment]
ok

**Comment by dzdzdzd123** [comment]
> 已修复

还没修复 老哥

**Comment by bhwxha** [comment]
> https://github.com/zhkl0228/unidbg/blob/2324daf5c7cbdb6c30edcba6aee50d192f9b47c9/unidbg-android/src/main/java/com/github/unidbg/linux/android/dvm/AbstractJni.java#L618

抱歉，我的错误，我看有人说最新版没有修复bug，然后我就点开了我之前发的链接，没注意到这个链接是旧的代码
点了作者大佬你发的最新版链接，发现是修复了这个bug

@dzdzdzd123，你再看一下相关代码
> https://github.com/zhkl0228/unidbg/blob/master/unidbg-android/src/main/java/com/github/unidbg/linux/android/dvm/AbstractJni.java#L618
