### ISSUE TITLE
调用libcms 的leviathan方法时,程序输出警告

### ISSUE THREAD

**Issue by super-keys** [zhkl0228/unidbg#47]
警告内容:
cn.banny.unidbg.linux.ARMSyscallHandler hook
handleInterrupt intno=2, NR=345, svcNumber=0x0, PC=unicorn@0x4022a65c[libcms.so]0x2a65c, syscall=null

根据提示, 去到相关类的hook方法. 发现是345没有定义. 
请问345对应的实现函数如何定义?
请问345对应的函数是lds吗?

**Comment by zhkl0228** [comment]
要发测试用例

**Comment by super-keys** [comment]
> 要发测试用例

您好我已经发到您的
zhkl0228@gmail.com 地址, 请查收.感谢
--

**Comment by zhkl0228** [comment]
345的系统调用提交了一个简单实现，看最新代码

**Comment by super-keys** [comment]
> 345的系统调用提交了一个简单实现，看最新代码

谢谢大佬. 我更新试试

**Comment by super-keys** [comment]
> 345的系统调用提交了一个简单实现，看最新代码

大佬你好, 我更新了最新代码. 执行测试demo没有报异常. 但是接口参数传入固定. 调用so接口后返回的结果和安卓端返回的结果不一样/.? 请问是我的使用方式有问题吗?还是在调用接口时需要模拟其它参数?

**Comment by super-keys** [comment]
谢谢大佬的解答
