### ISSUE TITLE
iOS 怎么调用这种指针的？+ (id)initData:(id)arg0 additionalKey:(id)arg1 result:(long*)arg2;(知道的大佬们回复一下，感谢)

### ISSUE THREAD

**Issue by Sabirjan** [zhkl0228/unidbg#471]
iOS 怎么调用这种指针的？

+ (id)initData:(id)arg0 additionalKey:(id)arg1 result:(long*)arg2;

;(知道的大佬们回复一下，感谢)

**Comment by Sabirjan** [comment]
iOS的 例子太少了

**Comment by Sabirjan** [comment]
@zhkl0228 大佬，指导一下

**Comment by zhkl0228** [comment]
ObjC.getCalss以及callObjc

**Comment by Sabirjan** [comment]
@interface Form: NSObject
+ (id)initData:(id)arg0 additionalKey:(id)arg1 result:(long*)arg2; 


我调用的代码:
ObjC objc = ObjC.getInstance(emulator);
ObjcClass oSignatureGenerator = objc.getClass("Form");
String input = "123";
long num1 = 0;
ObjcObject str2 = oSignatureGenerator.callObjc("unlock:additionalKey:result:",objc.newString(input),objc.newString("shareManager"),num1);
System.out.println("str2 = " + str2);

结果:
debugger break at: 0x1052054a8 @ Function64 address=0x1060f41c0, arguments=[RW@0x10508d060[FormUI.so]0x10508d060, RX@0x103e39aa6[FormUI.so]0x103e39aa6, RW@0x107a11c00, RW@0x1089b53a0, 0]
Unicorn fallback @ 0x1052054a8 for 142041 instructions (instr = 0x00000000)

**Comment by zhouxy158** [comment]
因为ios的arm64二进制指令集很新，推荐配合apple m1的hypervisor backend

**Comment by zhouxy158** [comment]
先切换unicorn后端试下

**Comment by Sabirjan** [comment]
@zhouxy158 “先切换unicorn后端试下”
怎么切换，你的意思是 项目里面的unicorn切换还是

**Comment by Sabirjan** [comment]
非常感谢 @zhkl0228
