### ISSUE TITLE
有没有会的大佬解决这个问题,com.github.unidbg.arm.backend.BackendException

### ISSUE THREAD

**Issue by hyoHhh** [zhkl0228/unidbg#519]
methodid到底是啥问题..我用frida hook  没问题,这个是一个黑盒,  用frida hook这个so文件的 一个 static native 方法 可以拿到结果,想试试使用unidbg,一直提示这个问题,也没有文档 告知解决方法.卡了半天了

**Comment by HappyTsing** [comment]
如何解决的呢
