### ISSUE TITLE
报这样一个错误，并且也没有堆栈main]E/JDG: [make_header:483] [-] Error pp not init

### ISSUE THREAD

**Issue by jianisodk** [zhkl0228/unidbg#550]
[10:19:32 082]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:468) - libjdg.so load dependency libandroid.so failed
JNIEnv->FindClass(com/jd/security/jdguard/core/Bridge) was called from RX@0x40015ab1[libjdg.so]0x15ab1
JNIEnv->RegisterNatives(com/jd/security/jdguard/core/Bridge, RW@0x4004b15c[libjdg.so]0x4b15c, 1) was called from RX@0x40015a73[libjdg.so]0x15a73
RegisterNative(com/jd/security/jdguard/core/Bridge, main(I[Ljava/lang/Object;)[Ljava/lang/Object;, RX@0x40015b19[libjdg.so]0x15b19)
Find native function Java_com_jd_security_jdguard_core_Bridge_main => RX@0x40015b19[libjdg.so]0x15b19
JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 0) => [B@75412c2f was called from RX@0x40016635[libjdg.so]0x16635
JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 1) => "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-" was called from RX@0x400177e7[libjdg.so]0x177e7
JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 2) => "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv" was called from RX@0x40016d43[libjdg.so]0x16d43
JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 3) => "1.0" was called from RX@0x40016a7b[libjdg.so]0x16a7b
JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 4) => "83" was called from RX@0x40016f01[libjdg.so]0x16f01
JNIEnv->GetStringUtfChars("83") was called from RX@0x4001d347[libjdg.so]0x1d347
JNIEnv->ReleaseStringUTFChars("83") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1
JNIEnv->GetArrayLength([B@75412c2f => 1285) was called from RX@0x40017983[libjdg.so]0x17983
JNIEnv->GetByteArrayRegion([B@75412c2f, 0, 1285, RW@0x40257000) was called from RX@0x400174ab[libjdg.so]0x174ab
JNIEnv->GetStringUtfChars("sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-") was called from RX@0x4001d347[libjdg.so]0x1d347
JNIEnv->ReleaseStringUTFChars("sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1
JNIEnv->GetStringUtfChars("eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv") was called from RX@0x4001d347[libjdg.so]0x1d347
JNIEnv->ReleaseStringUTFChars("eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1
JNIEnv->GetStringUtfChars("1.0") was called from RX@0x4001d347[libjdg.so]0x1d347
JNIEnv->ReleaseStringUTFChars("1.0") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1
JNIEnv->FindClass(java/lang/Integer) was called from RX@0x40019e53[libjdg.so]0x19e53
JNIEnv->GetMethodID(java/lang/Integer.<init>(I)V) => 0x4c76e5db was called from RX@0x40019ed7[libjdg.so]0x19ed7
JNIEnv->NewObjectV(class java/lang/Integer, <init>(0xffffef8f) => java.lang.Integer@3ecf72fd) was called from RX@0x40019df9[libjdg.so]0x19df9
[main]E/JDG: [make_header:483] [-] Error pp not init

进程已结束,退出代码0

**Comment by yulei-fighting** [comment]
请问下这个问题是怎么解决的啊

**Comment by bfy2000** [comment]
请问大佬解决了吗

**Comment by shuxuliang** [comment]
没初始化，JDG模块里有初始化逻辑，慢慢缕一下吧

**Comment by wjs876046992** [comment]
> 没初始化，JDG模块里有初始化逻辑，慢慢缕一下吧

![image](https://github.com/zhkl0228/unidbg/assets/17695195/2b71b707-7f4d-4172-be33-bec0cac47cfe)
<img width="557" alt="image" src="https://github.com/zhkl0228/unidbg/assets/17695195/f1de33a3-3e0e-485d-a4fe-c69e009adc2f">
看到这两步zhi h之后就不知道怎么补了。

**Comment by kenny68** [comment]
> [10:19:32 082] INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:468) - libjdg.so load dependency libandroid.so failed JNIEnv->FindClass(com/jd/security/jdguard/core/Bridge) was called from RX@0x40015ab1[libjdg.so]0x15ab1 JNIEnv->RegisterNatives(com/jd/security/jdguard/core/Bridge, RW@0x4004b15c[libjdg.so]0x4b15c, 1) was called from RX@0x40015a73[libjdg.so]0x15a73 RegisterNative(com/jd/security/jdguard/core/Bridge, main(I[Ljava/lang/Object;)[Ljava/lang/Object;, RX@0x40015b19[libjdg.so]0x15b19) Find native function Java_com_jd_security_jdguard_core_Bridge_main => RX@0x40015b19[libjdg.so]0x15b19 JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 0) => [B@75412c2f was called from RX@0x40016635[libjdg.so]0x16635 JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 1) => "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-" was called from RX@0x400177e7[libjdg.so]0x177e7 JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 2) => "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv" was called from RX@0x40016d43[libjdg.so]0x16d43 JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 3) => "1.0" was called from RX@0x40016a7b[libjdg.so]0x16a7b JNIEnv->GetObjectArrayElement([[B@75412c2f, "sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-", "eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv", "1.0", "83"], 4) => "83" was called from RX@0x40016f01[libjdg.so]0x16f01 JNIEnv->GetStringUtfChars("83") was called from RX@0x4001d347[libjdg.so]0x1d347 JNIEnv->ReleaseStringUTFChars("83") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1 JNIEnv->GetArrayLength([B@75412c2f => 1285) was called from RX@0x40017983[libjdg.so]0x17983 JNIEnv->GetByteArrayRegion([B@75412c2f, 0, 1285, RW@0x40257000) was called from RX@0x400174ab[libjdg.so]0x174ab JNIEnv->GetStringUtfChars("sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-") was called from RX@0x4001d347[libjdg.so]0x1d347 JNIEnv->ReleaseStringUTFChars("sdm845|-|OnePlus6|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§0|1§§-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-§§-|115717931008§§-|-|1.0|-§§0|1|-|-|-|-|-|-|-|-|-§§OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107162030:user/release-keys/|-|-|1678344292938|-§§-|-|-|-|-|-|-") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1 JNIEnv->GetStringUtfChars("eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv") was called from RX@0x4001d347[libjdg.so]0x1d347 JNIEnv->ReleaseStringUTFChars("eidAf5088122acsfbxEYf1ulTs2pUn38cGRLh28RGgYgyPwz80gu9s7yfbXAvbZ1R70WQm1PENZaDGd6EF/munBEHRDWPW5sYgYPelPhS+vYueanoeJv") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1 JNIEnv->GetStringUtfChars("1.0") was called from RX@0x4001d347[libjdg.so]0x1d347 JNIEnv->ReleaseStringUTFChars("1.0") was called from RX@0x4001d3b1[libjdg.so]0x1d3b1 JNIEnv->FindClass(java/lang/Integer) was called from RX@0x40019e53[libjdg.so]0x19e53 JNIEnv->GetMethodID(java/lang/Integer.(I)V) => 0x4c76e5db was called from RX@0x40019ed7[libjdg.so]0x19ed7 JNIEnv->NewObjectV(class java/lang/Integer, (0xffffef8f) => java.lang.Integer@3ecf72fd) was called from RX@0x40019df9[libjdg.so]0x19df9 [main]E/JDG: [make_header:483] [-] Error pp not init
> 
> 进程已结束,退出代码0

------------------》
兄弟，问题解决了吗

**Comment by kenny68** [comment]
@jianisodk 解决了吗

**Comment by bfy2000** [comment]
> @jianisodk 解决了吗

据说是在.so里面做了初始化，这个error是被try-catch块里面打的日志，需要先定位catch的位置然后追回变量初始化的位置，但是我也没找到😂

**Comment by shuxuliang** [comment]
> > @jianisodk 解决了吗
> 
> 据说是在.so里面做了初始化，这个error是被try-catch块里面打的日志，需要先定位catch的位置然后追回变量初始化的位置，但是我也没找到😂

在哪听说的？应该跟你说这个关系不大。很久之前我弄过，具体忘记了。只记得jdg里初始化会扫原始apk文件，解包扫资源xbt，jpg等文件，然后有个unidbg的系统函数存在bug跟真机环境运行结果不一样导致初始化失败。jdg模块初始化里还存在一个暗桩，大致是在ndk里创建一个java层的类对象，但是这个类根本不存在，如果unidbg补环境的过程中成功将其创建了则初始化失败。

**Comment by shuxuliang** [comment]
如果在jdg这里卡住了，我说句实话各位修行还不太够。或者说没入门。肯定没有好好的跟踪so文件里的汇编代码，其实不难，就怕没耐心

**Comment by jiefengH** [comment]
初学者，也在网上的 资料中，跑到not init这里卡住了。不知有没有大佬 能指点下
