### ISSUE TITLE
这种异常到底要什么样的思路去解决呢Invalid memory read (UC_ERR_READ_UNMAPPED)

### ISSUE THREAD

**Issue by jianisodk** [zhkl0228/unidbg#551]
[19:39:23 948]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:468) - libjdg.so load dependency libandroid.so failed
=====Open Path with=====> /dev/__properties__
=====Open Path with=====> /proc/stat
JNIEnv->FindClass(com/jd/security/jdguard/core/Bridge) was called from RX@0x40015ab1[libjdg.so]0x15ab1
JNIEnv->RegisterNatives(com/jd/security/jdguard/core/Bridge, RW@0x4004b15c[libjdg.so]0x4b15c, 1) was called from RX@0x40015a73[libjdg.so]0x15a73
RegisterNative(com/jd/security/jdguard/core/Bridge, main(I[Ljava/lang/Object;)[Ljava/lang/Object;, RX@0x40015b19[libjdg.so]0x15b19)
=====call 103=====
Find native function Java_com_jd_security_jdguard_core_Bridge_main => RX@0x40015b19[libjdg.so]0x15b19
onCall
X2_value1 = 103
JNIEnv->FindClass(com/jd/security/jdguard/core/Bridge) was called from RX@0x4001a72f[libjdg.so]0x1a72f
JNIEnv->NewGlobalRef(class com/jd/security/jdguard/core/Bridge) was called from RX@0x4001a75f[libjdg.so]0x1a75f
JNIEnv->GetStaticMethodID(com/jd/security/jdguard/core/Bridge.getAppContext()Landroid/content/Context;) => 0x999899a7 was called from RX@0x4001a695[libjdg.so]0x1a695
JNIEnv->CallStaticObjectMethodV(class com/jd/security/jdguard/core/Bridge, getAppContext() => android.content.Context@2d6e8792) was called from RX@0x4001a7cb[libjdg.so]0x1a7cb
JNIEnv->GetMethodID(android/content/Context.getPackageName()Ljava/lang/String;) => 0xf6590850 was called from RX@0x4001b3cf[libjdg.so]0x1b3cf
JNIEnv->CallObjectMethodV(android.content.Context@2d6e8792, getPackageName() => "com.jingdong.app.mall") was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->GetStringUtfChars("com.jingdong.app.mall") was called from RX@0x4001b437[libjdg.so]0x1b437
JNIEnv->ReleaseStringUTFChars("com.jingdong.app.mall") was called from RX@0x4001b477[libjdg.so]0x1b477
JNIEnv->GetStaticMethodID(com/jd/security/jdguard/core/Bridge.getAppContext()Landroid/content/Context;) => 0x999899a7 was called from RX@0x4001a695[libjdg.so]0x1a695
JNIEnv->CallStaticObjectMethodV(class com/jd/security/jdguard/core/Bridge, getAppContext() => android.content.Context@2acf57e3) was called from RX@0x4001a7cb[libjdg.so]0x1a7cb
JNIEnv->GetStaticMethodID(com/jd/security/jdguard/core/Bridge.getAppContext()Landroid/content/Context;) => 0x999899a7 was called from RX@0x4001a695[libjdg.so]0x1a695
JNIEnv->CallStaticObjectMethodV(class com/jd/security/jdguard/core/Bridge, getAppContext() => android.content.Context@506e6d5e) was called from RX@0x4001a7cb[libjdg.so]0x1a7cb
JNIEnv->GetMethodID(android/content/Context.getPackageName()Ljava/lang/String;) => 0xf6590850 was called from RX@0x4001b3cf[libjdg.so]0x1b3cf
JNIEnv->CallObjectMethodV(android.content.Context@506e6d5e, getPackageName() => "com.jingdong.app.mall") was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->GetStringUtfChars("com.jingdong.app.mall") was called from RX@0x4001b437[libjdg.so]0x1b437
JNIEnv->ReleaseStringUTFChars("com.jingdong.app.mall") was called from RX@0x4001b477[libjdg.so]0x1b477
JNIEnv->FindClass(android/content/pm/PackageManager) was called from RX@0x4001aea5[libjdg.so]0x1aea5
JNIEnv->GetStaticFieldID(android/content/pm/PackageManager.GET_SIGNATURESI) => 0x50720de7 was called from RX@0x4001af19[libjdg.so]0x1af19
JNIEnv->GetStaticIntField(class android/content/pm/PackageManager, GET_SIGNATURES => 0x40) was called from RX@0x4001af57[libjdg.so]0x1af57
JNIEnv->GetStaticMethodID(com/jd/security/jdguard/core/Bridge.getAppContext()Landroid/content/Context;) => 0x999899a7 was called from RX@0x4001a695[libjdg.so]0x1a695
JNIEnv->CallStaticObjectMethodV(class com/jd/security/jdguard/core/Bridge, getAppContext() => android.content.Context@3796751b) was called from RX@0x4001a7cb[libjdg.so]0x1a7cb
JNIEnv->GetMethodID(android/content/Context.getPackageManager()Landroid/content/pm/PackageManager;) => 0x3acc78f0 was called from RX@0x4001a3d7[libjdg.so]0x1a3d7
JNIEnv->CallObjectMethodV(android.content.Context@3796751b, getPackageManager() => android.content.pm.PackageManager@67b64c45) was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->GetMethodID(android/content/pm/PackageManager.getPackageInfo(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;) => 0x3bca8377 was called from RX@0x4001a223[libjdg.so]0x1a223
JNIEnv->NewStringUTF("com.jingdong.app.mall") was called from RX@0x4001a257[libjdg.so]0x1a257
JNIEnv->CallObjectMethodV(android.content.pm.PackageManager@67b64c45, getPackageInfo("com.jingdong.app.mall", 0x40) => android.content.pm.PackageInfo@6442b0a6) was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->GetFieldID(android/content/pm/PackageInfo.signatures [Landroid/content/pm/Signature;) => 0x25f17218 was called from RX@0x4001b05b[libjdg.so]0x1b05b
JNIEnv->GetObjectField(android.content.pm.PackageInfo@6442b0a6, signatures [Landroid/content/pm/Signature; => [android.content.pm.Signature@69d9c55]) was called from RX@0x4001b095[libjdg.so]0x1b095
JNIEnv->GetArrayLength([android.content.pm.Signature@69d9c55] => 1) was called from RX@0x4001b0d7[libjdg.so]0x1b0d7
JNIEnv->GetObjectArrayElement([android.content.pm.Signature@69d9c55], 0) => android.content.pm.Signature@69d9c55 was called from RX@0x4001b111[libjdg.so]0x1b111
JNIEnv->GetMethodID(android/content/pm/Signature.toByteArray()[B) => 0x6a3e2031 was called from RX@0x4001b21f[libjdg.so]0x1b21f
JNIEnv->CallObjectMethodV(android.content.pm.Signature@69d9c55, toByteArray() => [B@7ca48474) was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->FindClass(java/io/ByteArrayInputStream) was called from RX@0x4001a833[libjdg.so]0x1a833
JNIEnv->GetMethodID(java/io/ByteArrayInputStream.<init>([B)V) => 0xa3476a24 was called from RX@0x4001a8ab[libjdg.so]0x1a8ab
JNIEnv->NewObjectV(class java/io/ByteArrayInputStream, <init>([B@7ca48474) => java.io.ByteArrayInputStream@59e84876) was called from RX@0x40019df9[libjdg.so]0x19df9
JNIEnv->FindClass(java/security/cert/CertificateFactory) was called from RX@0x4001a937[libjdg.so]0x1a937
JNIEnv->GetStaticMethodID(java/security/cert/CertificateFactory.getInstance(Ljava/lang/String;)Ljava/security/cert/CertificateFactory;) => 0x2cba31f6 was called from RX@0x4001a9ab[libjdg.so]0x1a9ab
JNIEnv->NewStringUTF("X509") was called from RX@0x4001aa53[libjdg.so]0x1aa53
JNIEnv->CallStaticObjectMethodV(class java/security/cert/CertificateFactory, getInstance("X509") => java.security.cert.CertificateFactory@39fb3ab6) was called from RX@0x4001a7cb[libjdg.so]0x1a7cb
JNIEnv->GetMethodID(java/security/cert/CertificateFactory.generateCertificate(Ljava/io/InputStream;)Ljava/security/cert/Certificate;) => 0xdeaa2324 was called from RX@0x4001ab13[libjdg.so]0x1ab13
JNIEnv->CallObjectMethodV(java.security.cert.CertificateFactory@39fb3ab6, generateCertificate(java.io.ByteArrayInputStream@59e84876) => java.security.cert.Certificate@6276ae34) was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->GetMethodID(java/security/cert/Certificate.getEncoded()[B) => 0x7b49dc1f was called from RX@0x4001ac87[libjdg.so]0x1ac87
JNIEnv->CallObjectMethodV(java.security.cert.Certificate@6276ae34, getEncoded() => [B@7946e1f4) was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->GetArrayLength([B@7946e1f4 => 587) was called from RX@0x4001ad03[libjdg.so]0x1ad03
JNIEnv->GetStaticMethodID(com/jd/security/jdguard/core/Bridge.getAppContext()Landroid/content/Context;) => 0x999899a7 was called from RX@0x4001a695[libjdg.so]0x1a695
JNIEnv->CallStaticObjectMethodV(class com/jd/security/jdguard/core/Bridge, getAppContext() => android.content.Context@5cc7c2a6) was called from RX@0x4001a7cb[libjdg.so]0x1a7cb
JNIEnv->GetMethodID(android/content/Context.getPackageCodePath()Ljava/lang/String;) => 0xc493eef7 was called from RX@0x4001b5ef[libjdg.so]0x1b5ef
JNIEnv->CallObjectMethodV(android.content.Context@5cc7c2a6, getPackageCodePath() => "/data/app/com.jingdong.app.mall-ALiv1lAjQ8erUgxEi6H4wA==/base.apk") was called from RX@0x4001a4db[libjdg.so]0x1a4db
JNIEnv->GetStringUtfChars("/data/app/com.jingdong.app.mall-ALiv1lAjQ8erUgxEi6H4wA==/base.apk") was called from RX@0x4001b637[libjdg.so]0x1b637
JNIEnv->ReleaseStringUTFChars("/data/app/com.jingdong.app.mall-ALiv1lAjQ8erUgxEi6H4wA==/base.apk") was called from RX@0x4001b67b[libjdg.so]0x1b67b
=====Open Path with=====> /data/app/com.jingdong.app.mall-ALiv1lAjQ8erUgxEi6H4wA==/base.apk
[19:39:24 249]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:64) - Read memory failed: address=0x56668c31, size=1, value=0x0, PC=RX@0x4010d658[libc.so]0x17658, LR=RX@0x40019341[libjdg.so]0x19341
[19:39:24 249]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x40015b19[libjdg.so]0x15b19 exception sp=unidbg@0xbffff2d0, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=80ms

**Comment by jianisodk** [comment]
甚至不知道该如何下手。。。

**Comment by kevinsir** [comment]
我跟你一样，请问你解决了吗

**Comment by wybigsea9** [comment]
一样的，我也想问，我补后返回不是0 ，
JNIEnv->CallStaticObjectMethodV(class com/jd/security/jdguard/core/Bridge, getSecName() => "ccf12ce1-39a4-4ce0-ad4b-cdd05a32b7b5.jdg.xbt") was called from RX@0x4062ff50[libjdg.so]0x2ff50
JNIEnv->GetStringUtfChars("ccf12ce1-39a4-4ce0-ad4b-cdd05a32b7b5.jdg.xbt") was called from RX@0x40633694[libjdg.so]0x33694
JNIEnv->ReleaseStringUTFChars("ccf12ce1-39a4-4ce0-ad4b-cdd05a32b7b5.jdg.xbt") was called from RX@0x40632444[libjdg.so]0x32444
open:/data/app/com.jd.jdlite-djJcAUmx20KI1r2XwWNatA==/base.apk
JNIEnv->FindClass(java/lang/Integer) was called from RX@0x4062efe8[libjdg.so]0x2efe8
JNIEnv->GetMethodID(java/lang/Integer.<init>(I)V) => 0x4c76e5db was called from RX@0x4062f0b8[libjdg.so]0x2f0b8
JNIEnv->NewObjectV(class java/lang/Integer, <init>(0xfffff3e2) => java.lang.Integer@1725dc0f) was called from RX@0x4062ef50[libjdg.so]0x2ef50
返回：-3102

**Comment by BeHalcyon** [comment]
大佬，我补这个库时候遇到[main]E/JDG: [make_header:480] [-] Error pp not init
有什么解决办法吗
