### ISSUE TITLE
系统提示缺失的JAVA方法，反编译APK后找不到，导致无法补正确的结果

### ISSUE THREAD

**Issue by Alphamerry** [zhkl0228/unidbg#552]
样本使用的是QQ8950版本，SO文件名libfekit.so.

架子搭好后，最后一行提示：JNIEnv->GetStaticMethodID(com/tencent/mobileqq/qsec/qsecest/QsecEst.p(Landroid/content/Context;I)Ljava/lang/String;) => 0x747ab66c was called from RX@0x400718fc[libfekit.so]0x718fc。
但是在QsecEst这个类里面并没有这个p方法，导致无法通过HOOK来确定数据来源。

完整代码如下：
package com.bytedance.frameworks.core.encrypt;

import com.alibaba.fastjson.util.IOUtils;
import com.github.unidbg.AndroidEmulator;

import com.github.unidbg.Module;

import com.github.unidbg.arm.backend.Unicorn2Factory;

import com.github.unidbg.file.linux.AndroidFileIO;

import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;

import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.spi.SyscallHandler;
import com.github.unidbg.utils.Inspector;

import java.io.File;

public class TTEncrypt extends  AbstractJni{

    private final AndroidEmulator emulator;
    private final VM vm;
    private final boolean logging;

    TTEncrypt(boolean logging) {
        this.logging = logging;

        emulator = AndroidEmulatorBuilder.for64Bit()
                .setProcessName("com.qidian.dldl.official")
                .addBackendFactory(new Unicorn2Factory(true))
                .build(); // 创建模拟器实例，要模拟32位或者64位，在这里区分
        final Memory memory = emulator.getMemory(); // 模拟器的内存操作接口
        memory.setLibraryResolver(new AndroidResolver(23)); // 设置系统类库解析

        vm = emulator.createDalvikVM(); // 创建Android虚拟机
        vm.setJni(this);
        vm.setVerbose(logging); // 设置是否打印Jni调用细节
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/libfekit.so"), false); // 加载libttEncrypt.so到unicorn虚拟内存，加载成功以后会默认调用init_array等函数

        SyscallHandler<AndroidFileIO> syscallHandler = emulator.getSyscallHandler();
        syscallHandler.setEnableThreadDispatcher(true);
        dm.callJNI_OnLoad(emulator); // 手动执行JNI_OnLoad函数
        Module module = dm.getModule(); // 加载好的libttEncrypt.so对应为一个模块

    }
    @Override
    public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        switch (signature){
            case "com/tencent/mobileqq/qsec/qsecest/QsecEst->p(Landroid/content/Context;I)Ljava/lang/String;": {

                return new StringObject(vm,"AABBCC");//在JAVA中找不到这个方法，无法补正确数据
            }

        }
        return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);
    }

    void destroy() {
        IOUtils.close(emulator);
        if (logging) {
            System.out.println("destroy");
        }
    }

    public static void main(String[] args) throws Exception {
        TTEncrypt test = new TTEncrypt(true);

        byte[] data = test.ttEncrypt();
        Inspector.inspect(data, "ttEncrypt");

        test.destroy();
    }

    byte[] ttEncrypt() {
        String methodSign = "d(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)[B";

        DvmObject<?> Context = vm.resolveClass("android/content/Context").newObject(null);

        ByteArray est = vm.resolveClass("com.tencent.mobileqq.qsec.qsecest.QsecEst").callStaticJniMethodObject(emulator, methodSign, Context, new StringObject(vm, "![22222](https://github.com/zhkl0228/unidbg/assets/133935849/0cc0c9f9-6be7-4e60-bb6f-05809c542daf)"),new StringObject(vm, ""));

        return est.getValue();

    }

}
![1111](https://github.com/zhkl0228/unidbg/assets/133935849/cd686349-aa66-4cb2-919a-70288e66d105)

![22222](https://github.com/zhkl0228/unidbg/assets/133935849/1cef255c-85a7-40a2-91f5-ed2f13130743)

**Comment by fuqiuluo** [comment]
https://github.com/fuqiuluo/unidbg-fetch-qsign/commit/f0e02f26f8094508b082ff62e72a41c36a4846cd#diff-a6089df629406633427ceb0681ea6c2e3015f27b6bb5c792c0ccac338cf07effR138

**Comment by Alphamerry** [comment]
> [fuqiuluo/unidbg-fetch-qsign@f0e02f2#diff-a6089df629406633427ceb0681ea6c2e3015f27b6bb5c792c0ccac338cf07effR138](https://github.com/fuqiuluo/unidbg-fetch-qsign/commit/f0e02f26f8094508b082ff62e72a41c36a4846cd#diff-a6089df629406633427ceb0681ea6c2e3015f27b6bb5c792c0ccac338cf07effR138)

感谢回复，我之前直接按照老版本的补的，也不知道能不能用，现在试试大佬的。
