### ISSUE TITLE
新版iOS 找不到方法

### ISSUE THREAD

**Issue by BadDeveloper2022** [zhkl0228/unidbg#576]
` 
HookLoader.load(emulator).hookDispatchAsync(new DispatchAsyncCallback() {

                @Override
                public boolean canDispatch(Pointer dq, Pointer fun) {

                    long f = UnidbgPointer.nativeValue(fun);
                    System.out.println("canDispatch dq=" + dq + ", fun=" + fun + " L=" + f);

                    return f == 0x102366b8cL || f == 0x102366cccL;
                }
            });
`

新版IOS 怎么实现此功能

**Comment by zhkl0228** [comment]
DispatchAsyncCallback 的方法改成了：boolean canDispatch(Emulator<?> emulator, Pointer dq, Pointer fun, boolean is_barrier_async);
