### ISSUE TITLE
Linux服务器上初始化unicorn失败

### ISSUE THREAD

**Issue by chenliquan2** [zhkl0228/unidbg#58]
在Windows环境运行正常，将项目部署到linux服务器上，一开始报找不到unicorn_java，在将linux64的so设置入服务器的java.path后，出现另一个错误Could not initialize class unicorn.Unicorn，发现是在下面new Unicorn中进入jar后报了错，请问作者这个是什么原因：

public AbstractEmulator(int unicorn_arch, int unicorn_mode, String processName) {
        super();

        this.unicorn = new Unicorn(unicorn_arch, unicorn_mode);
        this.processName = processName == null ? "unidbg" : processName;
        this.registerContext = createRegisterContext(unicorn);

        this.readHook = new TraceMemoryHook();
        this.writeHook = new TraceMemoryHook();
        this.codeHook = new AssemblyCodeDumper(this);

        String name = ManagementFactory.getRuntimeMXBean().getName();
        String pid = name.split("@")[0];
        this.pid = Integer.parseInt(pid);

        POINTER_SIZE.set(getPointerSize());
    }

**Comment by chenliquan2** [comment]
之后又出现了libcapstone.so:file too short的错误

**Comment by zhkl0228** [comment]
可能要自行编译三剑客

**Comment by chenliquan2** [comment]
> 可能要自行编译三剑客

好的，正在尝试中

**Comment by chenliquan2** [comment]
> 可能要自行编译三剑客

谢谢大佬，问题已解决，不用重新编译，直接将Linux64下面的几个so放到/user/lib下面，然后升级下libc.so.6就行。主要是这个升级的问题，被我搞复杂了。
