### ISSUE TITLE
[UIDevice userInterfaceIdiom]: unrecognized selector sent to instance xxx 这种的怎么hook 补

### ISSUE THREAD

**Issue by BadDeveloper2022** [zhkl0228/unidbg#587]
Dec 19 12:53:10 unidbg.local JINJIANG-iOS[6096] <Error>: -[UIDevice userInterfaceIdiom]: unrecognized selector sent to instance 0x104a672d0
2023-12-19 12:53:10.250 JINJIANG-iOS[6096:3] -[UIDevice userInterfaceIdiom]: unrecognized selector sent to instance 0x104a672d0
Dec 19 12:53:10 unidbg.local JINJIANG-iOS[6096] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIDevice userInterfaceIdiom]: unrecognized selector sent to instance 0x104a672d0'
	*** First throw call stack:
	(0x101e66950 0x101b881fc 0x101e6b604 0x101e69330 0x101d8908c 0x1005dd1e4 0x1005b4654 0x1004d0a14 0x1004d3344 0x1004d9068 0x1005a1f08 0x7ffff0000)
2023-12-19 12:53:10.294 JINJIANG-iOS[6096:3] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIDevice userInterfaceIdiom]: unrecognized selector sent to instance 0x104a672d0'
*** First throw call stack:
(0x101e66950 0x101b881fc 0x101e6b604 0x101e69330 0x101d8908c 0x1005dd1e4 0x1005b4654 0x1004d0a14 0x1004d3344 0x1004d9068 0x1005a1f08 0x7ffff0000)
libc++abi.dylib: terminating with uncaught exception of type NSException

-----------
`
 objc = ObjC.getInstance(emulator);
            ObjcClass cPLCrashReporter = objc.getClass("UIDevice");
            substrate.hookMessageEx(cPLCrashReporter, objc.registerName("userInterfaceIdiom"), new ReplaceCallback() {
                @Override
                public HookStatus onCall(Emulator<?> emulator, HookContext context, long originFunction) {
                    System.out.println("hook成功 [UIDevice userInterfaceIdiom]");
                    return HookStatus.LR(emulator, 0L);
                }

                @Override
                public HookStatus onCall(Emulator<?> emulator, long originFunction) {
                    System.out.println("hook成功 [UIDevice userInterfaceIdiom]");
                    return super.onCall(emulator, originFunction);
                }
            });
`
这样hook 没成功拦截

**Comment by zhouxy158** [comment]
写进UIKit.m中编译

**Comment by zhkl0228** [comment]
是的，ios的开发建议mac os x
