### ISSUE TITLE
你好，执行速度有点慢，能从哪个方向解决啊？

### ISSUE THREAD

**Issue by xsren** [zhkl0228/unidbg#63]
你好，我跑起来了程序。在执行callStaticJniMethod的方法的时候有点慢，会花费3s左右的时间。请问可以从哪个方面优化啊？

**Comment by xsren** [comment]
![image](https://user-images.githubusercontent.com/4971925/67615406-a1cf9300-f7fe-11e9-9f65-5267dfbdce3c.png)
如图，我看你提供的例子 Utilities32 的最后一个也耗时3s多，请问有可能优化吗？

**Comment by zhkl0228** [comment]
用armv8 64位的so会快不少

**Comment by xsren** [comment]
好的，我试试。多谢！
