### ISSUE TITLE
android/graphics/Bitmap$Config->ARGB_8888:Landroid/graphics/Bitmap$Config;

### ISSUE THREAD

**Issue by 18712886438** [zhkl0228/unidbg#70]
请教大佬，getStaticObjectField中ARGB_8888:Landroid/graphics/Bitmap$Config;这种应该如何返回呢

**Comment by zhkl0228** [comment]
case "android/graphics/Bitmap$Config->ARGB_8888:Landroid/graphics/Bitmap$Config;":
                return dvmClass.newObject("ARGB_8888");

**Comment by 18712886438** [comment]
> case "android/graphics/Bitmap$Config->ARGB_8888:Landroid/graphics/Bitmap$Config;":
> return dvmClass.newObject("ARGB_8888");

好的，感谢大佬
