### ISSUE TITLE
Invalid memory fetch (UC_ERR_FETCH_UNMAPPED). Manipulation of Java objects by so libraries is not supported. 

### ISSUE THREAD

**Issue by owlwang** [zhkl0228/unidbg#71]
Manipulation of Java objects by so libraries seems is not supported. 

When the so lib have code like 
C: 
```c
jfieldID pointer_fieldid = (*env)->GetFieldID(env, clazz, "address", "J");
jlong pointer = (*env)->GetLongField(env, obj, pointer_fieldid);
```

It will alert Invalid memory fetch (UC_ERR_FETCH_UNMAPPED).
pointer  cannot get the correct value.

**Comment by zhkl0228** [comment]
post the test

**Comment by owlwang** [comment]
I have sent it to you by email.

**Comment by zhkl0228** [comment]
I committed the code, implemented GetPrimitiveArrayCritical and ReleasePrimitiveArrayCritical.
The test should like this, in attachment.
[shazam.tar.gz](https://github.com/zhkl0228/unidbg/files/3948760/shazam.tar.gz)

**Comment by owlwang** [comment]
Everything's working fine!
Thank you for your efforts!

I also have a question, is there any way to speed up the computation?
It looks a little slow now.

**Comment by zhkl0228** [comment]
There is no other option to speed up unicorn now

**Comment by owlwang** [comment]
Thanks again for your work.
