### ISSUE TITLE
如何修改直接修改模拟的设备信息，如ro.product.model,ro.product.manufacturer

### ISSUE THREAD

**Issue by weechatfly** [zhkl0228/unidbg#74]
作者你好，请问下如何如何修改直接修改模拟的设备信息，如ro.product.model,ro.product.manufacturer等这些属性，我使用__system_property_set修改不成功。
谢谢！

**Comment by zhkl0228** [comment]
SystemPropertyHook systemPropertyHook = new SystemPropertyHook(emulator);
memory.addHookListener(systemPropertyHook);

**Comment by weechatfly** [comment]
非常感谢，可以了！

**Comment by weechatfly** [comment]
已解决
