### ISSUE TITLE
iOS ARM64 emulation callRoutines调用不成功

### ISSUE THREAD

**Issue by chago** [zhkl0228/unidbg#83]
iOS64位模拟器初始化时将加载的模块内存段全设置为可写后，在 __os_object_release 中死循环怎么解决？

**Comment by zhkl0228** [comment]
iOS64位模拟太多坑，unidbg很不完善，建议分析dylib看原因

**Comment by chago** [comment]
> iOS64位模拟太多坑，unidbg很不完善，建议分析dylib看原因

有具体的分析方法吗？
在libsystem.B.dylib的__libxpc_initializer中的调用_os_object_release后，objc_msgSend(a1, "_xref_dispose")的返回值不正确导致死循环了，是libobjc的环境初始化不成功吗？

**Comment by zhkl0228** [comment]
64位的objc环境初始化一直没有调成功，目前我也是卡在这

**Comment by zhkl0228** [comment]
返回值不正确就要逆向看dylib里的逻辑，看是什么原因引起的不正确

**Comment by chago** [comment]
OK

**Comment by chago** [comment]
在libxpc.dylib的这个位置出现问题
![171580729365_ pic](https://user-images.githubusercontent.com/2239471/73649777-8a385e00-46bb-11ea-87f4-ce9919c2f597.jpg)

来到libdispatch.dylib的_os_object_release函数
![151580729208_ pic](https://user-images.githubusercontent.com/2239471/73649854-ae943a80-46bb-11ea-80be-39777b0a7995.jpg)
![161580729218_ pic](https://user-images.githubusercontent.com/2239471/73649956-ebf8c800-46bb-11ea-9645-f8f9f6e59dc2.jpg)

进入libobjc.dylib寻找_xref_dispose函数，最后找到函数在libxpc.dylib模块中
![131580729111_ pic](https://user-images.githubusercontent.com/2239471/73650043-28c4bf00-46bc-11ea-940a-df5b2d5630c2.jpg)

然后在[OS_xpc_object _xref_dispose]中进入死循环，一直调用此函数直至把栈撑满啦

**Comment by zhkl0228** [comment]
初始化时将加载的模块内存段全设置为可写，这个操作有可能会引入新的问题

**Comment by zhkl0228** [comment]
我的想法是，按正常逻辑加载到内存，运行出行的异常，逐一找到问题原因并解决

**Comment by chago** [comment]
@zhkl0228 好勒，什么时候有空把iOS64模拟也弄好啊

**Comment by zhkl0228** [comment]
这个问题已修复

**Comment by chago** [comment]
Makr

    // These fields should be set to zero because of the 
    // binding of _objc_empty_vtable, but OS X 10.8's dyld 
    // does not bind shared cache absolute symbols as expected.
    // This (and the __ARCLite__ hack below) can be removed 
    // once the simulator drops 10.8 support.
#if TARGET_OS_SIMULATOR
    if (cls->cache._mask) cls->cache._mask = 0;
    if (cls->cache._occupied) cls->cache._occupied = 0;
    if (cls->ISA()->cache._mask) cls->ISA()->cache._mask = 0;
    if (cls->ISA()->cache._occupied) cls->ISA()->cache._occupied = 0;
#endif
