### ISSUE TITLE
 How to use the program.

### ISSUE THREAD

**Issue by Kindles7** [zhkl0228/unidbg#97]
Hello. Help understand the use of the program. I have a native .so library. I know how its internal method is called from apk and what parameters need to be passed. From the examples it’s not clear how to use the program with a third-party library. What do I need to do. I hope for help. Thanks.

**Comment by zhkl0228** [comment]
Send the apk, tell me the calling parameters, I will try to write an example for you

**Comment by Kindles7** [comment]
Many thanks for the help. Attached apk. This is tiktok. I am trying to access the leviathan native function. As I understand it, its implementation is in "libcms.so". [https://drive.google.com/open?id=1gXw8zYU1gd4hns9Lm8FreXuV8el-66IR](url)

**Comment by zhkl0228** [comment]
tiktok is too complex

**Comment by Kindles7** [comment]
Using your program, you can’t call that function?

**Comment by Kindles7** [comment]
maybe I didn’t understand how it works. I managed to call leviathan and get values ​​using frida and the android emulator. But it is very resource intensive.
